#ifndef DND_CLASSCONST_IN
#define DND_CLASSCONST_IN

#define DND_DOOMGUY_DMGREDUCE_PERCENT 10
#define DND_DOOMGUY_DROPCHANCE 0.05
#define DND_DOOMGUY_HEALDIV 100
#define DND_DOOMGUY_MAXHEAL 10000
#define DND_DOOMGUY_DMGBONUS 20 // 20%
#define DND_DOOMGUY_RESISTPCT 33

#define DND_MARINE_DMGREDUCE_TIMER (TICRATE * 15)
#define DND_MARINE_PERK50_COOLDOWN (TICRATE * 180)
#define DND_MARINE_PERK50_HPPER 250

#define DND_HOBO_RESISTPCT 25
#define DND_HOBO_SHOTGUNTAGLIMIT 3
#define DND_HOBO_FRENZYBASETIME (TICRATE * 12)
#define DND_HOBO_ACCURACYBONUS 50
#define DND_HOBO_SHOTGUNFALLOFFDIST 400 // this is the least amount of distance his level 50 perk will gain bonuses from
#define DND_HOBO_SHOTGUNMINBESTDIST (2 * DND_PLAYER_RADIUS)
#define DND_HOBO_SHOTGUNMINBESTDIST_INT ((DND_HOBO_SHOTGUNMINBESTDIST) >> 16)

#define DND_WANDERER_PERK25_BUFF 25 // 25%

#define DND_WANDERER_RESREDUCE 10

#define DND_CYBORG_CYBER_MULT 3
#define DND_CYBORG_CYBER_DIV 10
#define DND_MAXCYBORG_INSTABILITY 10
#define DND_DMG_PER_INSTABILITY 2
#define DND_CYBORG_INSTABILITY_CHANCE 0.5 // 50% percent
#define DND_CYBORG_INSTABILITY_TIMER 165

#define DND_BERSERKER_PERK50_MAXSTACKS 30
#define DND_BERSERKER_PERK50_CRITBONUS 50

#define DND_BERSERKER_DAMAGETRACKTIME 122 // 3 is base, x 5 -- +2 for 0.5 second of buffer inclusion
#define DND_BERSERKER_PERK25_MAXSTACKS 15
#define DND_BERSERKER_PERK25_HEALPERCENT 15
#define DND_BERSERKER_PERK25_REDUCTION 2 // 2% per stack
#define DND_BERSERKER_PERK50_TIMER 70 // 14 x 5 = 70 => 2 seconds
#define DND_BERSERKER_PERK50_DMGINCREASE 8 // 8%

#endif