#ifndef DND_MENUCONSTANTS_IN
#define DND_MENUCONSTANTS_IN

#define DND_QUICKBUY_POPUPID 0xFFFF

// Box definitions for clickables
// 7 images on menu leftmost bar
#define MAX_MAIN_BOXES 10

// Mainbox Labels
enum {
	MAINBOX_NONE = 0,
	MAINBOX_STATS,
	MAINBOX_PERK,
	MAINBOX_LOAD,
	MAINBOX_SHOP,
	MAINBOX_RESEARCH,
	MAINBOX_ABILITY,
	MAINBOX_HELP,
	MAINBOX_LARR,
	MAINBOX_RET,
	MAINBOX_RARR
};

// Various box enums (I know this part is terrible, dk how to make it look better atm)
// Definition rule: L -> R, T -> B
enum {
	MBOX_1 = 1,
	MBOX_2,
	MBOX_3,
	MBOX_4,
	MBOX_5,
	MBOX_6,
	MBOX_7,
	MBOX_8,
	MBOX_9,
	MBOX_10,
	MBOX_11,
	MBOX_12,
	MBOX_13,
	MBOX_14,
	MBOX_15,
	MBOX_16
};

// Page definitions
enum { 
	MENU_NULL,
	MENU_STAT1,
	MENU_STAT2,
	MENU_STAT3,
	
	MENU_PERK,
	
	MENU_LOAD,
	MENU_LOAD1,
	MENU_LOAD2,
	MENU_LOAD3,
	MENU_LOAD_ACC1,
	MENU_LOAD_ACC2,
	MENU_LOAD_ACC3,
	MENU_LOAD_ACC4,
	
	MENU_SHOP,
	MENU_SHOP_WEAPON,
	MENU_SHOP_WEAPON1,
	MENU_SHOP_WEAPON2,
	MENU_SHOP_WEAPON3_1,
	MENU_SHOP_WEAPON3_2,
	MENU_SHOP_WEAPON4,
	MENU_SHOP_WEAPON5,
	MENU_SHOP_WEAPON6,
	MENU_SHOP_WEAPON7,
	MENU_SHOP_WEAPON8,
	
	MENU_SHOP_AMMO1,
	MENU_SHOP_AMMO2,
	MENU_SHOP_AMMO3,
	MENU_SHOP_AMMO_SPECIAL1,
	
	MENU_SHOP_ABILITY_1,
	MENU_SHOP_ABILITY_2,
	MENU_SHOP_ARTIFACT,
	MENU_SHOP_TALENT,
	MENU_SHOP_ARMOR1,
	MENU_SHOP_ARMOR2,
	MENU_RESEARCH,
	MENU_MAIN,
	MENU_HELP,
	MENU_HELP_CHARACTER,
	MENU_HELP_RESEARCHES,
	MENU_HELP_DAMAGETYPES,
	MENU_HELP_ORBS,
	MENU_HELP_LEGMONS,
	MENU_HELP_MMODS,
	MENU_ABILITY
};

enum {
	// wep slot 1
		SHOP_WEP_CSAW = 0,
		SHOP_WEP_KATANA,
		SHOP_WEP_SICKLE,
		SHOP_WEP_EXCALIBAT,
		SHOP_WEP_DUSKBLADE,
		SHOP_WEP_INFERNOSWORD,

	// wep slot 2
		SHOP_WEP_AKIMBOPISTOL,
		SHOP_WEP_MAGNUM,
		SHOP_WEP_LASERPISTOL,
		SHOP_WEP_RESPIS1,
		SHOP_WEP_RESPIS2,
		SHOP_WEP_RUBYWAND,
		SHOP_WEP_SCATTERPISTOL,

	// wep slot 3
		SHOP_WEP_PURIFIER,
		SHOP_WEP_AUTOSG,
		SHOP_WEP_RESSG1,
		SHOP_WEP_RESSG2,
		SHOP_WEP_HSSG,
		SHOP_WEP_ERASUS,
		SHOP_WEP_RESSSG1,
		SHOP_WEP_RESSSG2,

	// wep slot 3 - 2
		SHOP_WEP_SILVER,
		SHOP_WEP_SLAYER,

	// wep slot 4
		SHOP_WEP_HMG,
		SHOP_WEP_LEAD,
		SHOP_WEP_DSEAL,
		SHOP_WEP_RESMG1,
		SHOP_WEP_RESMG2,
		SHOP_WEP_RESMG3,
		SHOP_WEP_MINIGUN,
		SHOP_WEP_EBONY,

	// wep slot 5
		SHOP_WEP_TORPEDO,
		SHOP_WEP_MERC,
		SHOP_WEP_RESRL1,
		SHOP_WEP_RESRL2,
		SHOP_WEP_RESRL3,
		SHOP_WEP_GRENADE,
		SHOP_WEP_ROTARYGL,
		SHOP_WEP_HEAVYML,

	// wep slot 6
		SHOP_WEP_NUCLEARPL,
		SHOP_WEP_TUREL,
		SHOP_WEP_FROSTFANG,
		SHOP_WEP_RESPL1,
		SHOP_WEP_RESPL2,
		SHOP_WEP_NAIL,
		SHOP_WEP_BASILISK,

	// wep slot 7
		SHOP_WEP_BFG,
		SHOP_WEP_DEVA,
		SHOP_WEP_MFG,
		SHOP_WEP_RESBFG1,
		SHOP_WEP_RESBFG2,
		SHOP_WEP_GAUSS,
		SHOP_WEP_RAIL,

	// wep slot 8
		SHOP_WEP_DEATHSTAFF,
		SHOP_WEP_RAZOR,
		SHOP_WEP_SUN,
		SHOP_WEP_REAVER,

	// ammo - 1
		SHOP_AMMO_CLIP,
		SHOP_AMMO_SHELL,
		SHOP_AMMO_ROCKET,
		SHOP_AMMO_CELL,
		SHOP_AMMO_EXPSHELL,
		SHOP_AMMO_EBONY,
		SHOP_AMMO_EBONYX,
		SHOP_AMMO_MIS,
		SHOP_AMMO_GL,
		SHOP_AMMO_NAIL,

	// ammo 2
		SHOP_AMMO_BASILISK,
		SHOP_AMMO_GAUSS,
		SHOP_AMMO_SLAYER,
		SHOP_AMMO_RUBY,
		SHOP_AMMO_PCAN,
		SHOP_AMMO_RIOTSHELL,
		SHOP_AMMO_METEOR,
		SHOP_AMMO_FUEL,
		SHOP_AMMO_LG,
		SHOP_AMMO_NITROGEN,

	// ammo 3
		SHOP_AMMO_ION,
		SHOP_AMMO_ACID,
		SHOP_AMMO_EVERICE,
		SHOP_AMMO_VIPER,
		SHOP_AMMO_THUNDER,
		SHOP_AMMO_DSEAL,

	// ammo special
		SHOP_AMMO_FLECHETTE,
		SHOP_AMMO_PIERCING,
		SHOP_AMMO_ELECTRIC,
		SHOP_AMMO_NITROSHELL,
		SHOP_AMMO_SONICGRENADE,
		SHOP_AMMO_HEGRENADE,

	// abilities
		SHOP_ABILITY_KICK,
		SHOP_ABILITY_RELOAD,
		SHOP_ABILITY_DASH,
		SHOP_ABILITY_ARCANE,
		SHOP_ABILITY_POISON,
		SHOP_ABILITY_EXPLOSION,
		SHOP_ABILITY_HEART,
		SHOP_ABILITY_REGEN,
		SHOP_ABILITY_TEMPORAL,
		SHOP_ABILITY_SOUL,
		SHOP_ABILITY_MONSTERINFO,

	// talents
		SHOP_TALENTBULLET,
		SHOP_TALENTMELEE,
		SHOP_TALENTOCCULT,
		SHOP_TALENTEXPLOSIVE,
		SHOP_TALENTENERGY,
		SHOP_TALENTELEMENTAL,

		SHOP_ARMOR_GREEN,
		SHOP_ARMOR_YELLOW,
		SHOP_ARMOR_BLUE,
		SHOP_ARMOR_RED,
		SHOP_ARMOR_GUNSLINGER,
		SHOP_ARMOR_OCCULT,
		SHOP_ARMOR_DEMO,
		SHOP_ARMOR_ENERGY,
		SHOP_ARMOR_ELEMENTAL,

	// armor 2
		SHOP_ARMOR_MONOLITH,
		SHOP_ARMOR_CYBERNETIC,
		SHOP_ARMOR_DUELIST,
		SHOP_ARMOR_NECRO,
		SHOP_ARMOR_KNIGHT,
		SHOP_ARMOR_RAVAGER,

	// arti
		SHOP_ARTI_KIT,
		SHOP_ARTI_SALVATE,
		SHOP_ARTI_SHIELD,
		SHOP_ARTI_BLOOD,
		SHOP_ARTI_TRIPLE,
		SHOP_ARTI_VORTEX,
		SHOP_ARTI_BOOK,
		SHOP_ARTI_MAP,
		SHOP_ARTI_BACKPACK,
		SHOP_ARTI_RESET
};

#define MAXSHOPITEMS SHOP_ARTI_RESET + 1

#define SHOP_FIRSTARMOR_INDEX SHOP_ARMOR_GREEN
#define SHOP_FIRSTARMOR2_INDEX SHOP_ARMOR_MONOLITH
#define SHOP_ARMORPAGE1_BEGIN SHOP_FIRSTARMOR_INDEX
#define SHOP_ARMORPAGE2_BEGIN SHOP_FIRSTARMOR2_INDEX
#define SHOP_FIRSTAMMO_INDEX SHOP_AMMO_CLIP
#define SHOP_FIRSTAMMO2_INDEX SHOP_AMMO_BASILISK
#define SHOP_FIRSTAMMO3_INDEX SHOP_AMMO_ION
#define SHOP_FIRSTAMMOSPECIAL_INDEX SHOP_AMMO_FLECHETTE
#define SHOP_FIRSTARTI_INDEX SHOP_ARTI_KIT
#define SHOP_ABILITY1_BEGIN SHOP_ABILITY_KICK
#define SHOP_ABILITY2_BEGIN SHOP_ABILITY_TEMPORAL
#define SHOP_TALENT_BEGIN SHOP_TALENTBULLET

#define SHOP_WEAPON_BEGIN SHOP_WEP_CSAW
#define SHOP_WEAPON1_BEGIN SHOP_WEP_CSAW
#define SHOP_WEAPON2_BEGIN SHOP_WEP_AKIMBOPISTOL
#define SHOP_WEAPON31_BEGIN SHOP_WEP_PURIFIER
#define SHOP_WEAPON3SSG_BEGIN SHOP_WEP_HSSG
#define SHOP_WEAPON32_BEGIN SHOP_WEP_SILVER
#define SHOP_WEAPON4_BEGIN SHOP_WEP_HMG
#define SHOP_WEAPON5_BEGIN SHOP_WEP_TORPEDO
#define SHOP_WEAPON6_BEGIN SHOP_WEP_NUCLEARPL
#define SHOP_WEAPON7_BEGIN SHOP_WEP_BFG
#define SHOP_WEAPON8_BEGIN SHOP_WEP_DEATHSTAFF

#define SHOP_WEAPON_SLOT1END SHOP_WEP_INFERNOSWORD
#define SHOP_WEAPON_SLOT2END SHOP_WEP_SCATTERPISTOL
#define SHOP_WEAPON_SLOT31END SHOP_WEP_RESSSG2
#define SHOP_WEAPON_SLOT32END SHOP_WEP_SLAYER
#define SHOP_WEAPON_SLOT3END SHOP_WEP_SLAYER
#define SHOP_WEAPON_SLOT4END SHOP_WEP_EBONY
#define SHOP_WEAPON_SLOT5END SHOP_WEP_HEAVYML
#define SHOP_WEAPON_SLOT6END SHOP_WEP_BASILISK
#define SHOP_WEAPON_SLOT7END SHOP_WEP_RAIL
#define SHOP_WEAPON_SLOT8END SHOP_WEP_REAVER

#define SHOP_LASTAMMO_INDEX SHOP_AMMO_SLAYER
#define SHOP_LASTAMMO1_INDEX SHOP_AMMO_NAIL
#define SHOP_LASTAMMO2_INDEX SHOP_AMMO_NITROGEN
#define SHOP_LASTAMMO3_INDEX SHOP_AMMO_DSEAL
#define SHOP_LASTAMMO_SPECIALINDEX SHOP_AMMO_HEGRENADE
#define SHOP_LASTWEP_INDEX SHOP_WEP_REAVER
#define SHOP_ABILITY1_END SHOP_ABILITY_REGEN
#define SHOP_LASTABILITY_INDEX SHOP_ABILITY_MONSTERINFO
#define SHOP_LASTTALENT_INDEX SHOP_TALENTELEMENTAL
#define SHOP_LASTARMOR_INDEX SHOP_ARMOR_RAVAGER
#define SHOP_LASTARTI_INDEX SHOP_ARTI_RESET
#define SHOP_LASTDRAWNARTI_INDEX SHOP_ARTI_BOOK
#define SHOP_ARMORPAGE1_END SHOP_ARMOR_ELEMENTAL

#define MENU_FIRST_ACCESSORY_PAGE MENU_LOAD_ACC1
#define MENU_LAST_ACCESSORY_PAGE MENU_LOAD_ACC4

#define PAGE1_ARMOR_COUNT SHOP_FIRSTARMOR2_INDEX - SHOP_FIRSTARMOR_INDEX
#define PAGE2_ARMOR_COUNT SHOP_LASTARMOR_INDEX - SHOP_FIRSTARMOR2_INDEX

#define MAXSHOPWEAPONS SHOP_LASTWEP_INDEX - SHOP_WEAPON_BEGIN + 1
#define MAXSHOPAMMOS SHOP_LASTAMMO_SPECIALINDEX - SHOP_FIRSTAMMO_INDEX + 1
#define MAXABILITIES SHOP_LASTABILITY_INDEX - SHOP_ABILITY1_BEGIN + 1
#define MAXARTIFACTS SHOP_LASTARTI_INDEX - SHOP_FIRSTARTI_INDEX + 1

#define MENU_HELP_BEGIN MENU_HELP_CHARACTER
#define MENU_HELP_END MENU_HELP_MMODS

#define AMMO_ICON 0
#define AMMO_NAME 1	
#define AMMO_PAGE2_BEGIN SHOP_FIRSTAMMO2_INDEX - SHOP_FIRSTAMMO_INDEX
#define AMMO_PAGE3_BEGIN SHOP_FIRSTAMMO3_INDEX - SHOP_FIRSTAMMO_INDEX
#define AMMO_PAGESPECIAL_BEGIN SHOP_FIRSTAMMOSPECIAL_INDEX - SHOP_FIRSTAMMO_INDEX
str AmmoInfo[MAXSHOPAMMOS][2] = {
	{ "CLIPA0",			"Clip"								},
	{ "SHELA0",			"Shell"								},
	{ "ROCKA0",			"RocketAmmo"						},
	{ "CELLA0",			"Cell"								},
	{ "ESHAA0",			"ExplodingShell"					},
	{ "EBOPA0",			"EbonyAmmo"						    },
	{ "EBOPE0",			"EbonyAmmoX"						},
	{ "AHRLA0",			"MISAmmo"							},
	{ "GBUNA0",			"Grenades" 							},
	{ "NPAKA0",			"NailgunAmmo"						},
	
	{ "BASIA01",		"BasiliskAmmo"						},
	{ "GAUSICO",		"GaussRound"						},
	{ "SLAYAM01",		"SlayerAmmo"						},
	{ "RBAMA0",			"RubyAmmo"							},
	{ "PCNIC1",         "PCanAmmo"                          },
	{ "RIOTJ0",         "RiotgunShell"                      },
	{ "LAAM1",          "MeteorAmmo"                        },
	{ "FUAMA0",         "Fuel"                              },
	{ "D98AB1",         "LightningCell"                     },
	{ "D97A1",          "NitrogenCanister"                  },
	
	{ "IONAMM1",        "IonAmmo"                           },
	{ "D97AA0",			"AcidAmmo"							},
	{ "EICEAM1",		"EverIce"							},
	{ "C_H2A1",			"ViperAmmo"							},
	{ "D95AA0",			"ThunderAmmo"						},
	{ "DEMSICO",		"DSealAmmo"							},

	{ "SAM1A0",			"FlechetteShell"				    },
	{ "SAM3A0",			"PiercingShell"						},
	{ "SAM2A0",			"ElectricShell"						},
	{ "SAM4A0",         "NitroShell"                        },
	
	{ "GAM1A0",			"A40MMSonicGrenade"			        },
	{ "GAM2A0",			"A40MMHEGrenade"				    }
};

str AbilityInfo[MAXABILITIES] = {
	"Ability_Kick",
	"Ability_Reloader",
	"Ability_Dash",
	"Ability_Arcanery",
	"Ability_AntiPoison",
	"Ability_ExplosionMastery",
	"Ability_HeartSeeker",
	"Ability_Regeneration",
	"Ability_Temporal",
	"Ability_SoulStealer",
	"Ability_MonsterInfo"
};

#define ARTI_ICON 0
#define ARTI_NAME 1
str ArtifactInfo[MAXARTIFACTS][2] = { 
	{ "FKITD0",				"FieldKit"				},	
	{ "SALVRICO",			"SalvationSphere"		},
	{ "SHIELICO",			"PortableShield"		},
	{ "BRUNICO",			"BloodRune"				},
	{ "DMGICO",			    "TripleDamage"			},
	{ "SHRUA0",			    "BladeVortex"			},
	{ "BOTDICO",		    "BookOfTheDead"		    },
	{ "PMAPA0",			    "AllMapOnlyOnce"		},
	{ "BPAKA0",			    "NewBackPack"			},
	{ "RESETICO",           "StatReset"             }
};

#define MAXCLIPAMMOTYPES 26
str ClipAmmoTypes[MAXCLIPAMMOTYPES] = {
	"SpecialAmmoMode_3",
	"SpecialAmmoMode_3X",
	"SpecialAmmoMode_4",
	"SpecialAmmoMode_5",
	"SpecialAmmoMode_5X",
	"GoreMode",
	"BladeCharge",
	"SawedoffCounter",
	"AkimboClipLeft",
	"AkimboClipRight",
	"BulletSize_6",
	"ShellSize_2",
	"ShellSize_8",
	"ShellSize_8N",
	"ShellSize_10",
	"ShellSize_12",
	"MGClip",
	"MGClip2",
	"MGClip3",
	"MGClip4",
	"MGClip5",
	"LoadedBasilisk",
	"PCanClip",
	"RiotgunClip",
	"AcidClip",
	"HeavyGLCounter",
};

#define MAX_ACCESSORIES DND_ACCESSORY_LICHARM + 1

#endif