#ifndef DND_ATKINFO_IN
#define DND_ATKINFO_IN

#define ATK_CACHE_SHIFT 9
#define ATK_DTYPE_SHIFT 3
#define ATK_DPCT_SHIFT 5

#define CACHE_SHIFT 9
#define DTYPE_SHIFT 12
#define DPCT_SHIFT 17
#define BITMASK_NOFACTOR (0x1FFFF) // depends on DPCT_SHIFT, 17 1s

#define ATK_WID_MASK (0x1FF)
#define ATK_CACHE_MASK (0x7)
#define ATK_DTYPE_MASK (0x1F)
#define ATK_DPCT_MASK (0x3FF)

#define SPELL_DMG_SHIFT 16
#define SPELL_DTYPE_SHIFT 5

#define SPELLDMG_MASK (0xFFFF)
#define SPELLDTYPE_MASK (0x1F)
#define SPELLID_MASK (0x3FF)

#endif