#ifndef DND_GLOBAL_IN
#define DND_GLOBAL_IN

enum {
	DND_CONSTANT_EXPCURVE,
	DND_CONSTANT_MONSTER_LEVEL_DROPBOOST,

	DND_MAX_CONSTANTS
};

enum {
	DND_SHOPINFO_PRICE,
	DND_SHOPINFO_MAX,
	DND_SHOPINFO_STOCK,

	DND_SHOPINFO_REQUIREMENT1,
	DND_SHOPINFO_REQUIREMENT2,
	DND_SHOPINFO_REQUIREMENT3,

	DND_SHOPINFO_ARRLIMIT
};
#define MAX_RESEARCH_REQUIREMENTS 3

enum {
	MONSTERDATA_VARIATIONCOUNT,
	MONSTERDATA_WEIGHTSUM
};

enum {
	MONSTERCLASS_ZOMBIEMAN,
	MONSTERCLASS_SHOTGUNGUY,
	MONSTERCLASS_CHAINGUNGUY,
	MONSTERCLASS_DEMON,
	MONSTERCLASS_SPECTRE,
	MONSTERCLASS_IMP,
	MONSTERCLASS_CACODEMON,
	MONSTERCLASS_PAINELEMENTAL,
	MONSTERCLASS_LOSTSOUL,
	MONSTERCLASS_REVENANT,
	MONSTERCLASS_HELLKNIGHT,
	MONSTERCLASS_BARON,
	MONSTERCLASS_FATSO,
	MONSTERCLASS_ARACHNOTRON,
	MONSTERCLASS_ARCHVILE,
	MONSTERCLASS_SPIDERMASTERMIND,
	MONSTERCLASS_CYBERDEMON,
	MONSTERCLASS_WOLFENSS
};

// First element on each list is the "Vanilla" monster, rest follow from their variations with Var1 to VarX
#define MAX_MONSTER_CATEGORIES (MONSTERCLASS_WOLFENSS + 1)

enum {
	// wep slot 1
		SHOP_WEP_CSAW = 0,
		SHOP_WEP_KATANA,
		SHOP_WEP_EXCALIBAT,
		SHOP_WEP_INFERNOSWORD,
		SHOP_WEP_DUSKBLADE,
		SHOP_WEP_SICKLE,

	// wep slot 2
		SHOP_WEP_AKIMBOPISTOL,
		SHOP_WEP_MAGNUM,
		SHOP_WEP_LASERPISTOL,
		SHOP_WEP_RUBYWAND,
		SHOP_WEP_RESPIS1,
		SHOP_WEP_RESPIS2,
		SHOP_WEP_SCATTERPISTOL,

	// wep slot 3 - 1
		SHOP_WEP_PURIFIER,
		SHOP_WEP_AUTOSG,
		SHOP_WEP_EMERALDWAND,
		SHOP_WEP_RESSG1,
		SHOP_WEP_RESSG2,
		SHOP_WEP_RESSG3,
		SHOP_WEP_RESSG4,
		SHOP_WEP_HSSG,
		
	// wep slot 3 - 2
		SHOP_WEP_ERASUS,
		SHOP_WEP_HELLSMAW,
		SHOP_WEP_AXE,
		SHOP_WEP_RESSSG1,
		SHOP_WEP_RESSSG2,
		SHOP_WEP_RESSSG3,
		SHOP_WEP_RESSSG4,
		SHOP_WEP_SILVER,

	// wep slot 3 - 3 
		SHOP_WEP_SLAYER,

	// wep slot 4 - 1
		SHOP_WEP_HMG,
		SHOP_WEP_LEAD,
		SHOP_WEP_DSEAL,
		SHOP_WEP_RESMG1,
		SHOP_WEP_RESMG2,
		SHOP_WEP_RESMG3,
		SHOP_WEP_RESMG4,
		SHOP_WEP_RESMG5,
		
	// wep slot 4 - 2
		SHOP_WEP_DESOLATOR,
		SHOP_WEP_MINIGUN,
		SHOP_WEP_EBONY,
		SHOP_WEP_MPPB,

	// wep slot 5 - 1
		SHOP_WEP_TORPEDO,
		SHOP_WEP_GRENADE,
		SHOP_WEP_VINDICATOR,
		SHOP_WEP_HAMMER,
		SHOP_WEP_RESRL1,
		SHOP_WEP_RESRL2,
		SHOP_WEP_RESRL3,
		SHOP_WEP_RESRL4,
		
	// wep slot 5 - 2
		SHOP_WEP_RESRL5,
		SHOP_WEP_MERC,
		SHOP_WEP_ROTARYGL,
		SHOP_WEP_HEAVYML,
		SHOP_WEP_SEDRIN,

	// wep slot 6 - 1
		SHOP_WEP_NUCLEARPL,
		SHOP_WEP_TUREL,
		SHOP_WEP_FROSTFANG,
		SHOP_WEP_SNIPER,
		SHOP_WEP_RESPL1,
		SHOP_WEP_RESPL2,
		SHOP_WEP_RESPL3,
		SHOP_WEP_RESPL4,
		
	// wep slot 6 - 2
		SHOP_WEP_RHINO,
		SHOP_WEP_NAIL,
		SHOP_WEP_BASILISK,

	// wep slot 7
		SHOP_WEP_BFG,
		SHOP_WEP_DEVA,
		SHOP_WEP_MFG,
		SHOP_WEP_RESBFG1,
		SHOP_WEP_RESBFG2,
		
		SHOP_WEP_GAUSS,
		SHOP_WEP_RAIL,
		SHOP_WEP_DEATHRAY,

	// wep slot 8
		SHOP_WEP_DEATHSTAFF,
		SHOP_WEP_RAZOR,
		SHOP_WEP_SUN,
		SHOP_WEP_REAVER,

	// ammo list
		SHOP_AMMO_CLIP,
		SHOP_AMMO_SHELL,
		SHOP_AMMO_ROCKET,
		SHOP_AMMO_CELL,
		SHOP_AMMO_EXPSHELL,
		SHOP_AMMO_EBONY,
		SHOP_AMMO_EBONYX,
		SHOP_AMMO_MIS,
		SHOP_AMMO_GL,
		SHOP_AMMO_NAIL,
		
		SHOP_AMMO_BASILISK,
		SHOP_AMMO_GAUSS,
		SHOP_AMMO_SLAYER,
		SHOP_AMMO_RUBY,
		SHOP_AMMO_PCAN,
		SHOP_AMMO_RIOTSHELL,
		SHOP_AMMO_METEOR,
		SHOP_AMMO_FUEL,
		SHOP_AMMO_LG,
		SHOP_AMMO_NITROGEN,
		
		SHOP_AMMO_ION,
		SHOP_AMMO_ACID,
		SHOP_AMMO_EVERICE,
		SHOP_AMMO_VIPER,
		SHOP_AMMO_THUNDER,
		SHOP_AMMO_DSEAL,
		SHOP_AMMO_FUSION,
		SHOP_AMMO_FLAK,
		SHOP_AMMO_DESOLATOR,
		SHOP_AMMO_HADES,
		
		SHOP_AMMO_DEMONBLOOD,
		SHOP_AMMO_EMERALDMANA,
		SHOP_AMMO_HELLSMAW,
		SHOP_AMMO_DEVASTATOR,
		SHOP_AMMO_HEAVYGRENADE,
		SHOP_AMMO_FLAYER,
		SHOP_AMMO_GRAVDIS,
		SHOP_AMMO_SEDRIN,
		SHOP_AMMO_CHARON,
		SHOP_AMMO_INCINERATOR,

		SHOP_AMMO_AXEMANA,
		SHOP_AMMO_HAMMER,
		SHOP_AMMO_SNIPER,

	// ammo special
		SHOP_AMMO_FLECHETTE,
		SHOP_AMMO_PIERCING,
		SHOP_AMMO_ELECTRIC,
		SHOP_AMMO_NITROSHELL,
		SHOP_AMMO_SLUGSHELL,
		SHOP_AMMO_SONICGRENADE,
		SHOP_AMMO_HEGRENADE,

	// abilities
		SHOP_ABILITY_PARRY,
		SHOP_ABILITY_RELOAD,
		SHOP_ABILITY_DASH,
		SHOP_ABILITY_ARCANE,
		SHOP_ABILITY_POISON,
		SHOP_ABILITY_EXPLOSION,
		SHOP_ABILITY_HEART,
		SHOP_ABILITY_REGEN,
		SHOP_ABILITY_TEMPORAL,
		SHOP_ABILITY_SOUL,
		
	// account
		SHOP_ACCOUNT_STASHTAB,

	// arti
		SHOP_ARTI_KIT,
		SHOP_ARTI_SALVATE,
		SHOP_ARTI_SHIELD,
		SHOP_ARTI_BLOOD,
		SHOP_ARTI_TRIPLE,
		SHOP_ARTI_VORTEX,
		SHOP_ARTI_BOOK,
		SHOP_ARTI_MAP,
		SHOP_ARTI_BACKPACK,
		SHOP_ARTI_RESET,
		SHOP_ARTI_RADSUIT
};

#define MAXSHOPITEMS (SHOP_ARTI_RADSUIT + 1)

typedef struct {
	int initial_capacity;
	str icon;
	str name;
} ammo_info_T;

typedef struct {
    ammo_info_T[]?[]? AmmoInfo;

	int DnD_Constants[DND_MAX_CONSTANTS][256];

	int ShopInfo[MAXSHOPITEMS][DND_SHOPINFO_ARRLIMIT];

	int ShopStockRemaining[MAXPLAYERS][MAXSHOPITEMS];
	
	int MonsterCategoryData[MAX_MONSTER_CATEGORIES][2];
} globals_T;

global globals_T 47: GlobalData;

void Build_Constants() {
	// the exp curve is assuming level DND_EXP_ADJUST_LEVEL and above as the value, but the array is 0 - (100 - DND_EXP_ADJUST_LEVEL) range
	int i = 0;
	for(; i <= MAXLEVELS - DND_EXP_ADJUST_LEVEL; ++i) {
		GlobalData.DnD_Constants[DND_CONSTANT_EXPCURVE][i] = fpow(DND_EXP_ADJUST_LEVELFACTOR, i + 1);
		//Log(d:i, s: " => ", f:DnD_Constants[DND_CONSTANT_EXPCURVE][i]);
	}

	for(i = 0; i < MAXLEVELS; ++i) {
		GlobalData.DnD_Constants[DND_CONSTANT_MONSTER_LEVEL_DROPBOOST][i] = GetMonsterLevelDroprateBonus(i + 1);
	}
}

#include "DnD_DropTables.h"

#endif