#ifndef DND_DATABASEROWS_IN
#define DND_DATABASEROWS_IN

#define DND_DB_WEAPONINT "DND_PlayerWeapons_"
#define DND_DB_STATS_1 "DND_PlayerStats_1"
#define DND_DB_STATS_2 "DND_PlayerStats_2"
#define DND_DB_STATS_3 "DND_PlayerStats_3"
#define DND_DB_PERKS "DND_PlayerPerks"
#define DND_DB_PERKS2 "DND_PlayerPerks2"
#define DND_DB_HEALTHARMOR "DND_PlayerHealthArmor"
#define DND_DB_ARMORTYPE "DND_PlayerArmorType"
#define DND_DB_AMMO "DND_PlayerAmmo_"
#define DND_DB_SPECIALAMMO "DND_PlayerSpecialAmmo_"
#define DND_DB_TEMPAMMO "DND_PlayerTemporaryAmmo"
#define DND_DB_TEMPAMMO_BLADECHARGE "DND_PlayerTemporaryAmmo_BladeCharge"
#define DND_DB_TALENT_1 "DND_PlayerTalent_1"
#define DND_DB_TALENT_2 "DND_PlayerTalent_2"
#define DND_DB_EXP "DND_PlayerEXP"
#define DND_DB_CREDIT "DND_PlayerCredit"
#define DND_DB_LEVEL "DND_PlayerLevel"
#define DND_DB_ABILITY "DND_PlayerAbilities"
#define DND_DB_ATTRIBUTEPERK "DND_PlayerUnspentStuff"
#define DND_DB_ACTIVEACCESSORIES "DND_SelectedAccessories"
#define DND_DB_ACCESSORIES "DND_PlayerAccessories"
#define DND_DB_ARTIFACTS "DND_PlayerArtifacts"
#define DND_DB_RESEARCH_DONE "DND_PlayerResearch_Done_"
#define DND_DB_RESEARCH_DISCOVERED "DND_PlayerResearch_Discovered_"
#define DND_DB_RESEARCH_INVESTED "DND_PlayerResearch_Invested_"
#define DND_DB_BUDGET "DND_PlayerBudget"
#define DND_DB_QUESTSTATE1 "DnD_PlayerQuest_1"
#define DND_DB_QUESTSTATE2 "DnD_PlayerQuest_2"
#define DND_DB_WEAPONQUALITY "DnD_WeaponQuality_"
#define DND_DB_WEAPONORBMOD_VAL "DnD_WeaponOrbModVal_"
#define DND_DB_WEAPONORBMOD_TIER "DnD_WeaponOrbModTier_"
#define DND_DB_WEAPONMOD_VAL "DnD_WeaponModVal_"
#define DND_DB_WEAPONMOD_TIER "DnD_WeaponModTier_"
#define DND_DB_STOREDKIT "DnD_StoredKit"
#define DND_DB_SURVIVECOUNT "DnD_PlayerLifeTime"
#define DND_DB_PLAYERWEPCHECKERS "DnD_PlayerWepCheckers"
#define DND_DB_MISC "DnD_PlayerMiscallenous"
#define DND_DB_KEYS "DnD_PlayerChestKeys"
#define DND_DB_RESEARCHTRACKER "DnD_ResearchTracker"
#define DND_DB_NPCTRACKER "DnD_NPCTracker"
#define DND_DB_LEGENDARYTRACKER "DnD_LegendaryKills"

#define DND_DB_KILLTRACKER "DnD_LifetimeKills"
#define DND_DB_KILLTRACKER_MILLION "DnD_LifetimeKills_Mil"
#define DND_DB_KILLTRACKER_BILLION "DnD_LifetimeKills_Bil"

// Orb Stuff
#define DND_DB_ORBFLATHPBONUS "DnD_Orb_FlatHPBonus"
#define DND_DB_ORBFLATARMBONUS "DnD_Orb_FlatARMBonus"
#define DND_DB_ORBPERCENTHPBONUS "DnD_Orb_PercentHPBonus"
#define DND_DB_ORBPERCENTARMBONUS "DnD_Orb_PercentARMBonus"
#define DND_DB_ORBGREEDBONUS "DnD_Orb_GreedBonus"
#define DND_DB_ORBWISDOMBONUS "DnD_Orb_WisdomBonus"
#define DND_DB_ORBSPEEDBONUS "DnD_Orb_SpeedBonus"
#define DND_DB_ORBDROPCHANCEBONUS "DnD_Orb_DropChanceBonus"
#define DND_DB_ORBHOLDINGBONUS "DnD_Orb_HoldingBonus"

#define DND_DB_ORBWEAPONBONUS "DnD_Orb_WeaponBonus_"
#define DND_DB_ORBWEAPONQUALITY "DnD_Orb_WeaponQuality_"

#define DND_DB_ORBDAMAGETYPEBONUS "DnD_Orb_DamageType_"

// Elixir Stuff
#define DND_DB_ELIXIRFLATHPBONUS "DnD_Elixir_FlatHPBonus"
#define DND_DB_ELIXIRFLATARMORBONUS "DnD_Elixir_FlatArmorBonus"
#define DND_DB_ELIXIRPERCENTHPBONUS "DnD_Elixir_PercentHPBonus"
#define DND_DB_ELIXIRPERCENTARMORBONUS "DnD_Elixir_PercentArmorBonus"
#define DND_DB_ELIXIRSPEEDBONUS "DnD_Elixir_SpeedBonus"
#define DND_DB_ELIXIRLUCKBONUS "DnD_Elixir_LuckBonus"
#define DND_DB_ELIXIRDAMAGETYPEBONUS "DnD_Elixir_DamageTypeBonus"

#define DND_DB_PLAYERINVENTORY "DnD_PlayerInventory_"
#define DND_DB_PLAYERINVENTORYFIELD_WIDTH "Width"
#define DND_DB_PLAYERINVENTORYFIELD_HEIGHT "Height"
#define DND_DB_PLAYERINVENTORYFIELD_IMAGE "Image"
#define DND_DB_PLAYERINVENTORYFIELD_TYPE "Type"
#define DND_DB_PLAYERINVENTORYFIELD_SUBTYPE "SubType"
#define DND_DB_PLAYERINVENTORYFIELD_LEVEL "Level"
#define DND_DB_PLAYERINVENTORYFIELD_STACK "Stack"
#define DND_DB_PLAYERINVENTORYFIELD_ATTRIBCOUNT "AttributeCount"
#define DND_DB_PLAYERINVENTORYFIELD_ATTRIBVAL "AttributeVal"
#define DND_DB_PLAYERINVENTORYFIELD_ATTRIBID "AttributeID"
#define DND_DB_PLAYERINVENTORYFIELD_ATTRIBTIER "AttributeTier"

#define DND_DB_CHARMUSED "CharmsUsed_"

#define DND_DB_STASHPAGE "StashPage_"
#define DND_DB_STASH_PAGES "DnD_PlayerStashPages"

#ifdef ISAPRILFIRST
	#define DND_DB_NFT "NFT"
#endif

#endif
