#ifndef DND_ELITEPOW_IN
#define DND_ELITEPOW_IN

enum {
	// Traitset 1
	
	DND_MELEE_RESIST, // obsolete
	
	DND_ENERGY_WEAKNESS,
	DND_SILVER_WEAKNESS,
	DND_FIRE_WEAKNESS = DND_SILVER_WEAKNESS << 1,
	DND_ICE_WEAKNESS = DND_FIRE_WEAKNESS << 1,
	DND_MAGIC_WEAKNESS = DND_ICE_WEAKNESS << 1,
	
	DND_EXPLOSIVE_RESIST = DND_MAGIC_WEAKNESS << 1,
	DND_EXPLOSIVE_IMMUNE = DND_EXPLOSIVE_RESIST << 1,
	DND_EXPLOSIVE_NONE = DND_EXPLOSIVE_IMMUNE << 1,
	DND_BULLET_RESIST = DND_EXPLOSIVE_NONE << 1,
	DND_GHOST = DND_BULLET_RESIST << 1,
	DND_HARDENED_SKIN = DND_GHOST << 1,
	DND_REFLECTIVE = DND_HARDENED_SKIN << 1,
	DND_MINIONS = DND_REFLECTIVE << 1,
	DND_CURSE = DND_MINIONS << 1,
	DND_HEAL = DND_CURSE << 1,
	DND_BLOCK = DND_HEAL << 1,
	DND_SPLIT = DND_BLOCK << 1,
	DND_RAISE = DND_SPLIT << 1,
	DND_TELEPORT = DND_RAISE << 1,
	DND_RESURRECT = DND_TELEPORT << 1,
	DND_MOBILITY = DND_RESURRECT << 1,
	DND_HOMING = DND_MOBILITY << 1,
	DND_POISON = DND_HOMING << 1,
	DND_DEATH = DND_POISON << 1,
	DND_RAGE = DND_DEATH << 1,
	DND_PIERCE = DND_RAGE << 1,
	DND_AGGRESSIVE = DND_PIERCE << 1,
	DND_EXTRAFAST = DND_AGGRESSIVE << 1,
	DND_FASTREACTION = DND_EXTRAFAST << 1,
	DND_NOPAIN = DND_FASTREACTION << 1,
	
	// Traitset 2
	
	DND_BULLET_IMMUNE = 1,
	DND_ENERGY_RESIST = DND_BULLET_IMMUNE << 1,
	DND_ENERGY_IMMUNE = DND_ENERGY_RESIST << 1,
	DND_MAGIC_RESIST = DND_ENERGY_IMMUNE << 1,
	DND_MAGIC_IMMUNE = DND_MAGIC_RESIST	<< 1,
	DND_ELEMENTAL_RESIST = DND_MAGIC_IMMUNE << 1,
	DND_ELEMENTAL_IMMUNE = DND_ELEMENTAL_RESIST << 1,
	DND_EXTRASTRONG = DND_ELEMENTAL_IMMUNE << 1,
	DND_VITAL = DND_EXTRASTRONG << 1,
	DND_ARMORPEN = DND_VITAL << 1,
	DND_PET = DND_ARMORPEN << 1,
	DND_SUMMONED = DND_PET << 1,
	DND_REVIVED = DND_SUMMONED << 1,
	DND_ICECREATURE = DND_REVIVED << 1,
	DND_FIRECREATURE = DND_ICECREATURE << 1,
	DND_STONECREATURE = DND_FIRECREATURE << 1,
	DND_ELEMENTAL_WEAKNESS = DND_STONECREATURE << 1,
	DND_EARTHCREATURE = DND_ELEMENTAL_WEAKNESS << 1,
	
	DND_LEGENDARY = DND_EARTHCREATURE << 1,
};

enum {
	DND_ENERGY_WEAKNESS_POW,
	DND_SILVER_WEAKNESS_POW,
	DND_FIRE_WEAKNESS_POW,
	DND_ICE_WEAKNESS_POW,
	DND_MAGIC_WEAKNESS_POW,
	
	DND_EXPLOSIVE_RESIST_POW,
	DND_EXPLOSIVE_IMMUNE_POW,
	DND_EXPLOSIVE_NONE_POW,
	DND_BULLET_RESIST_POW,
	DND_GHOST_POW,
	DND_HARDENED_SKIN_POW,
	DND_REFLECTIVE_POW,
	DND_MINIONS_POW,
	DND_CURSE_POW,
	DND_HEAL_POW,
	DND_BLOCK_POW,
	DND_SPLIT_POW,
	DND_RAISE_POW,
	DND_TELEPORT_POW,
	DND_RESURRECT_POW,
	DND_MOBILITY_POW,
	DND_HOMING_POW,
	DND_POISON_POW,
	DND_DEATH_POW,
	DND_RAGE_POW,
	DND_PIERCE_POW,
	DND_AGGRESSIVE_POW,
	DND_EXTRAFAST_POW,
	DND_FASTREACTION_POW,
	DND_NOPAIN_POW,
	
	// Traitset 2
	
	DND_BULLET_IMMUNE_POW = 0,
	DND_ENERGY_RESIST_POW,
	DND_ENERGY_IMMUNE_POW,
	DND_MAGIC_RESIST_POW,
	DND_MAGIC_IMMUNE_POW,
	DND_ELEMENTAL_RESIST_POW,
	DND_ELEMENTAL_IMMUNE_POW,
	DND_EXTRASTRONG_POW,
	DND_VITAL_POW,
	DND_ARMORPEN_POW,
	DND_PET_POW,
	DND_SUMMONED_POW,
	DND_REVIVED_POW,
	DND_ICECREATURE_POW,
	DND_FIRECREATURE_POW,
	DND_STONECREATURE_POW,
	DND_ELEMENTAL_WEAKNESS_POW,
	DND_EARTHCREATURE_POW,
	
	DND_LEGENDARY_POW
};

#endif