#ifndef DND_HUDDEFS_IN
#define DND_HUDDEFS_IN

#include "DnD_EliteInfo.h"

#define ASPECT_4_3 (4.0 / 3)
#define ASPECT_5_4 1.25
#define ASPECT_16_9 (16.0 / 9)
#define ASPECT_16_10 1.6

#define MAX_SCREENRES_OFFSETS 5
#define SCREEN_ASPECT_RATIO 4
int ScreenResOffsets[MAX_SCREENRES_OFFSETS] = { -1, -1, -1, -1, ASPECT_4_3 };

#define INVENTORYINFO_NORMALVIEW_WRAPX 272.0
#define INVENTORYINFO_NORMALVIEW_WRAPY 152.0

#define INVENTORYINFO_TRADEVIEW_WRAPX 304.0
#define INVENTORYINFO_TRADEVIEW_WRAPY 200.0

#define NEXT_LINE_LEN 35
#define NEXT_LINE_LEN_ATTR 30

#define NOTIFBAK_X 160
#define NOTIFBAK_Y 128
#define NOTIFBAK_XF 160.0
#define NOTIFBAK_YF 128.0

#define QSTBOX_X 250
#define QSTBOX_Y 150
#define QSTBOX_XF 250.0
#define QSTBOX_YF 150.0

#define QSTBOX2_X 288
#define QSTBOX2_Y 173
#define QSTBOX2_XF 288.0
#define QSTBOX2_YF 173.0

#define MONSTERINFO_HOLDTIME 0.2
#define EXIT_HOLDTIME 0.5

#define MILLION_MINUS_ONE 999999
#define THOUSAND_MINUS_ONE 999

#define TIPBOX_TOPLEN 70.0
#define TIPBOX_MIDLEN 39.0

#define ITEMINFOBG_TOPLEN 17.0
#define ITEMINFOBG_MIDLEN 16.0
#define ITEMINFOBG_MAXMIDS 12
#define ITEMINFO_CLIPWIDTH 360

typedef struct coord {
	int x;
	int y;
} coord_T;

// x is scroll current pos, y is scroll limit
coord_T ScrollPos = { 0, 0 };
//coord_T HudScale = { 1.0, 1.0 };

#define BOSSDATA_TID 0 // unique boss tid, this is typically dungeon boss or one off boss encounters in maps
#define BOSSDATA_HP 1 // unique boss hp, monster health isnt synced to clients
#define BOSSDATA_FORT 2
#define BOSSDATA_DMGTAKEN 3
#define BOSSDATA_DMGTRIGGER 4
#define BOSSDATA_AWAKENED 5
int DungeonBossData[6] = { 0, 0, 0, 0, 0, 0 };

// Box definitions for clickables
// 7 images on menu leftmost bar
#define MAX_MAIN_BOXES 10
#define MAX_TAGCHARS_SHOWN 17

// Mainbox Labels
enum {
	MAINBOX_NONE = 0,
	MAINBOX_STATS,
	MAINBOX_PERK,
	MAINBOX_LOAD,
	MAINBOX_SHOP,
	MAINBOX_RESEARCH,
	MAINBOX_ABILITY,
	MAINBOX_HELP,
	MAINBOX_LARR,
	MAINBOX_RET,
	MAINBOX_RARR
};

// Various box enums (I know this part is terrible, dk how to make it look better atm)
// Definition rule: L -> R, T -> B
enum {
	MBOX_1 = 1,
	MBOX_2,
	MBOX_3,
	MBOX_4,
	MBOX_5,
	MBOX_6,
	MBOX_7,
	MBOX_8,
	MBOX_9,
	MBOX_10,
	MBOX_11,
	MBOX_12,
	MBOX_13,
	MBOX_14,
	MBOX_15,
	MBOX_16
};

// MENU IDS
// Moved here because of dependencies
enum {
	RPGMENUCURSORID = 100,
	RPGMENUPOPUPID = 105,
	RPGMENUTRADECOUNTDOWNID,
	RPGMENUPAGEID = 120,
	RPGMENUHIGHLIGHTID,

	// this is used as basis for the character select menu id
	RPGMENUCHARSELID = 800,

	RPGMENUINVENTORYID = 849,
	
	RPGMENUCLICKEDID = 1749,
	RPGMENUID,
	RPGMENULARRID,
	RPGMENURARRID,
	RPGMENURETARRID,
	RPGMENUITEMIDEND,
	RPGMENUITEMID = 2050,
	RPGMENUITEMSUBID,
	RPGMENUHELPCORNERID,
	RPGMENUHELPCORNERIDMAIN,
	RPGMENUNAMEID,
	RPGMENUHELPID,
	RPGMENUINFOID,
	RPGMENUDAMAGETYPEID,
	RPGMENULISTID = 2110,
	RPGMENUWEAPONPANELID = 2150,
	RPGMENUBACKGROUNDID = 2151,
	
	// monster scanner hud id stuff
	MONSTER_TYPEICONID = 2300,
	MONSTER_TYPEICONID_RIGHT,
	MONSTER_NAMEID,
	MONSTER_TEXTID,
	MONSTER_BARFILL_OVERLAY1,
	MONSTER_BARFILL_OVERLAY2,
	MONSTER_BARFILLID,
	MONSTER_BARFILLOVERLAY,
	MONSTER_BARFILLOVERLAY2,
	MONSTER_BARFILLOVERLAY3,
	MONSTER_BARFILLOVERLAY4,
	MONSTER_TRAITID = 2400,
	
	HUD_GRAPHIC_ID = 2600,
	HUD_GRAPHIC_ID_2,

	HUD_STAMINA_FOREGROUND,
	HUD_STAMINA_PARRYCDID,
	HUD_STAMINA_PARRYDICID,
	HUD_STAMINA_ICON,

	BLACKOUT_ID = 2699,
	HUDANIMATED_ID,
	ESHIELD_LEFT_ID = 3000,
	ESHIELD_RIGHT_ID
};

void ClearMonsterScanInfo() {
	DeleteTextRange(MONSTER_TYPEICONID, MONSTER_BARFILLOVERLAY4);
	DeleteTextRange(MONSTER_TRAITID, MONSTER_TRAITID + MAX_MONSTER_TRAITS_SHOWN);
}

#endif