#ifndef DND_ELIXIR_IN
#define DND_ELIXIR_IN

#include "DnD_Stat.h"

enum {
	DND_ELIXIR_HEALTH,
	DND_ELIXIR_ARMOR,
	DND_ELIXIR_HPARMOR,
	DND_ELIXIR_HPPERCENT,
	DND_ELIXIR_ARMORPERCENT,
	DND_ELIXIR_HPARMORPERCENT,
	DND_ELIXIR_SPEED,
	DND_ELIXIR_DAMAGE,
	DND_ELIXIR_LUCK
};
#define MAX_ELIXIRS DND_ELIXIR_DAMAGE

#define ELIXIR_NAME 0
#define ELIXIR_TAG 1
str ElixirList[MAX_ELIXIRS][2] = {
	{ "ElixirOfHealth", "Elixir of Health" },
};

#endif