#ifndef DND_POPUP_IN
#define DND_POPUP_IN

enum {
	POPUP_NONE,
	POPUP_NOFUNDS,
	POPUP_CANTBUY,
	POPUP_ALREADYOWN,
	POPUP_DONTOWN,
	POPUP_NEEDRESEARCH,
	POPUP_NOBUDGET,
	POPUP_NEEDDISCOVER,
	POPUP_ALREADYRESEARCHED,
	POPUP_MAXACCESSORYEQUIPPED,
	POPUP_NOTALENTPOINT,
	POPUP_ACCESSORYNOTFOUND,
	POPUP_CHARMMISMATCH,
	POPUP_NOITEMTHERE,
	POPUP_TARGETISTRADING,
	POPUP_YOUARETRADING,
	POPUP_NOSPACEFORTRADE,
	POPUP_YOUAREMUTED,
	POPUP_ITEMNEEDSTARGET,
	POPUP_MATERIALCANTUSE,
	POPUP_ITEMTYPEMISMATCH,
	POPUP_NOSPOTFORITEM,
	POPUP_POINTLESSARMOR,
	POPUP_OUTOFSTOCK,
	POPUP_NOARMORWORN,
	POPUP_ARMORISFULL,
	POPUP_NOREPAIRTOKENS,
	POPUP_YOUARENTALLOWED,
	POPUP_PLAYERCONDNOTMET,
	POPUP_MONKILLCONDNOTMET,
	POPUP_ITEMLVLTOOHIGH,
	POPUP_NOMORESMALLCHARMS,
	POPUP_ONLYONEUNIQUE,
	POPUP_ALREADYFOUND,
	POPUP_MAXINVESTMENT,
	POPUP_NARESEARCH,
	POPUP_CANTWEARBODYARMOR,
	POPUP_CANTPUTONBODYARMOR,
	POPUP_NOTENOUGHSPACE,
	POPUP_SCAVENGECONFIRM,
	POPUP_NOTENOUGHMATERIALS,
	POPUP_CANTUSEPOWERCORE,
	POPUP_ONLYONEFLASK,
    POPUP_NODUNGEONSELECTED,
	POPUP_ALREADYDUNGEONACTIVE,
	
	#ifdef ISAPRILFIRST
	POPUP_OWNNFT,
	#endif

    MAX_POPUPS
};

str GetPopupText(int id) {
	switch(id) {
		case POPUP_NOFUNDS:
		return "DND_POPUP_NOFUNDS";
		case POPUP_CANTBUY:
		return "DND_POPUP_CANTBUY";
		case POPUP_ALREADYOWN:
		return "DND_POPUP_ALREADYOWN";
		case POPUP_DONTOWN:
		return "DND_POPUP_DONTOWN";
		case POPUP_NEEDRESEARCH:
		return "DND_POPUP_NEEDRESEARCH";
		case POPUP_NOBUDGET:
		return "DND_POPUP_NOBUDGET";
		case POPUP_NEEDDISCOVER:
		return "DND_POPUP_NEEDDISCOVER";
		case POPUP_ALREADYRESEARCHED:
		return "DND_POPUP_ALREADYRESEARCHED";
		case POPUP_MAXACCESSORYEQUIPPED:
		return "DND_POPUP_MAXACCESSORYEQUIPPED";
		case POPUP_NOTALENTPOINT:
		return "DND_POPUP_NOTALENTPOINT";
		case POPUP_ACCESSORYNOTFOUND:
		return "DND_POPUP_ACCESSORYNOTFOUND";
		case POPUP_CHARMMISMATCH:
		return "DND_POPUP_CHARMMISMATCH";
		case POPUP_NOITEMTHERE:
		return "DND_POPUP_NOITEMTHERE";
		case POPUP_TARGETISTRADING:
		return "DND_POPUP_TARGETISTRADING";
		case POPUP_YOUARETRADING:
		return "DND_POPUP_YOUARETRADING";
		case POPUP_NOSPACEFORTRADE:
		return "DND_POPUP_NOSPACEFORTRADE";
		case POPUP_YOUAREMUTED:
		return "DND_POPUP_YOUAREMUTED";
		case POPUP_ITEMNEEDSTARGET:
		return "DND_POPUP_ITEMNEEDSTARGET";
		case POPUP_MATERIALCANTUSE:
		return "DND_POPUP_MATERIALCANTUSE";
		case POPUP_ITEMTYPEMISMATCH:
		return "DND_POPUP_ITEMTYPEMISMATCH";
		case POPUP_NOSPOTFORITEM:
		return "DND_POPUP_NOSPOTFORITEM";
		case POPUP_POINTLESSARMOR:
		return "DND_POPUP_POINTLESSARMOR";
		case POPUP_OUTOFSTOCK:
		return "DND_POPUP_OUTOFSTOCK";
		case POPUP_NOARMORWORN:
		return "DND_POPUP_NOARMORWORN";
		case POPUP_ARMORISFULL:
		return "DND_POPUP_ARMORISFULL";
		case POPUP_NOREPAIRTOKENS:
		return "DND_POPUP_NOREPAIRTOKENS";
		case POPUP_YOUARENTALLOWED:
		return "DND_POPUP_YOUARENTALLOWED";
		case POPUP_PLAYERCONDNOTMET:
		return "DND_POPUP_PLAYERCONDNOTMET";
		case POPUP_MONKILLCONDNOTMET:
		return "DND_POPUP_MONKILLCONDNOTMET";
		case POPUP_ITEMLVLTOOHIGH:
		return "DND_POPUP_ITEMLVLTOOHIGH";
		case POPUP_NOMORESMALLCHARMS:
		return "DND_POPUP_NOMORESMALLCHARMS";
		case POPUP_ONLYONEUNIQUE:
		return "DND_POPUP_ONLYONEUNIQUE";
		case POPUP_ALREADYFOUND:
		return "DND_POPUP_ALREADYFOUND";
		case POPUP_MAXINVESTMENT:
		return "DND_POPUP_MAXINVESTMENT";
		case POPUP_NARESEARCH:
		return "DND_POPUP_NARESEARCH";
		case POPUP_CANTWEARBODYARMOR:
		return "DND_POPUP_CANTUSEBODYARMOR";
		case POPUP_CANTPUTONBODYARMOR:
		return "DND_POPUP_CANTPUTONBODYARMOR";
		case POPUP_NOTENOUGHSPACE:
		return "DND_POPUP_NOTENOUGHSPACE";
		case POPUP_SCAVENGECONFIRM:
		return "DND_POPUP_SCAVENGECONFIRM";
		case POPUP_NOTENOUGHMATERIALS:
		return "DND_POPUP_NOTENOUGHMATERIALS";
		case POPUP_CANTUSEPOWERCORE:
		return "DND_POPUP_CANTUSEPOWERCORE";
		case POPUP_ONLYONEFLASK:
		return "DND_POPUP_ONLYONEFLASK";
        case POPUP_NODUNGEONSELECTED:
        return "DND_POPUP_NODUNGEONSELECTED";
		case POPUP_ALREADYDUNGEONACTIVE:
		return "DND_POPUP_ALREADYDUNGEONACTIVE";
		
		#ifdef ISAPRILFIRST
		case POPUP_OWNNFT:
		return "DND_POPUP_OWNNFT";
		#endif
	}
	return "";
}

void ShowPopup(int popupid, bool isSell, int activebox) {
	ACS_NamedExecuteAlways("DnD Menu Popup", 0, Playernumber() | (popupid << 16), isSell, activebox);
}

void ShowNotif(int popupid, int activebox, int extra) {
	ACS_NamedExecuteAlways("DnD Menu Notif", 0, Playernumber() | (popupid << 16), extra, activebox);
}

void ShowActorPopup(int pnum, int popupid, bool isSell, int activebox) {
	ACS_NamedExecuteAlways("DnD Menu Popup", 0, pnum | (popupid << 16), isSell, activebox);
}

#endif