#ifndef DND_MONSTERDATA_IN
#define DND_MONSTERDATA_IN

#define DND_CUSTOMMONSTER_ID 65536

enum {
	// Classics
	MONSTER_ZOMBIEMAN,
	MONSTER_SHOTGUNNER,
	MONSTER_CHAINGUNNER,
	MONSTER_DEMON,
	MONSTER_SPECTRE,
	MONSTER_IMP,
	MONSTER_CACODEMON,
	MONSTER_PAINELEMENTAL,
	MONSTER_LOSTSOUL,
	MONSTER_REVENANT,
	MONSTER_HELLKNIGHT,
	MONSTER_BARON,
	MONSTER_FATSO,
	MONSTER_VILE,
	MONSTER_SPIDER,
	MONSTER_MASTERMIND,
	MONSTER_CYBERDEMON,
	MONSTER_NAZI,
	
	// DnD Exclusives
	
	// Zombieman
	MONSTER_ZOMBIEMANGRAY,
	MONSTER_ZOMBIERANGER,
	MONSTER_ZOMBIESMG,
	MONSTER_ZOMBIERAPID,
	MONSTER_ZOMBIEMARINE,
	MONSTER_ZOMBIELOS,
	MONSTER_ZOMBIEPISTOL,
	MONSTER_ZOMBIEQUAKE1,
	MONSTER_ZOMBIEHUNTER,
	MONSTER_ZOMBIEPROPHET,
	
	// Shotgunner
	MONSTER_SSGLOS,
	MONSTER_ZSPECSG,
	MONSTER_SGLOS,
	MONSTER_SAWEDOFF1,
	MONSTER_SAWEDOFF2,
	MONSTER_ROGUE,
	MONSTER_ZOMBIEQUAKE2,
	MONSTER_ZOMBIESSG,
	
	// Chaingunner
	MONSTER_ZOMBIEQUAKE3,
	MONSTER_ZOMBIEMG,
	MONSTER_INITIATE,
	MONSTER_DOUBLEGUNNER,
	MONSTER_CGMAJOR,
	MONSTER_MRROBOT,
	MONSTER_ZSEC,
	MONSTER_ZSPECMG,
	MONSTER_PLASMAZOMBIE,
	MONSTER_BERSERKERGUY,
	
	// Demon
	MONSTER_BLOODDEMON,
	MONSTER_BLOODFIEND,
	MONSTER_CYBERFIEND,
	MONSTER_FLAMEDEMON,
	MONSTER_STONEIMP,
	MONSTER_SCAVENGER,
	MONSTER_SOULEATER,
	MONSTER_NHUMCIGN,
	MONSTER_STONEDEMON,
	MONSTER_BRUTY,
	MONSTER_SATYR,
	MONSTER_EARTHGOLEM,
	MONSTER_RAVAGER,
	MONSTER_PUREBREDDEMON,
	
	// Spectre
	MONSTER_LURKER,
	MONSTER_GRAVEDIGGER,
	MONSTER_DEVOURER,
	MONSTER_NIGHTMAREDEMON,
	
	// Imp
	MONSTER_DARKIMP1,
	MONSTER_VOIDDARKIMP,
	MONSTER_NETHERDARKIMP,
	MONSTER_DARKIMP2,
	MONSTER_IMPABOM,
	MONSTER_STIMP,
	MONSTER_VOIDIMP,
	MONSTER_SOULHARVESTER,
	MONSTER_PYROIMP,
	MONSTER_DEVIL,
	MONSTER_DEVIL2,
	MONSTER_VULGAR,
	MONSTER_UNDEADMAGE,
	MONSTER_SHADOW,
	MONSTER_ROACH,
	
	// Lost Soul
	MONSTER_BABYCACO,
	MONSTER_ETHEREALSOUL,
	MONSTER_FLESHSPAWN,
	MONSTER_GUARDIANCUBE,
	MONSTER_FORGOTTENONE,
	MONSTER_HADESSPHERE,
	MONSTER_WATCHER,
	MONSTER_DARKLICH_SPIRIT,
	
	// Cacodemon
	MONSTER_WEAKENER,
	MONSTER_SHADOWPRIEST,
	MONSTER_GRELL,
	MONSTER_DEATHWHISPERER,
	MONSTER_CACOLICH,
	MONSTER_INFERNO,
	MONSTER_GUARDIAN,
	MONSTER_ENHANCEDCACO,
	MONSTER_EARTHLICH,
	MONSTER_WICKED,
	
	// Pain Elemental
	MONSTER_BLOODLICH,
	MONSTER_HADESELEMENTAL,
	MONSTER_HELLARBITER,
	MONSTER_DEFILER,
	MONSTER_TORTUREDSOUL,
	MONSTER_SHADOWDISCIPLE,
	MONSTER_SENTINEL,
	MONSTER_WRAITH,
	
	// Revenant
	MONSTER_INCARNATE,
	MONSTER_BEAMREVENANT,
	MONSTER_AXEKNIGHT,
	MONSTER_WIDOWMAKER,
	MONSTER_YETI,
	MONSTER_SLUDGEGIANT,
	MONSTER_SLUDGEGIANT2,
	MONSTER_SLUDGEGIANT3,
	MONSTER_CADAVER,
	MONSTER_DARKSERVANT,
	MONSTER_CRAWLER,
	MONSTER_DRAUGR,
	
	// Hell Knight
	MONSTER_BLOODSATYR,
	MONSTER_HELLWARRIOR,
	MONSTER_HELLSFURY,
	MONSTER_BLACKKNIGHT,
	MONSTER_ARCHON,
	MONSTER_WARLORD,
	MONSTER_SKULLWIZARD,
	MONSTER_CYBORGWARRIOR,
	MONSTER_SHADOWBEAST,
	MONSTER_CHAOSSERPENT,
	MONSTER_MOONSATYR,
	MONSTER_ICEGOLEM,
	MONSTER_GLADIATOR,

	// Baron
	MONSTER_LAVADEMON,
	MONSTER_LORDOFHERESY,
	MONSTER_BORMERETH,
	MONSTER_BARBATOS,
	MONSTER_BLOODSEEKER,
	MONSTER_SHADOWWIZARD,
	MONSTER_KJAROCH,
	MONSTER_CYBRUISER,
	MONSTER_BRUISERDEMON,
	MONSTER_MAGMASERPENT,
	MONSTER_DREADKNIGHT,
	MONSTER_MAGMAGOLEM,
	MONSTER_WARMASTER,
	
	// Fatso
	MONSTER_CORPULENT,
	MONSTER_DAEDABUS,
	MONSTER_PALADIN,
	MONSTER_GAMON,
	MONSTER_MEPHISTO,
	MONSTER_MAFIBUS,
	MONSTER_ICEFATSO,
	MONSTER_ABOMINATION,
	MONSTER_GOLDGOLEM,
	
	// Arachnotron
	MONSTER_FUSIONSPIDER,
	MONSTER_RAILARACHNOTRON,
	MONSTER_HELLFORGESPIDER,
	MONSTER_VORE,
	MONSTER_BABYDEMOLISHER,
	MONSTER_CHAINGUNGENERAL,
	MONSTER_CHAINGUNCOMMANDO,
	MONSTER_LEGIONNAIRE,
	MONSTER_MANTICORE,
	
	// ArchVile
	MONSTER_DIABLOIST,
	MONSTER_UNDEADPRIEST,
	MONSTER_DEATHVILE,
	MONSTER_HIEROPHANT,
	MONSTER_GURU,
	MONSTER_DEATHKNIGHT,
	MONSTER_HORSHACKER,
	MONSTER_DARKZEALOT,
	MONSTER_FLESHWIZARD,
	
	// Spider Mastermind
	MONSTER_DEMOLISHER,
	MONSTER_ARACHNOPHYTE,
	MONSTER_PSIONICQUEEN,
	MONSTER_ANGELOFDEATH,
	MONSTER_GOLDLICH,
	MONSTER_GOLDLICHFAKE,
	MONSTER_IRONLICH,
	MONSTER_SPIDEROVERLORD,
	MONSTER_DARKLICH,
	
	// Cyberdemon
	MONSTER_CARDINAL,
	MONSTER_TERMINATOR,
	MONSTER_THAMUZ,
	MONSTER_AZAZEL,
	MONSTER_HELLSMITH,
	MONSTER_THANATOS,
	MONSTER_AVATAR,
	MONSTER_CERBERUS,
	
	MONSTER_DREAMINGGOD,
	MONSTER_TORRASQUE,
	MONSTER_MORDECQAI,
	MONSTER_GODSLAYER,
	MONSTER_GOLGOTH
};

enum {
	MONSTER_PET_ZOMBIE
};
#define MAX_PET_TYPES MONSTER_PET_ZOMBIE + 1

enum {
	DND_ZOMBIEMANID,
	DND_SHOTGUNNERID,
	DND_CHAINGUNGUYID,
	DND_DEMONID,
	DND_SPECTREID,
	DND_IMPID,
	DND_CACODEMONID,
	DND_PAINELEMENTALID,
	DND_LOSTSOULID,
	DND_REVENANTID,
	DND_HELLKNIGHTID,
	DND_BARONID,
	DND_FATSOID,
	DND_ARCHVILEID,
	DND_ARACHNOTRONID,
	DND_SPIDERMASTERMINDID,
	DND_CYBERDEMONID,
	DND_NAZIID
};

enum {
	DND_MTYPE_DEMON_POW = 1,
	DND_MTYPE_UNDEAD_POW = 2,
	DND_MTYPE_MAGICAL_POW = 4,
	DND_MTYPE_ROBOTIC_POW = 8,
	DND_MTYPE_ZOMBIE_POW = 16
};

enum {
	DND_MTYPE_DEMON,
	DND_MTYPE_UNDEAD,
	DND_MTYPE_MAGICAL,
	DND_MTYPE_ROBOTIC
};

// first 4 above dictate the basic monster types
#define MAX_MONSTER_TYPES 4
str MonsterTypeIdentifiers[MAX_MONSTER_TYPES] = {
	"MType_Demon",
	"MType_Undead",
	"MType_Magical",
	"MType_Robotic"
};

str MonsterTypeIcons[MAX_MONSTER_TYPES] = {
	"DNDEDEM",
	"DNDEUND",
	"DNDEMAG",
	"DNDEROB"
};

int InferMonsterPower(int mid) {
	if(mid & DND_MTYPE_ROBOTIC_POW) {
		// give priority to demon on half demon half robots
		if(mid & DND_MTYPE_DEMON_POW)
			return DND_MTYPE_DEMON;
		return DND_MTYPE_ROBOTIC;
	}
	if(mid & DND_MTYPE_MAGICAL_POW)
		return DND_MTYPE_MAGICAL;
	if(mid & DND_MTYPE_UNDEAD_POW)
		return DND_MTYPE_UNDEAD;
	return DND_MTYPE_DEMON;
}

int GetMonsterType(int monsterID) {
	int mid = MonsterTypeList[monsterID];
	return InferMonsterPower(mid);
}

int GetCustomMonsterType(int properties) {
	// get the first 5 bits only
	return InferMonsterPower(properties & 0x1F);
}

int GetPetMonsterType(int monsterID) {
	int mid = MonsterPetTypeList[monsterID];
	if(mid & DND_MTYPE_ROBOTIC_POW) {
		// give priority to demon on half demon half robots
		if(mid & DND_MTYPE_DEMON_POW)
			return DND_MTYPE_DEMON;
		return DND_MTYPE_ROBOTIC;
	}
	if(mid & DND_MTYPE_MAGICAL_POW)
		return DND_MTYPE_MAGICAL;
	if(mid & DND_MTYPE_UNDEAD_POW)
		return DND_MTYPE_UNDEAD;
	return DND_MTYPE_DEMON;
}

#define DND_BOSS_BEGIN MONSTER_DEMOLISHER
#define LEGENDARY_START MONSTER_DREAMINGGOD
#define DND_LASTMONSTER_INDEX MONSTER_GOLGOTH
#define DND_MAX_LEGENDARY DND_LASTMONSTER_INDEX - LEGENDARY_START + 1
#define MONSTER_COUNT DND_LASTMONSTER_INDEX + 50 // possible compatibility for other wads' monsters

int MonsterTypeList[DND_LASTMONSTER_INDEX + 1] = {
	// Classic
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_UNDEAD_POW,
	DND_MTYPE_UNDEAD_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW | DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW | DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_DEMON_POW | DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_DEMON_POW | DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	
	// DnD Exclusives
	
	// Zombieman
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	
	// Shotgunner
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	
	// Chaingunner
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	
	// Demon
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	
	// Spectre
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	
	// Imp
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_UNDEAD_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	
	// Lost Soul
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_UNDEAD_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_UNDEAD_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_UNDEAD_POW,
	
	// Cacodemon
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_UNDEAD_POW,
	DND_MTYPE_UNDEAD_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_DEMON_POW,
	
	// Pain Elemental
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_UNDEAD_POW,
	
	// Revenant
	DND_MTYPE_UNDEAD_POW,
	DND_MTYPE_UNDEAD_POW,
	DND_MTYPE_UNDEAD_POW,
	DND_MTYPE_UNDEAD_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_UNDEAD_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_UNDEAD_POW,
	
	// Hell Knight
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_UNDEAD_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_DEMON_POW,

	// Baron
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW | DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW | DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_UNDEAD_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_DEMON_POW,
	
	// Fatso
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW | DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_DEMON_POW | DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_DEMON_POW | DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_DEMON_POW | DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_MAGICAL_POW,
	
	// Arachnotron
	DND_MTYPE_DEMON_POW | DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_DEMON_POW | DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW | DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_UNDEAD_POW | DND_MTYPE_ZOMBIE_POW,
	DND_MTYPE_DEMON_POW,
	
	// ArchVile
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_UNDEAD_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_UNDEAD_POW,
	DND_MTYPE_UNDEAD_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_DEMON_POW,
	
	// Spider Mastermind
	DND_MTYPE_DEMON_POW | DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_DEMON_POW | DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_DEMON_POW | DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_MAGICAL_POW,
	
	// Cyberdemon
	DND_MTYPE_DEMON_POW | DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_DEMON_POW | DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_DEMON_POW | DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW | DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_MAGICAL_POW,
	DND_MTYPE_DEMON_POW,
	
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_DEMON_POW,
	DND_MTYPE_ROBOTIC_POW,
	DND_MTYPE_DEMON_POW
};

int MonsterHPList[DND_LASTMONSTER_INDEX + 1] = {
	20, //DND_ZOMBIEMANID,
	60, //DND_SHOTGUNNERID,
	70, //DND_CHAINGUNGUYID,
	150, //DND_DEMONID,
	150, //DND_SPECTREID,
	60, //DND_IMPID,
	400, //DND_CACODEMONID,
	400, //DND_PAINELEMENTALID,
	50, //DND_LOSTSOULID,
	300, //DND_REVENANTID,
	500, //DND_HELLKNIGHTID,
	1000, //DND_BARONID,
	600, //DND_FATSOID,
	700, //DND_ARCHVILEID,
	500, //DND_ARACHNOTRONID,
	3000, //DND_SPIDERMASTERMINDID,
	4000, //DND_CYBERDEMONID,
	50, //DND_NAZIID,	
	
	40, //DND_ZOMBIEGRAY,
	45, //DND_ZOMBIERANGER,
	35, //DND_ZOMBIESMG,
	30, //DND_ZOMBIERAPID,
	45, //DND_ZOMBIEMARINE,
    45, //DND_ZOMBIELOS,
    25, //DND_ZOMBIEPISTOL,
    55, //DND_ZOMBIEQUAKE1,
    65, //DND_ZOMBIEHUNTER,
    50, //DND_PROPHET,

	// Shotgunner
    50, //DND_SSGLOS,
    50, //DND_ZSPECSG,
    50, //DND_SGLOS,
    50, //DND_SAWEDOFF1,
    50, //DND_SAWEDOFF2,
    65, //DND_ROGUE,
    70, //DND_ZOMBIEQUAKE2,
    75, //DND_ZOMBIESSG,

	// Chaingunner
    85, //DND_ZOMBIEQUAKE3,
    85, //DND_ZOMBIEMG,
    65, //DND_INITIATE,
    100, //DND_DOUBLEGUNNER,
    110, //DND_CGMAJOR,
    100, //DND_MRROBOT,
    70, //DND_ZSEC,
    60, //DND_ZSPECMG,
	85, //DND_PLASMAZOMBIE,
	150, //DND_BERSERKERGUY,

	// Demon
    250, //DND_BLOODDEMON,
    160, //DND_BLOODFIEND,
    300, //DND_CYBERFIEND,
    200, //DND_FLAMEDEMON,
    180, //DND_STONEIMP,
    195, //DND_SCAVENGER,
    200, //DND_SOULEATER,
    275, //DND_NHUMCIGN,
    250, //DND_STONEDEMON,
    240, //DND_BRUTY,
	150, //DND_SATYR,
	325, //DND_EARTHGOLEM,
	250, //DND_RAVAGER,
	275, //DND_PUREBREDDEMON,

	// Spectre
    160, //DND_LURKER,
    160, //Unknown - DND_GRAVEDIGGER,
    175, //DND_DEVOURER,
    150, //DND_NIGHTMAREDEMON,

	// Imp
    80, //DND_DARKIMP1,
    100, //DND_VOIDDARKIMP,
    100, //DND_NETHERDARKIMP,
    90, //DND_DARKIMP2,
    80, //DND_IMPABOM,
    55, //DND_STIMP,
    65, //DND_VOIDIMP,
    100, //DND_SOULHARVESTER,
    60, //DND_PYROIMP,
    85, //DND_DEVIL,
	125, //DND_DEVIL2,
    70, //DND_VULGAR,
    80, //DND_UNDEADMAGE,
	85, //DND_SHADOW,
	80, //DND_ROACH,

	// Lost Soul
    60, //DND_BABYCACO,
    60, //DND_ETHEREALSOUL,
    50, //DND_FLESHSPAWN,
    75, //DND_GUARDIANCUBE,
    40, //DND_FORGOTTENONE,
	35, //DND_HADESSPHERE,
	100, //DND_WATCHER,
	75, //DND_DARKLICH_SPIRIT,

	// Cacodemon
    300, //DND_WEAKENER,
    250, //DND_SHADOWPRIEST,
    325, //DND_GRELL,
    500, //DND_DEATHWHISPERER,
    500, //DND_CACOLICH,
    400, //DND_INFERNO,
    275, //DND_GUARDIAN,
    300, //DND_ENHANCEDCACO,
    425, //DND_EARTHLICH,
	300, //DND_WICKED,
	
	// Pain E.
	675, //DND_BLOODLICH,
	800, //DND_HADESELEMENTAL,
	700, //Unknown - DND_HELLARBITER,
	500, //DND_DEFILER,
	550, //DND_TORTUREDSOUL,
	500, //DND_SHADOWDISCIPLE,
	750, //DND_SENTINEL,
	75, //DND_WRAITH,
	
	// Revenant
	250, //DND_INCARNATE,
	250, //Unknown - DND_BEAMREVENANT,
	250, //DND_AXEKNIGHT,
	300, //DND_WIDOWMAKER,
	350, //DND_YETI,
	280, //DND_SLUDGEGIANT,
	140, //DND_SLUDGEGIANT2,
	70, //DND_SLUDGEGIANT3,
	350, //DND_CADAVER,
	275, //DND_DARKSERVANT,
	325, //DND_CRAWLER,
	350, //DND_DRAUGR,
	
	// Hell Knight
	550, //DND_BLOODSATYR,
	400, //DND_HELLWARRIOR,
	600, //DND_HELLSFURY,
	550, //DND_BLACKKNIGHT,
	700, //DND_ARCHON,
	650, //DND_WARLORD,
	500, //DND_SKULLWIZARD,
	650, //DND_CYBORGWARRIOR,
	400, //DND_SHADOWBEAST,
	450, //DND_CHAOSSERPENT,
	750, //DND_MOONSATYR,
	400, //DND_ICEGOLEM,
	450, //DND_GLADIATOR,

	// Baron
	1000, //DND_LAVADEMON,
	1100, //DND_LORDOFHERESY,
	1200, //DND_BORMERETH,
	1100, //Unknown - DND_BARBATOS,
	1000, //DND_BLOODSEEKER,
	900, //DND_SHADOWWIZARD,
	1650, //DND_KJAROCH,
	1500, //DND_CYBRUISER,
	1500, //DND_BRUISERDEMON,
	900, //DND_MAGMASERPENT,
	900, //DND_DREADKNIGHT,
	900, //DND_MAGMAGOLEM,
	1250, //DND_WARMASTER,
	
	// Fatso
	850, //DND_CORPULENT,
	850, //DND_DAEDABUS,
	775, //DND_PALADIN,
	875, //DND_GAMON,
	900, //DND_MEPHISTO,
	1100, //DND_MAFIBUS,
	650, //DND_ICEFATSO,
	775, //DND_ABOMINATION,
	1000, //DND_GOLDGOLEM,
	
	// Arachnotron
	500, //DND_FUSIONSPIDER,
	450, //DND_RAILARACHNOTRON,
	700, //DND_HELLFORGESPIDER,
	700, //DND_VORE,
	700, //DND_BABYDEMOLISHER,
	550, //DND_CHAINGUNGENERAL,
	550, //DND_CHAINGUNCOMMANDO,
	600, //DND_LEGIONNAIRE,
	650, //DND_MANTICORE,
	
	// ArchVile
	850, //DND_DIABLOIST,
	800, //DND_UNDEADPRIEST,
	800, //DND_DEATHVILE,
	1250, //DND_HIEROPHANT,
	800, //DND_GURU,
	900, //DND_DEATHKNIGHT,
	900, //DND_HORSHACKER,
	750, //DND_DARKZEALOT,
	625, //DND_FLESHWIZARD,
	
	// Spider Mastermind
	4000, //DND_DEMOLISHER,
	3500, //DND_ARACHNOPHYTE,
	4000, //DND_PSIONICQUEEN,
	4000, //DND_ANGELOFDEATH,
	4750, //DND_GOLDLICH,
	300, //DND_GOLDLICHFAKE,
	4000, //DND_IRONLICH,
	4000, //DND_SPIDEROVERLORD,
	4000, //DND_DARKLICH,
	
	// Cyberdemon
	4500, //DND_CARDINAL,
	5750, //DND_TERMINATOR,
	4750, //DND_THAMUZ,
	5250, //DND_AZAZEL,
	6000, //DND_HELLSMITH,
	6500, //DND_THANATOS,
	5500, //DND_AVATAR,
	6000, //DND_CERBERUS,
	
	// Legendaries
	20000, //DND_DREAMER,
	16500, //DND_TORRASQUE,
	18500, //DND_MORDECQAI,
	13500, //DND_GODSLAYER,
	17500 //DND_GOLGOTH
};

int MonsterPetTypeList[MAX_PET_TYPES] = {
	DND_MTYPE_UNDEAD_POW
};

bool IsBoss() {
	int id = MonsterProperties[ActivatorTID() - DND_MONSTERTID_BEGIN].id;
	return id == MONSTER_MASTERMIND || id == MONSTER_CYBERDEMON || id >= DND_BOSS_BEGIN;
}

bool IsDemon() {
	return MonsterTypeList[MonsterProperties[ActivatorTID() - DND_MONSTERTID_BEGIN].id] & DND_MTYPE_DEMON_POW;
}

bool IsZombie() {
	return MonsterTypeList[MonsterProperties[ActivatorTID() - DND_MONSTERTID_BEGIN].id] & DND_MTYPE_ZOMBIE_POW;
}

bool IsUndead() {
	return MonsterTypeList[MonsterProperties[ActivatorTID() - DND_MONSTERTID_BEGIN].id] & DND_MTYPE_UNDEAD_POW;
}

bool IsRobotic() {
	return MonsterTypeList[MonsterProperties[ActivatorTID() - DND_MONSTERTID_BEGIN].id] & DND_MTYPE_ROBOTIC_POW;
}

bool IsLostSoul() {
	int id = MonsterProperties[ActivatorTID() - DND_MONSTERTID_BEGIN].id;
	return (id >= MONSTER_BABYCACO && id <= MONSTER_DARKLICH_SPIRIT) || id == MONSTER_LOSTSOUL;
}

bool isPet(int tid) {
	return tid >= DND_PETTID_BEGIN && tid < DND_MONSTERTID_BEGIN;
}

// First element on each list is the "Vanilla" monster, rest follow from their variations with Var1 to VarX
#define MAX_MONSTER_CATEGORIES 17
#define MAX_MONSTER_VARIATIONS 16
int Monster_Weights[MAX_MONSTER_CATEGORIES][MAX_MONSTER_VARIATIONS] = {
    // Zombieman
    { 16, 16, 8, 12, 8, 8, 8, 8, 16, 12, 8, -1 },
    // Shotgunguy
    { 16, 4, 8, 6, 4, 4, 6, 6, 4, -1 },
    // Chaingunguy
    { 8, 8, 8, 6, 4, 4, 4, 3, 4, 6, 3, -1 },
    // Demon
    { 16, 16, 12, 8, 12, 16, 8, 10, 7, 8, 10, 10, 6, 6, 4, -1 },
    // Spectre
    { 1, 1, 1, 1, 1, 1, 1, 1, 1, -1 },
    // Imp
    { 16, 8, 8, 8, 8, 8, 16, 16, 16, 12, 12, 8, 8, 8, 10, 10 },
    // Caco
    { 16, 16, 16, 12, 12, 10, 16, 16, 16, 12, 9, -1 },
    // Pain Elemental
    { 16, 12, 10, 10, 16, 16, 12, 12, -1 },
    // Lost Soul
    { 8, 8, 6, 8, 8, 8, 6, -1 },
    // Revenant
    { 16, 16, 12, 12, 8, 9, 0, 0, 9, 8, 9, 10, 9, -1 },
    // HellKnight
    { 12, 16, 14, 12, 10, 10, 10, 10, 8, 12, 12, 10, 6, 6, -1 },
    // Baron
    { 16, 16, 16, 12, 12, 10, 10, 8, 8, 8, 10, 6, 6, 4, -1 },
    // Fatso
    { 16, 12, 12, 10, 10, 8, 10, 12, 16, 5, -1 },
    // ArchVile
    { 16, 8, 8, 12, 8, 8, 6, 6, 6, 5, -1 },
    // Arachno
    { 16, 16, 16, 12, 10, 8, 10, 10, 8, 6, -1 },
    // Spider Mastermind
    { 16, 10, 10, 12, 8, 0, 8, 8, 10, 6, -1 },
    // Cyberdemon
    { 16, 12, 12, 12, 10, 10, 8, 8, 5, -1 }
};

str LegendaryMonsters[DND_MAX_LEGENDARY] = {
	"DreamingGod",
	"Torrasque",
	"Mordecqai",
	"GodSlayer",
	"Golgoth"
};

#endif