#ifndef DND_ORBDEF_IN
#define DND_ORBDEF_IN

#define DND_MAX_ORB_REROLL_ATTEMPTS 100

enum {
	DND_ORB_ENHANCE,
	DND_ORB_CORRUPT,
	DND_ORB_PRISMATIC,
	DND_ORB_REPENT,
	DND_ORB_AFFLUENCE,

	DND_ORB_CALAMITY,
	DND_ORB_PROSPERITY,
	DND_ORB_NULLIFICATION,
	DND_ORB_DESTRUCTION,
	DND_ORB_VIOLENCE,

	DND_ORB_FORTITUDE,
	DND_ORB_SIN,
	DND_ORB_TREMORS,
	DND_ORB_TINKERER,
	DND_ORB_REFINEMENT,

	DND_ORB_SCULPTING,
	DND_ORB_ELEVATION,
	DND_ORB_TURMOIL,
	DND_ORB_HEXES,
	DND_ORB_GROWTH,

	DND_ORB_POTENCY,
	DND_ORB_CRACKLING,
	DND_ORB_BRUTE,
	DND_ORB_JAGGED,
	DND_ORB_ALCHEMIST,
	
	DND_ORB_EVOKER,
	DND_ORB_SAVAGERY,

	// unique drops from specific monsters
	DND_ORB_HOLLOW,
	DND_ORB_PHANTASMAL,
	DND_ORB_ASSIMILATION
};

#endif
