#ifndef DND_MONSTERDATA_IN
#define DND_MONSTERDATA_IN

enum {
	// Classics
	MONSTER_ZOMBIEMAN,
	MONSTER_SHOTGUNNER,
	MONSTER_CHAINGUNNER,
	MONSTER_DEMON,
	MONSTER_SPECTRE,
	MONSTER_IMP,
	MONSTER_CACODEMON,
	MONSTER_PAINELEMENTAL,
	MONSTER_LOSTSOUL,
	MONSTER_REVENANT,
	MONSTER_HELLKNIGHT,
	MONSTER_BARON,
	MONSTER_FATSO,
	MONSTER_VILE,
	MONSTER_SPIDER,
	MONSTER_MASTERMIND,
	MONSTER_CYBERDEMON,
	MONSTER_NAZI,
	
	// DnD Exclusives
	
	// Zombieman
	MONSTER_ZOMBIEMANGRAY,
	MONSTER_ZOMBIERANGER,
	MONSTER_ZOMBIESMG,
	MONSTER_ZOMBIERAPID,
	MONSTER_ZOMBIEMARINE,
	MONSTER_ZOMBIELOS,
	MONSTER_ZOMBIEPISTOL,
	MONSTER_ZOMBIEQUAKE1,
	MONSTER_ZOMBIEHUNTER,
	MONSTER_ZOMBIEPROPHET,
	
	// Shotgunner
	MONSTER_SSGLOS,
	MONSTER_ZSPECSG,
	MONSTER_SGLOS,
	MONSTER_SAWEDOFF1,
	MONSTER_SAWEDOFF2,
	MONSTER_ROGUE,
	MONSTER_ZOMBIEQUAKE2,
	MONSTER_ZOMBIESSG,
	
	// Chaingunner
	MONSTER_ZOMBIEQUAKE3,
	MONSTER_ZOMBIEMG,
	MONSTER_INITIATE,
	MONSTER_DOUBLEGUNNER,
	MONSTER_CGMAJOR,
	MONSTER_MRROBOT,
	MONSTER_ZSEC,
	MONSTER_ZSPECMG,
	MONSTER_PLASMAZOMBIE,
	
	// Demon
	MONSTER_BLOODDEMON,
	MONSTER_BLOODFIEND,
	MONSTER_CYBERFIEND,
	MONSTER_FLAMEDEMON,
	MONSTER_STONEIMP,
	MONSTER_SCAVENGER,
	MONSTER_SOULEATER,
	MONSTER_NHUMCIGN,
	MONSTER_STONEDEMON,
	MONSTER_BRUTY,
	MONSTER_SATYR,
	MONSTER_EARTHGOLEM,
	
	// Spectre
	MONSTER_LURKER,
	MONSTER_GRAVEDIGGER,
	MONSTER_DEVOURER,
	MONSTER_NIGHTMAREDEMON,
	
	// Imp
	MONSTER_DARKIMP1,
	MONSTER_VOIDDARKIMP,
	MONSTER_NETHERDARKIMP,
	MONSTER_DARKIMP2,
	MONSTER_IMPABOM,
	MONSTER_STIMP,
	MONSTER_VOIDIMP,
	MONSTER_SOULHARVESTER,
	MONSTER_PYROIMP,
	MONSTER_DEVIL,
	MONSTER_VULGAR,
	MONSTER_UNDEADMAGE,
	MONSTER_SHADOW,
	MONSTER_ROACH,
	
	// Lost Soul
	MONSTER_BABYCACO,
	MONSTER_ETHEREALSOUL,
	MONSTER_FLESHSPAWN,
	MONSTER_GUARDIANCUBE,
	MONSTER_FORGOTTENONE,
	MONSTER_HADESSPHERE,
	MONSTER_WATCHER,
	MONSTER_DARKLICH_SPIRIT,
	
	// Cacodemon
	MONSTER_WEAKENER,
	MONSTER_SHADOWPRIEST,
	MONSTER_GRELL,
	MONSTER_DEATHWHISPERER,
	MONSTER_CACOLICH,
	MONSTER_INFERNO,
	MONSTER_GUARDIAN,
	MONSTER_ENHANCEDCACO,
	MONSTER_EARTHLICH,
	MONSTER_WICKED,
	
	// Pain Elemental
	MONSTER_BLOODLICH,
	MONSTER_HADESELEMENTAL,
	MONSTER_HELLARBITER,
	MONSTER_DEFILER,
	MONSTER_TORTUREDSOUL,
	MONSTER_SHADOWDISCIPLE,
	MONSTER_SENTINEL,
	MONSTER_WRAITH,
	
	// Revenant
	MONSTER_INCARNATE,
	MONSTER_BEAMREVENANT,
	MONSTER_AXEKNIGHT,
	MONSTER_WIDOWMAKER,
	MONSTER_YETI,
	MONSTER_SLUDGEGIANT,
	MONSTER_CADAVER,
	MONSTER_DARKSERVANT,
	MONSTER_CRAWLER,
	MONSTER_DRAUGR,
	
	// Hell Knight
	MONSTER_BLOODSATYR,
	MONSTER_HELLWARRIOR,
	MONSTER_HELLSFURY,
	MONSTER_BLACKKNIGHT,
	MONSTER_ARCHON,
	MONSTER_WARLORD,
	MONSTER_SKULLWIZARD,
	MONSTER_CYBORGWARRIOR,
	MONSTER_SHADOWBEAST,
	MONSTER_CHAOSSERPENT,
	MONSTER_MOONSATYR,
	DND_ICEGOLEM,

	// Baron
	MONSTER_LAVADEMON,
	MONSTER_LORDOFHERESY,
	MONSTER_BORMERETH,
	MONSTER_BARBATOS,
	MONSTER_BLOODSEEKER,
	MONSTER_SHADOWWIZARD,
	MONSTER_KJAROCH,
	MONSTER_CYBRUISER,
	MONSTER_BRUISERDEMON,
	MONSTER_MAGMASERPENT,
	MONSTER_DREADKNIGHT,
	MONSTER_MAGMAGOLEM,
	
	// Fatso
	MONSTER_CORPULENT,
	MONSTER_DAEDABUS,
	MONSTER_PALADIN,
	MONSTER_GAMON,
	MONSTER_MEPHISTO,
	MONSTER_MAFIBUS,
	MONSTER_ICEFATSO,
	MONSTER_ABOMINATION,
	MONSTER_GOLDGOLEM,
	
	// Arachnotron
	MONSTER_FUSIONSPIDER,
	MONSTER_RAILARACHNOTRON,
	MONSTER_HELLFORGESPIDER,
	MONSTER_VORE,
	MONSTER_BABYDEMOLISHER,
	MONSTER_CHAINGUNGENERAL,
	MONSTER_CHAINGUNCOMMANDO,
	MONSTER_LEGIONNAIRE,
	
	// ArchVile
	MONSTER_DIABLOIST,
	MONSTER_UNDEADPRIEST,
	MONSTER_DEATHVILE,
	MONSTER_HIEROPHANT,
	MONSTER_GURU,
	MONSTER_DEATHKNIGHT,
	MONSTER_HORSHACKER,
	MONSTER_DARKZEALOT,
	MONSTER_FLESHWIZARD,
	
	// Spider Mastermind
	MONSTER_DEMOLISHER,
	MONSTER_ARACHNOPHYTE,
	MONSTER_PSIONICQUEEN,
	MONSTER_ANGELOFDEATH,
	MONSTER_GOLDLICH,
	MONSTER_IRONLICH,
	MONSTER_SPIDEROVERLORD,
	MONSTER_DARKLICH,
	
	// Cyberdemon
	MONSTER_CARDINAL,
	MONSTER_TERMINATOR,
	MONSTER_THAMUZ,
	MONSTER_AZAZEL,
	MONSTER_HELLSMITH,
	MONSTER_THANATOS,
	MONSTER_AVATAR,
	MONSTER_CERBERUS,
	
	MONSTER_DREAMINGGOD,
	MONSTER_TORRASQUE,
	MONSTER_MORDECQAI,
	MONSTER_GODSLAYER
};

enum {
	DND_ZOMBIEMANID,
	DND_SHOTGUNNERID,
	DND_CHAINGUNGUYID,
	DND_DEMONID,
	DND_SPECTREID,
	DND_IMPID,
	DND_CACODEMONID,
	DND_PAINELEMENTALID,
	DND_LOSTSOULID,
	DND_REVENANTID,
	DND_HELLKNIGHTID,
	DND_BARONID,
	DND_FATSOID,
	DND_ARCHVILEID,
	DND_ARACHNOTRONID,
	DND_SPIDERMASTERMINDID,
	DND_CYBERDEMONID,
	DND_NAZIID
};

#define DND_BOSS_BEGIN MONSTER_DEMOLISHER
#define LEGENDARY_START MONSTER_DREAMINGGOD
#define DND_LASTMONSTER_INDEX MONSTER_GODSLAYER
#define DND_MAX_LEGENDARY DND_LASTMONSTER_INDEX - LEGENDARY_START + 1
#define MONSTER_COUNT DND_LASTMONSTER_INDEX + 50 // possible compatibility for other wads' monsters

int IsBoss(int monsterid) {
	if(monsterid == MONSTER_CYBERDEMON || monsterid == MONSTER_MASTERMIND || monsterid >= MONSTER_DEMOLISHER)
		return 1;
	return 0;
}

#define MAX_MONSTER_TRAITS 31
#define MONSTER_TRAITID 1103
#define MONSTER_BARID MONSTER_TRAITID + MAX_MONSTER_TRAITS + 1
// up to 1102 is occupied by barfillid, 1102 included
#define MONSTER_BARFILLID 1001
#define MONSTER_TEXTID 1000
#define MONSTER_NAMEID 999

str MonsterTraits[MAX_MONSTER_TRAITS] = {
	"Energy Weakness",
	"Silver Weakness",
	"Fire Weakness",
	"Ice Weakness",
	"Magic Weakness",
	
	"Explosive Resist",
	"High Explosive Resist",
	"Explosive Immune",
	"Physical Resist",
	"Ghost",
	"Hardened Skin",	// ripper immune
	"Reflective",
	"Summon Minion",
	"Can Curse",		// monsters with curses
	"Can Heal",		// monsters with healing
	"Can Block",		// shielded monster
	"Can Split",
	"Can Raise",
	"Can Teleport",
	"Resurrect Fallen",	// arch vile
	"Mobility",	// dashes, fast speed etc
	"Homing",
	"Poisonous",
	"Death Surprise",	// monsters with dangerous deaths
	"Rage", // monsters that get angry after a certain condition
	"Pierces Armor", // monsters that ignore player armor
	"Aggressive", // more aggression
	"Extra Fast", // nightmare fast
	"Fast Reaction", // quicktoretaliate
	"No Pain",
	"Magic Resist"
};

#define MAX_MONSTER_TRAITS2 10
str MonsterTraits2[MAX_MONSTER_TRAITS2] = {
	"Physical Immune",
	"Energy Resist",
	"Energy Immune",
	"Magic Resist",
	"Magic Immune",
	"Elemental Resist",
	"Elemental Immune",
	"Extra Strong",
	"Vital",
	"Armor Penetration"
};

// First element on each list is the "Vanilla" monster, rest follow from their variations with Var1 to VarX
#define MAX_MONSTER_CATEGORIES 17
#define MAX_MONSTER_VARIATIONS 15
int Monster_Weights[MAX_MONSTER_CATEGORIES][MAX_MONSTER_VARIATIONS] = {
    // Zombieman
    { 16, 16, 8, 12, 8, 8, 8, 8, 16, 12, 8, -1 },
    // Shotgunguy
    { 16, 4, 8, 6, 4, 4, 6, 6, 4, -1 },
    // Chaingunguy
    { 8, 8, 8, 6, 4, 4, 4, 3, 4, 6, -1 },
    // Demon
    { 16, 16, 12, 8, 12, 16, 8, 10, 7, 8, 10, 10, 6, -1 },
    // Spectre
    { 1, 1, 1, 1, 1, 1, 1, 1, -1 },
    // Imp
    { 16, 8, 8, 8, 8, 8, 16, 16, 16, 12, 12, 8, 8, 8, 10 },
    // Caco
    { 16, 16, 16, 12, 12, 10, 16, 16, 16, 12, 9, -1 },
    // Pain Elemental
    { 16, 12, 10, 10, 16, 16, 12, 12, -1 },
    // Lost Soul
    { 8, 8, 6, 8, 8, 8, 6, -1 },
    // Revenant
    { 16, 16, 12, 12, 8, 9, 9, 8, 9, 10, 9, -1 },
    // HellKnight
    { 12, 16, 14, 12, 10, 10, 10, 10, 8, 12, 12, 10, 6, -1	},
    // Baron
    { 16, 16, 16, 12, 12, 10, 10, 8, 8, 8, 10, 6, 6, -1 },
    // Fatso
    { 16, 12, 12, 10, 10, 8, 10, 12, 16, 5, -1 },
    // ArchVile
    { 16, 8, 8, 12, 8, 8, 6, 6, 6, 5, -1 },
    // Arachno
    { 16, 16, 16, 12, 10, 8, 10, 10, 8, -1 },
    // Spider Mastermind
    { 16, 10, 10, 12, 8, 8, 8, 10, 6, -1 },
    // Cyberdemon
    { 16, 12, 12, 12, 10, 10, 8, 8, 5, -1 }
};

str LegendaryMonsters[DND_MAX_LEGENDARY] = {
	"DreamingGod",
	"Torrasque",
	"Mordecqai",
	"GodSlayer"
};

#endif