#ifndef DND_INV_WEIGHTS_IN
#define DND_INV_WEIGHTS_IN

enum {
	DND_DROPPEDITEM_BODY,
	DND_DROPPEDITEM_BOOT,
	DND_DROPPEDITEM_HELM,

	DND_DROPPEDITEM_FLASK,

	DND_DROPPEDITEM_LAST
};

#define MAX_SUB_ITEMTYPES 64 // increase if needed
global int 50: ItemDropWeights[DND_DROPPEDITEM_LAST][MAX_SUB_ITEMTYPES];

#define SET_ITEM_WEIGHT(X, Y, W) 	ItemDropWeights[X][Y] = weight + W; \
									weight += W

#define MAX_BODYARMOR_WEIGHT ItemDropWeights[DND_DROPPEDITEM_BODY][BODYARMORS_REGULAREND]
#define MAX_BOOT_WEIGHT ItemDropWeights[DND_DROPPEDITEM_BOOT][BOOTS_END]
#define MAX_HELM_WEIGHT ItemDropWeights[DND_DROPPEDITEM_HELM][HELMS_END]
#define MAX_FLASK_WEIGHT ItemDropWeights[DND_DROPPEDITEM_FLASK][HELMS_END]

#endif