#ifndef DND_ITEMBASE_IN
#define DND_ITEMBASE_IN

// Mod generation profiles describing eligibility of mods to appear naturally on items for drops
enum {
    DND_ITEMBASE_CHARM,

    DND_ITEMBASE_BODY_ARMOR,
    DND_ITEMBASE_BODY_ESHIELD,
    DND_ITEMBASE_BODY_MITIGATION,

    DND_ITEMBASE_BODY_ARMOR_ESHIELD,
    DND_ITEMBASE_BODY_ARMOR_MITIGATION,
    DND_ITEMBASE_BODY_ESHIELD_MITIGATION,

    DND_ITEMBASE_BODY_ARMOR_ESHIELD_MITIGATION,

    DND_ITEMBASE_HELM_ARMOR,
    DND_ITEMBASE_HELM_ESHIELD,
    DND_ITEMBASE_HELM_MITIGATION,

    DND_ITEMBASE_HELM_ARMOR_ESHIELD,
    DND_ITEMBASE_HELM_ARMOR_MITIGATION,
    DND_ITEMBASE_HELM_ESHIELD_MITIGATION,

    DND_ITEMBASE_BOOT_ARMOR,
    DND_ITEMBASE_BOOT_ESHIELD,
    DND_ITEMBASE_BOOT_MITIGATION,

    DND_ITEMBASE_BOOT_ARMOR_ESHIELD,
    DND_ITEMBASE_BOOT_ARMOR_MITIGATION,
    DND_ITEMBASE_BOOT_ESHIELD_MITIGATION,

    DND_ITEMBASE_SPECIALTY_DOOMGUY,
	DND_ITEMBASE_SPECIALTY_MARINE,
	DND_ITEMBASE_SPECIALTY_HOBO,

	DND_ITEMBASE_SPECIALTY_PUNISHER_ARMOR,
    DND_ITEMBASE_SPECIALTY_PUNISHER_ESHIELD,
    DND_ITEMBASE_SPECIALTY_PUNISHER_MITIGATION,

	DND_ITEMBASE_SPECIALTY_WANDERER,
	DND_ITEMBASE_SPECIALTY_CYBORG,

	DND_ITEMBASE_SPECIALTY_BERSERKER_ARMOR,
    DND_ITEMBASE_SPECIALTY_BERSERKER_MITIGATION,
    DND_ITEMBASE_SPECIALTY_BERSERKER_ARMOR_MITIGATION,

	DND_ITEMBASE_SPECIALTY_TRICKSTER_ARMOR,
    DND_ITEMBASE_SPECIALTY_TRICKSTER_MITIGATION,

    DND_ITEMBASE_FLASK_LIFE,
    DND_ITEMBASE_FLASK_UTILITY,

    DND_MAX_ITEMBASES
};

// One row describes a base completely: which slot it occupies, which tags it admits, and which of
// those its particular defensive flavour takes back out. Kept together so a new base cannot be
// half-defined -- a parallel slot table would have nothing forcing the two to stay aligned.
typedef struct {
    int slot_flag;                                  // DND_MODBASE_XXX
    int allowed_tags;
    int excluded_tags;
} itembase_tags_T;
#define SIZEOF_ITEMBASE_TAGS (SIZEOF_INT * 3)

// tagsets from item bases defined above -- these are used for mod pools
itembase_tags_T module& GetItemBaseTags(int item_base) {
    static itembase_tags_T tags[DND_MAX_ITEMBASES] = {
        // DND_ITEMBASE_CHARM
        { DND_MODBASE_CHARM, INV_ATTR_TAG_ALL, 0 },

        // DND_ITEMBASE_BODY_ARMOR,
        { DND_MODBASE_BODYARMOR, INV_ATTR_TAG_OK_BODYARMOR, INV_ATTR_TAG_EXCLUDED_BODYARMOR | INV_ATTR_TAG_ESHIELD | INV_ATTR_TAG_MITIGATION },

        // DND_ITEMBASE_BODY_ESHIELD,
        { DND_MODBASE_BODYARMOR, INV_ATTR_TAG_OK_BODYARMOR, INV_ATTR_TAG_EXCLUDED_BODYARMOR | INV_ATTR_TAG_ARMOR | INV_ATTR_TAG_MITIGATION },

        // DND_ITEMBASE_BODY_MITIGATION,
        { DND_MODBASE_BODYARMOR, INV_ATTR_TAG_OK_BODYARMOR, INV_ATTR_TAG_EXCLUDED_BODYARMOR | INV_ATTR_TAG_ARMOR | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_BODY_ARMOR_ESHIELD,
        { DND_MODBASE_BODYARMOR, INV_ATTR_TAG_OK_BODYARMOR, INV_ATTR_TAG_EXCLUDED_BODYARMOR | INV_ATTR_TAG_MITIGATION },

        // DND_ITEMBASE_BODY_ARMOR_MITIGATION,
        { DND_MODBASE_BODYARMOR, INV_ATTR_TAG_OK_BODYARMOR, INV_ATTR_TAG_EXCLUDED_BODYARMOR | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_BODY_ESHIELD_MITIGATION,
        { DND_MODBASE_BODYARMOR, INV_ATTR_TAG_OK_BODYARMOR, INV_ATTR_TAG_EXCLUDED_BODYARMOR | INV_ATTR_TAG_ARMOR },

        // DND_ITEMBASE_BODY_ARMOR_ESHIELD_MITIGATION
        { DND_MODBASE_BODYARMOR, INV_ATTR_TAG_OK_BODYARMOR, INV_ATTR_TAG_EXCLUDED_BODYARMOR },

        // DND_ITEMBASE_HELM_ARMOR,
        { DND_MODBASE_HELM, INV_ATTR_TAG_OK_HELM, INV_ATTR_TAG_EXCLUDED_HELM | INV_ATTR_TAG_MITIGATION | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_HELM_ESHIELD,
        { DND_MODBASE_HELM, INV_ATTR_TAG_OK_HELM, INV_ATTR_TAG_EXCLUDED_HELM | INV_ATTR_TAG_MITIGATION | INV_ATTR_TAG_ARMOR },

        // DND_ITEMBASE_HELM_MITIGATION,
        { DND_MODBASE_HELM, INV_ATTR_TAG_OK_HELM, INV_ATTR_TAG_EXCLUDED_HELM | INV_ATTR_TAG_ARMOR | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_HELM_ARMOR_ESHIELD,
        { DND_MODBASE_HELM, INV_ATTR_TAG_OK_HELM, INV_ATTR_TAG_EXCLUDED_HELM | INV_ATTR_TAG_MITIGATION },

        // DND_ITEMBASE_HELM_ARMOR_MITIGATION,
        { DND_MODBASE_HELM, INV_ATTR_TAG_OK_HELM, INV_ATTR_TAG_EXCLUDED_HELM | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_HELM_ESHIELD_MITIGATION,
        { DND_MODBASE_HELM, INV_ATTR_TAG_OK_HELM, INV_ATTR_TAG_EXCLUDED_HELM | INV_ATTR_TAG_ARMOR },

        // DND_ITEMBASE_BOOT_ARMOR,
        { DND_MODBASE_BOOT, INV_ATTR_TAG_OK_BOOT, INV_ATTR_TAG_EXCLUDED_BOOT | INV_ATTR_TAG_MITIGATION | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_BOOT_ESHIELD,
        { DND_MODBASE_BOOT, INV_ATTR_TAG_OK_BOOT, INV_ATTR_TAG_EXCLUDED_BOOT | INV_ATTR_TAG_MITIGATION | INV_ATTR_TAG_ARMOR },

        // DND_ITEMBASE_BOOT_MITIGATION,
        { DND_MODBASE_BOOT, INV_ATTR_TAG_OK_BOOT, INV_ATTR_TAG_EXCLUDED_BOOT | INV_ATTR_TAG_ARMOR | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_BOOT_ARMOR_ESHIELD,
        { DND_MODBASE_BOOT, INV_ATTR_TAG_OK_BOOT, INV_ATTR_TAG_EXCLUDED_BOOT | INV_ATTR_TAG_MITIGATION },

        // DND_ITEMBASE_BOOT_ARMOR_MITIGATION,
        { DND_MODBASE_BOOT, INV_ATTR_TAG_OK_BOOT, INV_ATTR_TAG_EXCLUDED_BOOT | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_BOOT_ESHIELD_MITIGATION,
        { DND_MODBASE_BOOT, INV_ATTR_TAG_OK_BOOT, INV_ATTR_TAG_EXCLUDED_BOOT | INV_ATTR_TAG_ARMOR },

        // DND_ITEMBASE_SPECIALTY_DOOMGUY,
        { DND_MODBASE_SPECIALTY_DOOMGUY, INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_FLASK },

        // DND_ITEMBASE_SPECIALTY_MARINE,
        { DND_MODBASE_SPECIALTY_MARINE, INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_STAMINA | INV_ATTR_TAG_FLASK },

        // DND_ITEMBASE_SPECIALTY_HOBO,
        { DND_MODBASE_SPECIALTY_HOBO, INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_STAMINA | INV_ATTR_TAG_FLASK },

        // DND_ITEMBASE_SPECIALTY_PUNISHER_ARMOR,
        { DND_MODBASE_SPECIALTY_PUNISHER, INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_STAMINA | INV_ATTR_TAG_FLASK | INV_ATTR_TAG_MITIGATION | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_SPECIALTY_PUNISHER_ESHIELD,
        { DND_MODBASE_SPECIALTY_PUNISHER, INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_STAMINA | INV_ATTR_TAG_FLASK | INV_ATTR_TAG_MITIGATION | INV_ATTR_TAG_ARMOR },

        // DND_ITEMBASE_SPECIALTY_PUNISHER_MITIGATION,
        { DND_MODBASE_SPECIALTY_PUNISHER, INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_STAMINA | INV_ATTR_TAG_FLASK | INV_ATTR_TAG_ARMOR | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_SPECIALTY_WANDERER,
        { DND_MODBASE_SPECIALTY_WANDERER, INV_ATTR_TAG_ALL, INV_ATTR_TAG_STAMINA | INV_ATTR_TAG_FLASK },

        // DND_ITEMBASE_SPECIALTY_CYBORG,
        { DND_MODBASE_SPECIALTY_CYBORG, INV_ATTR_TAG_ALL, INV_ATTR_TAG_STAMINA | INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_FLASK },

        // DND_ITEMBASE_SPECIALTY_BERSERKER_ARMOR,
        { DND_MODBASE_SPECIALTY_BERSERKER, INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_ENERGY | INV_ATTR_TAG_FLASK | INV_ATTR_TAG_MITIGATION | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_SPECIALTY_BERSERKER_MITIGATION,
        { DND_MODBASE_SPECIALTY_BERSERKER, INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_ENERGY | INV_ATTR_TAG_FLASK | INV_ATTR_TAG_ARMOR | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_SPECIALTY_BERSERKER_ARMOR_MITIGATION
        { DND_MODBASE_SPECIALTY_BERSERKER, INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_ENERGY | INV_ATTR_TAG_FLASK | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_SPECIALTY_TRICKSTER_ARMOR,
        { DND_MODBASE_SPECIALTY_TRICKSTER, INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_DEFENSE | INV_ATTR_TAG_LIFE | INV_ATTR_TAG_STAMINA | INV_ATTR_TAG_FLASK | INV_ATTR_TAG_MITIGATION | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_SPECIALTY_TRICKSTER_MITIGATION,
        { DND_MODBASE_SPECIALTY_TRICKSTER, INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_DEFENSE | INV_ATTR_TAG_LIFE | INV_ATTR_TAG_STAMINA | INV_ATTR_TAG_FLASK | INV_ATTR_TAG_ARMOR | INV_ATTR_TAG_ESHIELD },
    
        // DND_ITEMBASE_FLASK_LIFE
        { DND_MODBASE_FLASK, INV_ATTR_TAG_FLASK, 0 },

        // DND_ITEMBASE_FLASK_UTILITY
        { DND_MODBASE_FLASK, INV_ATTR_TAG_FLASK, 0 }
    };

    return tags[item_base];
}

// What a base actually admits. allowed carries every tag its slot could ever take and excluded
// removes what this particular base does not have, so a BODY_ARMOR base drops ESHIELD and
// MITIGATION while BODY_ARMOR_ESHIELD only drops MITIGATION.
int GetItemBaseEffectiveTags(int item_base) {
    itembase_tags_T module& t = GetItemBaseTags(item_base);
    return t.allowed_tags & ~t.excluded_tags;
}

// Tags say what a base admits, allowed_slots on the mod says where that mod can ever live, and both
// have to agree -- the slot clause blocks 7 to 55 mods per base that the tags let through.
int ItemBaseToModBaseFlag(int item_base) {
    return GetItemBaseTags(item_base).slot_flag;
}

#endif