#ifndef DND_ITEMBASE_IN
#define DND_ITEMBASE_IN

// Mod generation profiles describing eligibility of mods to appear naturally on items for drops
enum {
    DND_ITEMBASE_CHARM,

    DND_ITEMBASE_BODY_ARMOR,
    DND_ITEMBASE_BODY_ESHIELD,
    DND_ITEMBASE_BODY_MITIGATION,

    DND_ITEMBASE_BODY_ARMOR_ESHIELD,
    DND_ITEMBASE_BODY_ARMOR_MITIGATION,
    DND_ITEMBASE_BODY_ESHIELD_MITIGATION,

    DND_ITEMBASE_BODY_ARMOR_ESHIELD_MITIGATION,

    DND_ITEMBASE_HELM_ARMOR,
    DND_ITEMBASE_HELM_ESHIELD,
    DND_ITEMBASE_HELM_MITIGATION,

    DND_ITEMBASE_HELM_ARMOR_ESHIELD,
    DND_ITEMBASE_HELM_ARMOR_MITIGATION,
    DND_ITEMBASE_HELM_ESHIELD_MITIGATION,

    DND_ITEMBASE_BOOT_ARMOR,
    DND_ITEMBASE_BOOT_ESHIELD,
    DND_ITEMBASE_BOOT_MITIGATION,

    DND_ITEMBASE_BOOT_ARMOR_ESHIELD,
    DND_ITEMBASE_BOOT_ARMOR_MITIGATION,
    DND_ITEMBASE_BOOT_ESHIELD_MITIGATION,

    DND_ITEMBASE_SPECIALTY_DOOMGUY,
	DND_ITEMBASE_SPECIALTY_MARINE,
	DND_ITEMBASE_SPECIALTY_HOBO,

	DND_ITEMBASE_SPECIALTY_PUNISHER_ARMOR,
    DND_ITEMBASE_SPECIALTY_PUNISHER_ESHIELD,
    DND_ITEMBASE_SPECIALTY_PUNISHER_MITIGATION,

	DND_ITEMBASE_SPECIALTY_WANDERER,
	DND_ITEMBASE_SPECIALTY_CYBORG,

	DND_ITEMBASE_SPECIALTY_BERSERKER_ARMOR,
    DND_ITEMBASE_SPECIALTY_BERSERKER_MITIGATION,
    DND_ITEMBASE_SPECIALTY_BERSERKER_ARMOR_MITIGATION,

	DND_ITEMBASE_SPECIALTY_TRICKSTER_ARMOR,
    DND_ITEMBASE_SPECIALTY_TRICKSTER_MITIGATION,

    DND_ITEMBASE_FLASK_LIFE,
    DND_ITEMBASE_FLASK_UTILITY,

    DND_MAX_ITEMBASES
};

typedef struct {
    int allowed_tags;
    int excluded_tags;
} itembase_tags_T;

// tagsets from item bases defined above -- these are used for mod pools
itembase_tags_T module& GetItemBaseTags(int item_base) {
    static itembase_tags_T tags[DND_MAX_ITEMBASES] = {
        // DND_ITEMBASE_CHARM
        { INV_ATTR_TAG_ALL, 0 },

        // DND_ITEMBASE_BODY_ARMOR,
        { INV_ATTR_TAG_OK_BODYARMOR, INV_ATTR_TAG_EXCLUDED_BODYARMOR | INV_ATTR_TAG_ESHIELD | INV_ATTR_TAG_MITIGATION },

        // DND_ITEMBASE_BODY_ESHIELD,
        { INV_ATTR_TAG_OK_BODYARMOR, INV_ATTR_TAG_EXCLUDED_BODYARMOR | INV_ATTR_TAG_ARMOR | INV_ATTR_TAG_MITIGATION },

        // DND_ITEMBASE_BODY_MITIGATION,
        { INV_ATTR_TAG_OK_BODYARMOR, INV_ATTR_TAG_EXCLUDED_BODYARMOR | INV_ATTR_TAG_ARMOR | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_BODY_ARMOR_ESHIELD,
        { INV_ATTR_TAG_OK_BODYARMOR, INV_ATTR_TAG_EXCLUDED_BODYARMOR | INV_ATTR_TAG_MITIGATION },

        // DND_ITEMBASE_BODY_ARMOR_MITIGATION,
        { INV_ATTR_TAG_OK_BODYARMOR, INV_ATTR_TAG_EXCLUDED_BODYARMOR | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_BODY_ESHIELD_MITIGATION,
        { INV_ATTR_TAG_OK_BODYARMOR, INV_ATTR_TAG_EXCLUDED_BODYARMOR | INV_ATTR_TAG_ARMOR },

        // DND_ITEMBASE_BODY_ARMOR_ESHIELD_MITIGATION
        { INV_ATTR_TAG_OK_BODYARMOR, INV_ATTR_TAG_EXCLUDED_BODYARMOR },

        // DND_ITEMBASE_HELM_ARMOR,
        { INV_ATTR_TAG_OK_HELM, INV_ATTR_TAG_EXCLUDED_HELM | INV_ATTR_TAG_MITIGATION | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_HELM_ESHIELD,
        { INV_ATTR_TAG_OK_HELM, INV_ATTR_TAG_EXCLUDED_HELM | INV_ATTR_TAG_MITIGATION | INV_ATTR_TAG_ARMOR },

        // DND_ITEMBASE_HELM_MITIGATION,
        { INV_ATTR_TAG_OK_HELM, INV_ATTR_TAG_EXCLUDED_HELM | INV_ATTR_TAG_ARMOR | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_HELM_ARMOR_ESHIELD,
        { INV_ATTR_TAG_OK_HELM, INV_ATTR_TAG_EXCLUDED_HELM | INV_ATTR_TAG_MITIGATION },

        // DND_ITEMBASE_HELM_ARMOR_MITIGATION,
        { INV_ATTR_TAG_OK_HELM, INV_ATTR_TAG_EXCLUDED_HELM | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_HELM_ESHIELD_MITIGATION,
        { INV_ATTR_TAG_OK_HELM, INV_ATTR_TAG_EXCLUDED_HELM | INV_ATTR_TAG_ARMOR },

        // DND_ITEMBASE_BOOT_ARMOR,
        { INV_ATTR_TAG_OK_BOOT, INV_ATTR_TAG_EXCLUDED_BOOT | INV_ATTR_TAG_MITIGATION | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_BOOT_ESHIELD,
        { INV_ATTR_TAG_OK_BOOT, INV_ATTR_TAG_EXCLUDED_BOOT | INV_ATTR_TAG_MITIGATION | INV_ATTR_TAG_ARMOR },

        // DND_ITEMBASE_BOOT_MITIGATION,
        { INV_ATTR_TAG_OK_BOOT, INV_ATTR_TAG_EXCLUDED_BOOT | INV_ATTR_TAG_ARMOR | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_BOOT_ARMOR_ESHIELD,
        { INV_ATTR_TAG_OK_BOOT, INV_ATTR_TAG_EXCLUDED_BOOT | INV_ATTR_TAG_MITIGATION },

        // DND_ITEMBASE_BOOT_ARMOR_MITIGATION,
        { INV_ATTR_TAG_OK_BOOT, INV_ATTR_TAG_EXCLUDED_BOOT | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_BOOT_ESHIELD_MITIGATION,
        { INV_ATTR_TAG_OK_BOOT, INV_ATTR_TAG_EXCLUDED_BOOT | INV_ATTR_TAG_ARMOR },

        // DND_ITEMBASE_SPECIALTY_DOOMGUY,
        { INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_FLASK },

        // DND_ITEMBASE_SPECIALTY_MARINE,
        { INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_STAMINA | INV_ATTR_TAG_FLASK },

        // DND_ITEMBASE_SPECIALTY_HOBO,
        { INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_STAMINA | INV_ATTR_TAG_FLASK },

        // DND_ITEMBASE_SPECIALTY_PUNISHER_ARMOR,
        { INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_STAMINA | INV_ATTR_TAG_FLASK | INV_ATTR_TAG_MITIGATION | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_SPECIALTY_PUNISHER_ESHIELD,
        { INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_STAMINA | INV_ATTR_TAG_FLASK | INV_ATTR_TAG_MITIGATION | INV_ATTR_TAG_ARMOR },

        // DND_ITEMBASE_SPECIALTY_PUNISHER_MITIGATION,
        { INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_STAMINA | INV_ATTR_TAG_FLASK | INV_ATTR_TAG_ARMOR | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_SPECIALTY_WANDERER,
        { INV_ATTR_TAG_ALL, INV_ATTR_TAG_STAMINA | INV_ATTR_TAG_FLASK },

        // DND_ITEMBASE_SPECIALTY_CYBORG,
        { INV_ATTR_TAG_ALL, INV_ATTR_TAG_STAMINA | INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_FLASK },

        // DND_ITEMBASE_SPECIALTY_BERSERKER_ARMOR,
        { INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_ENERGY | INV_ATTR_TAG_FLASK | INV_ATTR_TAG_MITIGATION | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_SPECIALTY_BERSERKER_MITIGATION,
        { INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_ENERGY | INV_ATTR_TAG_FLASK | INV_ATTR_TAG_ARMOR | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_SPECIALTY_BERSERKER_ARMOR_MITIGATION
        { INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_ENERGY | INV_ATTR_TAG_FLASK | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_SPECIALTY_TRICKSTER_ARMOR,
        { INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_DEFENSE | INV_ATTR_TAG_LIFE | INV_ATTR_TAG_STAMINA | INV_ATTR_TAG_FLASK | INV_ATTR_TAG_MITIGATION | INV_ATTR_TAG_ESHIELD },

        // DND_ITEMBASE_SPECIALTY_TRICKSTER_MITIGATION,
        { INV_ATTR_TAG_ALL, INV_ATTR_TAG_OCCULT | INV_ATTR_TAG_DEFENSE | INV_ATTR_TAG_LIFE | INV_ATTR_TAG_STAMINA | INV_ATTR_TAG_FLASK | INV_ATTR_TAG_ARMOR | INV_ATTR_TAG_ESHIELD },
    
        // DND_ITEMBASE_FLASK_LIFE
        { INV_ATTR_TAG_FLASK, 0 },

        // DND_ITEMBASE_FLASK_UTILITY
        { INV_ATTR_TAG_FLASK, 0 }
    };

    return tags[item_base];
}

#endif