#ifndef DND_INVATTRIBTABLE_IN
#define DND_INVATTRIBTABLE_IN

// these two imply we have 1000 regular charm mods potentially, 1000 essence and unlimited unique mods
// reason we have these generous ranges is so when a new mod is added, database resets do not need to happen
#define CORRUPT_ATTRIB_ID_BEGIN 1000
#define IMPLICIT_ATTRIB_ID_BEGIN 1250
#define ESSENCE_ATTRIB_ID_BEGIN 1500
#define INCURSION_ATTRIB_ID_BEGIN 2000
#define FLASK_IMPLICIT_ID_BEGIN 2300
#define FLASK_ATTRIB_ID_BEGIN 2400
#define UNIQUE_ATTRIB_ID_BEGIN 2500
// self note: all status_buffs_X modifiers are handled as exceptions
enum {
	INV_HP_INCREASE,
	INV_ARMOR_INCREASE,
	INV_HPPERCENT_INCREASE,
	INV_ARMORPERCENT_INCREASE,
	INV_EXPGAIN_INCREASE,
	INV_CREDITGAIN_INCREASE,
	INV_DROPCHANCE_INCREASE,
	INV_LUCK_INCREASE,
	INV_AMMOCAP_INCREASE,
	INV_SPEED_INCREASE,
	INV_MAGAZINE_INCREASE,
	
	INV_FLATPHYS_DAMAGE,
	INV_FLATENERGY_DAMAGE,
	INV_FLATRADIUS_DAMAGE,
	INV_FLATMAGIC_DAMAGE,
	INV_FLATELEM_DAMAGE,
	
	INV_PERCENTPHYS_DAMAGE,
	INV_PERCENTENERGY_DAMAGE,
	INV_PERCENTRADIUS_DAMAGE,
	INV_PERCENTMAGIC_DAMAGE,
	INV_PERCENTELEM_DAMAGE,
	
	INV_HANDGUN_PERCENT,
	INV_SHOTGUN_PERCENT,
	INV_AUTOMATIC_PERCENT,
	INV_ARTILLERY_PERCENT,
	INV_PRECISION_PERCENT,

	INV_FLAT_HANDGUN,
	INV_FLAT_SHOTGUN,
	INV_FLAT_AUTOMATIC,
	INV_FLAT_ARTILLERY,

	INV_PELLET_INCREASE,
	
	INV_EXPLOSION_RADIUS,
	INV_SELFDMG_RESIST,
	
	INV_AMMOGAIN_CHANCE,
	INV_AMMOGAIN_INCREASE,
	INV_SHOPSTOCK_INCREASE,
	
	INV_REGENCAP_INCREASE,
	
	INV_CRITCHANCE_INCREASE,
	INV_CRITPERCENT_INCREASE,
	INV_CRITDAMAGE_INCREASE,
	
	INV_KNOCKBACK_RESIST,
	INV_DAMAGEPERCENT_MORE,
	INV_ACCURACY_INCREASE,
	
	INV_STAT_STRENGTH,
	INV_STAT_DEXTERITY,
	INV_STAT_INTELLECT,
	
	INV_DMGREDUCE_ELEM,
	INV_DMGREDUCE_PHYS,
	INV_DMGREDUCE_REFL,
	
	INV_PEN_PHYSICAL,
	INV_PEN_ENERGY,
	INV_CHANCE_IGNORERADIUSIMMUNITY,
	INV_PEN_OCCULT,
	INV_PEN_ELEMENTAL,
	
	INV_FLAT_FIREDMG,
	INV_FLAT_ICEDMG,
	INV_FLAT_LIGHTNINGDMG,
	INV_FLAT_POISONDMG,
	
	INV_LIFESTEAL,
	
	INV_POISON_TICRATE,
	INV_POISON_DURATION,
	INV_POISON_TICDMG,
	
	INV_BLOCKERS_MOREDMG,
	
	INV_FREEZECHANCE,
	INV_SLOWEFFECT,
	INV_CHILLTHRESHOLD,
	
	INV_IGNITECHANCE,
	INV_IGNITEDMG,
	INV_IGNITEDURATION,
	
	INV_OVERLOADCHANCE,
	INV_OVERLOAD_ZAPCOUNT,
	INV_OVERLOAD_DMGINCREASE,
	
	INV_CYBERNETIC,
	INV_MELEERANGE,
	INV_MELEEDAMAGE,
	INV_DOTMULTI,
	INV_INCREASEDDOT,
	
	INV_PROJSPEED,
	INV_DMGREDUCE_ENERGY,
	INV_PERCENT_KNOCKBACKRESIST,
	INV_DMGREDUCE_MAGIC,
	INV_DOTMULTI_FIRE,
	INV_DOTMULTI_POISON,
	INV_DOTMULTI_BLEED,
	INV_CHARGEDURATION,
	
	INV_ADDEDMAXRESIST,
	INV_REGENRATE,
	
	INV_LIFESTEAL_RATE,
	INV_LIFESTEAL_RECOVERY,
	INV_LIFESTEAL_CAP,
	INV_LIFESTEAL_DAMAGE,
	
	INV_OVERLOAD_DURATION,
	
	INV_IGNITE_PROLIFCHANCE,
	INV_IGNITE_PROLIFCOUNT,
	INV_IGNITE_PROLIFRANGE,
	
	INV_CHANCE_AILMENTIGNORE,
	INV_CHANCE_FLATIGNITE,
	INV_CHANCE_FLATPROLIF,

	INV_SHIELD_INCREASE,
	INV_PERCENTSHIELD_INCREASE,
	INV_SHIELD_RECOVERYRATE,
	INV_SHIELD_RECHARGEDELAY,
	INV_MIT_INCREASE,
	INV_MITEFFECT_INCREASE,

	INV_PERCENTFIRE_DAMAGE,
	INV_PERCENTICE_DAMAGE,
	INV_PERCENTLIGHTNING_DAMAGE,
	INV_PERCENTPOISON_DAMAGE,

	INV_PEN_FIRE,
	INV_PEN_ICE,
	INV_PEN_LIGHTNING,
	INV_PEN_POISON,

	INV_MAGIC_NEGATION,

	INV_FLAT_TECH,
	INV_FLAT_PRECISION,
	INV_TECH_PERCENT,
	INV_FLAT_MAGIC,
	INV_MAGIC_PERCENT,

	INV_REDUCED_OVERHEAT,
	INV_DMGREDUCE_ALL,
	INV_ITEMRARITY,

	INV_RIPCOUNT,
	INV_RIPDAMAGE,
	INV_LOCKONAREA,
	INV_LOCKONRANGE,
	INV_INCKILLINGSPREE,
	INV_REDUCEDCURSEEFFECT,
	INV_REDUCEDCURSEDURATION,
	INV_AVOID_IGNITE,
	INV_AVOID_CHILLFREEZE,
	INV_AVOID_POISON,
	INV_AVOID_OVERLOAD,
	INV_AVOID_ELEAILMENTS,
	INV_AVOID_BLEED,

	INV_CHANCE_BLEED,
	INV_PERCENTDMG_BLEED,
	INV_BLEED_DURATION,

	INV_CRITPERCENT_FORWEPTYPE,
	INV_FRENZYCHARGE_ONSHATTER,
	INV_ENDURANCECHARGE_ONMELEE,
	INV_POWERCHARGE_ONOVERLOAD,
	INV_INC_STAMINA,
	INV_INC_STAMINARECOVERYRATE,
	INV_INC_STAMINAGAINED,
	INV_MELEECRIT_NOTONLOWSTAMINA,
	INV_MELEESPLASH_NOTONLOWSTAMINA,
	INV_MELEE_ATKCDR,
	INV_CRUSHINGBLOW,
	INV_DEEPCUTS,
	INV_OPENWOUNDS,
	INV_DEADLYSTRIKE,
	INV_REAPINGCLEAVE,

	INV_INCFLASKCHARGEGAINED,
	INV_FLASKLIFERECOVERYRATE,

	// add new regular rollable attributes here

	// corrupted implicits -- add new ones here
	INV_CORR_WEAPONDMG = CORRUPT_ATTRIB_ID_BEGIN,
	INV_CORR_WEAPONCRIT,
	INV_CORR_WEAPONCRITDMG,
	INV_CORR_SPEED,
	INV_CORR_DROPCHANCE,
	INV_CORR_PERCENTSTATS,
	INV_CORR_WEAPONPLUSPROJ,
	INV_CORR_WEAPONPOISONPCT,
	INV_CORR_WEAPONFORCEPAIN,
	INV_CORR_CYBERNETIC,
	INV_CORR_DMGDOESNTSTOPREGEN,
	INV_CORR_INSTALEECHPCT,
	INV_CORR_MOREAOE,
	INV_CORR_ALLPIERCE,
	INV_CORR_WEPCULL,
	INV_CORR_MAXFRENZY,
	INV_CORR_MAXENDURANCE,
	INV_CORR_MAXPOWER,
	// add new corruption implicits here

	// implicits -- add new ones below here
	INV_IMP_INCARMOR = IMPLICIT_ATTRIB_ID_BEGIN,
	INV_IMP_INCSHIELD,
	INV_IMP_INCARMORSHIELD,
	INV_IMP_INCMIT,
	INV_IMP_INCMITARMOR,
	INV_IMP_INCMITSHIELD,
	INV_IMP_POWERCORE,
	INV_IMP_UNSTABLECORE,
	INV_IMP_INCMITARMORSHIELD,

	INV_IMP_RAVAGER,					// ravager armor
	INV_IMP_DOUBLEESHIELDRECOVERY,		// 
	INV_IMP_ABSORBLIGHTNING,			// lightning coil
	INV_IMP_KNIGHTARMOR,
	INV_IMP_HANDGUNBONUS,
	INV_IMP_NECROARMOR,
	INV_IMP_CANROLL_PHYS,
	INV_IMP_CANROLL_MAGIC,
	INV_IMP_CANROLL_EXPLOSIVE,
	INV_IMP_CANROLL_ENERGY,
	INV_IMP_CANROLL_ELEMENTAL,
	INV_IMP_HIGHREFLECTREDUCE,			// synth metal
	INV_IMP_ESHIELDBLOCKSALL,
	INV_IMP_LESSLIGHTNINGTAKEN,
	INV_IMP_FASTEROVERHEATDISS,
	INV_IMP_LESSPOISONTAKEN,
	INV_IMP_LESSFIRETAKEN,
	INV_IMP_LESSSELFDAMAGETAKEN,
	INV_IMP_BONUSPETCAP,
	INV_IMP_REDUCEDVISIONIMPAIR,		// synthmetal mask
	INV_IMP_MELEEIGNORESSHIELDS,
	INV_IMP_MOREDAMAGETOBOSSES,
	INV_IMP_RECOVERESONUNDEADKILL,
	INV_IMP_PRECISIONCRITBONUS,
	INV_IMP_QUALITYCAPFIFTY,
	INV_IMP_PERCENTSTR,
	INV_IMP_PERCENTDEX,
	INV_IMP_PERCENTINT,
	INV_IMP_REDUCEDSLOWSHOTGUNS,
	INV_IMP_AMMOGAIN_SHOTGUNS,
	INV_IMP_ONKILL_FRENZY,
	INV_IMP_ONKILL_ENDURANCE,
	INV_IMP_ONKILL_POWER,
	INV_IMP_PHASINGTIME,
	INV_IMP_STAMINAONKILL,
	// add new implicits here
	
	// essence attributes (only via. specific means)
	INV_ESS_VAAJ = ESSENCE_ATTRIB_ID_BEGIN,
	INV_ESS_SSRATH,
	INV_ESS_OMNISIGHT,
	INV_ESS_OMNISIGHT2,
	INV_ESS_CHEGOVAX,
	INV_ESS_HARKIMONDE,
	INV_ESS_LESHRAC,
	INV_ESS_KRULL,
	INV_ESS_THORAX,
	INV_ESS_ZRAVOG,
	INV_ESS_ERYXIA,
	// add new essences here

	INV_INC_DOUBLEHPBONUS = INCURSION_ATTRIB_ID_BEGIN,
	INV_INC_MAXPOISONSTACK,
	INV_INC_POISONSPREAD,
	INV_INC_CRITFORDOT,
	INV_INC_ALLOVERLOAD,
	INV_INC_ESHIELDNOINTERRUPT,
	INV_INC_PLUSPROJ,
	INV_INC_PLUSTWOPROJ,
	INV_INC_INSTANTLIFESTEAL,
	INV_INC_TWICEARMORDEFENSE,
	INV_INC_MITIGATIONTODODGE,
	INV_INC_ACCURACYFORPRECISION,
	INV_INC_HPREGENINTERRUPT,
	INV_INC_PASSIVEREGEN,
	INV_INC_ENEMYRIPCHANCE,
	INV_INC_BLOCKPREVENTION,
	INV_INC_RIPPERSEXPLODE,
	INV_INC_INVERTRESISTANCES,
	INV_INC_ACCURACYREVERSED,
	INV_INC_PROJREVERSE,
	INV_INC_EXCESSCRIT,
	// add new incursion mods here

	INV_FLASK_IMP_CHARGECOUNT = FLASK_IMPLICIT_ID_BEGIN,
	INV_FLASK_IMP_LIFE,
	INV_FLASK_IMP_GRANITE,
	INV_FLASK_IMP_BASALT,
	INV_FLASK_IMP_BISMUTH,
	INV_FLASK_IMP_INSULAR,
	INV_FLASK_IMP_OAK,
	INV_FLASK_IMP_ARCANE,
	INV_FLASK_IMP_DIAMOND,
	INV_FLASK_IMP_SILVER,
	INV_FLASK_IMP_SULPHUR,
	INV_FLASK_IMP_QUICKSILVER,
	INV_FLASK_IMP_QUARTZ,

	INV_FLASK_INCCHARGES = FLASK_ATTRIB_ID_BEGIN,
    INV_FLASK_REDUCEDCHARGEUSE,
    INV_FLASK_INCAMOUNTRECOVER,
    INV_FLASK_INSTANTRECOVERY,
    INV_FLASK_INCEFFECT,
    INV_FLASK_INCDURATION,
    INV_FLASK_IMMUNE_BLEED,
    INV_FLASK_IMMUNE_POISON,
    INV_FLASK_IMMUNE_SHOCK,
    INV_FLASK_IMMUNE_IGNITE,
    INV_FLASK_IMMUNE_CHILLFREEZE,
    INV_FLASK_CHANCEGAINCRIT,
    INV_FLASK_CHANCEGAINONHIT,
    INV_FLASK_INCCHARGERECOVERY,
    INV_FLASK_INCRECOVERYRATE,
    INV_FLASK_INSTANTONLOWLIFE,
    INV_FLASK_MORERECOVERYONLOWLIFE,
	
	// below here are exotic attributes not found in normal items, if you add new attributes do so to above and change MAX_INV_ATTRIBUTE_TYPES
	INV_EX_CHANCE_CASTELEMSPELLONATK = UNIQUE_ATTRIB_ID_BEGIN,
	INV_EX_KNOCKBACK_IMMUNITY,
	INV_EX_FACTOR_SMALLCHARM,
	INV_EX_ALLSTATS,
	INV_EX_CHANCE_HEALMISSINGONPAIN,
	INV_EX_DMGINCREASE_LIGHTNING,
	INV_EX_MORECRIT_LIGHTNING,
	INV_EX_SECONDEXPBONUS,
	INV_EX_DOUBLE_HEALTHCAP,
	INV_EX_PHYSDAMAGEPER_FLATHEALTH, // only 1%
	INV_EX_FORBID_ARMOR,
	INV_EX_BEHAVIOR_PELLETSFIRECIRCLE,
	INV_EX_FORSHOW_BURSTGETSPELLETBONUS,
	INV_EX_CHANCE_ONDEATH_RAISEZOMBIE,
	INV_EX_DMGREDUCE_SHAREWITHPETS,
	INV_EX_DMGINCREASE_TAKEN,
	INV_EX_FLATDMG_ALL,
	INV_EX_ONKILL_HEALMISSING,
	INV_EX_SOULWEPS_FULLDAMAGE,
	INV_EX_PICKUPS_MORESOUL,
	INV_EX_ABILITY_RALLY,
	INV_EX_BEHAVIOR_SPELLSFULLDAMAGE,
	INV_EX_ABILITY_MONSTERSRIP,
	INV_EX_FLATDOT,
	INV_EX_DOTDURATION,
	INV_EX_ABILITY_LUCKYCRIT,
	INV_EX_CRITIGNORERESCHANCE,
	INV_EX_CURSEIMMUNITY,
	INV_EX_LIMITEDSMALLCHARMS,
	INV_EX_FLATPERSHOTGUNOWNED,
	INV_EX_LESSHEALING,
	INV_EX_SOULWEPSPEN,
	INV_EX_DEADEYEBONUS,
	INV_EX_DAMAGPERMISSINGAMMO,
	INV_EX_MOREAMMOUSE,
	INV_EX_REDUCEDAMMOCAP,
	INV_EX_UNITY,
	INV_EX_UNITY_RES_BONUS,
	INV_EX_UNITY_PEN_BONUS,
	INV_EX_UNITY_NOBONUS,
	INV_EX_INTBONUSTOMELEE,
	INV_EX_STARTESONDEPLETE,
	INV_EX_ESCHARGE_DMGNOINTERRUPT,
	INV_EX_ESEXPLOSIONHPDMG,
	INV_EX_ESCHARGE_USEHP,
	INV_EX_HPTOESHIELD,
	INV_EX_ESHIELDFULLABSORB,
	INV_EX_HEALTHATONE,
	INV_EX_RESPERESHIELD,
	INV_EX_ESHIELDONLYBLOCKPCT,
	INV_EX_REFILLAMMOONMELEEKILL,
	INV_EX_SWAPFROMMELEECRIT,
	INV_EX_DAMAGELOWESTTAKENASPHYS,
	INV_EX_DEMONBARRIERS,
	INV_EX_SOULPICKUPSINFAMMO,
	INV_EX_SOULPICKUPSONLYAMMO,
	INV_EX_STREXTRABONUSTOMELEE,
	INV_EX_ELEPENHARMONY,
	INV_EX_CANFIREOVERHEATED,
	INV_EX_CANTFIRENONOVERHEAT,
	INV_EX_MOREDMGPEROVERHEAT,
	INV_EX_LESSDMGTAKENMAXOVERHEAT,
	INV_EX_WEAPONSUSEHEALTH,
	INV_EX_CANNOTPICKAMMO,
	INV_EX_AMMOCOSTMULTIPLIER,
	INV_EX_RIPPERSONETIMEONLY,
	INV_EX_RIPPERSRIPALL,
	INV_EX_MIRROROTHERMEDIUM,
	INV_EX_CHANCEGAINXCHARGE,
	INV_EX_CHARGEDURATIONHALVED,
	INV_EX_MOREDAMAGEPERCHARGE,
	INV_EX_COUNTASHAVINGMAXCHARGEOF,
	// add new unique attributes here
	INV_EX_PLAYERPOWERSET1, // holds certain powers that are just bitfields in one -- is not shown in item attrib list
};

// attributes below last_inv (normal rollables) are exotic
#define FIRST_INV_ATTRIBUTE INV_HP_INCREASE
#define LAST_INV_ATTRIBUTE INV_FLASKLIFERECOVERYRATE
#define NORMAL_ATTRIBUTE_COUNT (LAST_INV_ATTRIBUTE - FIRST_INV_ATTRIBUTE + 1)

// modify the above to make it use the negative last
//#define NEGATIVE_ATTRIB_BEGIN INV_NEG_DAMAGE_DEALT
#define UNIQUE_ATTRIB_BEGIN INV_EX_CHANCE_CASTELEMSPELLONATK
#define UNIQUE_ATTRIB_END INV_EX_PLAYERPOWERSET1
#define UNIQUE_ATTRIB_COUNT (UNIQUE_ATTRIB_END - UNIQUE_ATTRIB_BEGIN + 1)

#define FIRST_CORRUPT_IMPLICIT INV_CORR_WEAPONDMG
#define LAST_CORRUPT_IMPLICIT INV_CORR_MAXPOWER
#define MAX_CORRUPT_IMPLICITS (LAST_CORRUPT_IMPLICIT - FIRST_CORRUPT_IMPLICIT + 1)

#define FIRST_REGULAR_IMPLICIT INV_IMP_INCARMOR
#define LAST_REGULAR_IMPLICIT INV_IMP_STAMINAONKILL

#define FIRST_ESSENCE_ATTRIBUTE INV_ESS_VAAJ
#define LAST_ESSENCE_ATTRIBUTE INV_ESS_ERYXIA
#define ESSENCE_ATTRIBUTE_COUNT (LAST_ESSENCE_ATTRIBUTE - FIRST_ESSENCE_ATTRIBUTE + 1)
#define ESSENCE_MAP_MACRO(X) ((X) - FIRST_ESSENCE_ATTRIBUTE + 1)

#define FIRST_INCURSION_ATTRIBUTE INV_INC_DOUBLEHPBONUS
#define LAST_INCURSION_ATTRIBUTE INV_INC_EXCESSCRIT
#define INCURSION_ATTRIBUTE_COUNT (LAST_INCURSION_ATTRIBUTE - FIRST_INCURSION_ATTRIBUTE + 1)
#define INCURSION_MAP_MACRO(X) ((X) - FIRST_INCURSION_ATTRIBUTE + 1)

#define FIRST_FLASK_IMPLICIT INV_FLASK_IMP_CHARGECOUNT
#define LAST_FLASK_IMPICIT INV_FLASK_IMP_QUARTZ

#define FIRST_FLASK_ATTRIBUTE INV_FLASK_INCCHARGES
#define LAST_FLASK_ATTRIBUTE INV_FLASK_MORERECOVERYONLOWLIFE
#define FLASK_ATTRIBUTE_COUNT (LAST_FLASK_ATTRIBUTE - FIRST_FLASK_ATTRIBUTEFIRST_FLASK_ATTRIBUTE + 1)
#define FLASK_MAP_MACRO(X) ((X) - FIRST_FLASK_ATTRIBUTE + 1)

#define MAX_INV_ATTRIBUTE_TYPES (NORMAL_ATTRIBUTE_COUNT + ESSENCE_ATTRIBUTE_COUNT + INCURSION_ATTRIBUTE_COUNT)
#define UNIQUE_MAP_MACRO(X) ((X) - UNIQUE_ATTRIB_ID_BEGIN + 1)
#define MAX_TOTAL_ATTRIBUTES 3000 // 1000 for each of: regular, essence, unique mods.

typedef struct {
	int attrib_low;
	int attrib_high;
	int attrib_extra_low;
	int attrib_extra_high;
	int attrib_level_modifier;
	int attrib_level_extra_modifier;
	int tags;										// tags
	int allowed_slots;								// what slots can these appear on, DND_MODBASE_XXX
	int weight;
} inv_attrib_T;

// reason why this uses UNIQUE_ATTRIB_ID_BEGIN, it skips regular and essence mod indexes. This means, we have enough room without database reset for both regular
// and essence mods. This is good for future compatibility as well.
// Currently: 2000 mods, 0-1999
global inv_attrib_T 62: ItemModTable[UNIQUE_ATTRIB_ID_BEGIN];

void SetupInventoryAttributeTable() {
	// doing this so we populate the global arrays (acs wont allow just initializing them like local variables)
	// and these are global so we move from stack to heap and also only initialize this once when server is launched
	// and never again as opposed to start of every map with local variable method
	ItemModTable[INV_HP_INCREASE].attrib_low = 5;
	ItemModTable[INV_HP_INCREASE].attrib_high = 14;
	ItemModTable[INV_HP_INCREASE].attrib_level_modifier = 0;
	ItemModTable[INV_HP_INCREASE].tags = INV_ATTR_TAG_LIFE;
	ItemModTable[INV_HP_INCREASE].weight = 1000;
	ItemModTable[INV_HP_INCREASE].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;
	
	ItemModTable[INV_ARMOR_INCREASE].attrib_low = 5;
	ItemModTable[INV_ARMOR_INCREASE].attrib_high = 24;
	ItemModTable[INV_ARMOR_INCREASE].attrib_level_modifier = 0;
	ItemModTable[INV_ARMOR_INCREASE].tags = INV_ATTR_TAG_DEFENSE;
	ItemModTable[INV_ARMOR_INCREASE].weight = 1000;
	ItemModTable[INV_ARMOR_INCREASE].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;
	
	ItemModTable[INV_HPPERCENT_INCREASE].attrib_low = 1;
	ItemModTable[INV_HPPERCENT_INCREASE].attrib_high = 6;
	ItemModTable[INV_HPPERCENT_INCREASE].attrib_level_modifier = 0;
	ItemModTable[INV_HPPERCENT_INCREASE].tags = INV_ATTR_TAG_LIFE;
	ItemModTable[INV_HPPERCENT_INCREASE].weight = 800;
	ItemModTable[INV_HPPERCENT_INCREASE].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;
	
	ItemModTable[INV_ARMORPERCENT_INCREASE].attrib_low = 1;
	ItemModTable[INV_ARMORPERCENT_INCREASE].attrib_high = 9;
	ItemModTable[INV_ARMORPERCENT_INCREASE].attrib_level_modifier = 0;
	ItemModTable[INV_ARMORPERCENT_INCREASE].tags = INV_ATTR_TAG_DEFENSE;
	ItemModTable[INV_ARMORPERCENT_INCREASE].weight = 800;
	ItemModTable[INV_ARMORPERCENT_INCREASE].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;
	
	ItemModTable[INV_EXPGAIN_INCREASE].attrib_low = 0.02;
	ItemModTable[INV_EXPGAIN_INCREASE].attrib_high = 0.04;
	ItemModTable[INV_EXPGAIN_INCREASE].attrib_level_modifier = 0.03;
	ItemModTable[INV_EXPGAIN_INCREASE].tags = INV_ATTR_TAG_UTILITY;
	ItemModTable[INV_EXPGAIN_INCREASE].weight = 600;
	ItemModTable[INV_EXPGAIN_INCREASE].allowed_slots = DND_MODBASE_ALL;
	
	ItemModTable[INV_CREDITGAIN_INCREASE].attrib_low = 0.02;
	ItemModTable[INV_CREDITGAIN_INCREASE].attrib_high = 0.04;
	ItemModTable[INV_CREDITGAIN_INCREASE].attrib_level_modifier = 0.03;
	ItemModTable[INV_CREDITGAIN_INCREASE].tags = INV_ATTR_TAG_UTILITY;
	ItemModTable[INV_CREDITGAIN_INCREASE].weight = 600;
	ItemModTable[INV_CREDITGAIN_INCREASE].allowed_slots = DND_MODBASE_ALL;
	
	ItemModTable[INV_DROPCHANCE_INCREASE].attrib_low = 0.025;
	ItemModTable[INV_DROPCHANCE_INCREASE].attrib_high = 0.05;
	ItemModTable[INV_DROPCHANCE_INCREASE].attrib_level_modifier = 0;
	ItemModTable[INV_DROPCHANCE_INCREASE].tags = INV_ATTR_TAG_UTILITY;
	ItemModTable[INV_DROPCHANCE_INCREASE].weight = 300;
	ItemModTable[INV_DROPCHANCE_INCREASE].allowed_slots = DND_MODBASE_CHARM;
	
	ItemModTable[INV_LUCK_INCREASE].attrib_low = 0.005;
	ItemModTable[INV_LUCK_INCREASE].attrib_high = 0.015;
	ItemModTable[INV_LUCK_INCREASE].attrib_level_modifier = 0;
	ItemModTable[INV_LUCK_INCREASE].tags = INV_ATTR_TAG_UTILITY;
	ItemModTable[INV_LUCK_INCREASE].weight = 200;
	ItemModTable[INV_LUCK_INCREASE].allowed_slots = DND_MODBASE_CHARM;
	
	ItemModTable[INV_AMMOCAP_INCREASE].attrib_low = 5;
	ItemModTable[INV_AMMOCAP_INCREASE].attrib_high = 14;
	ItemModTable[INV_AMMOCAP_INCREASE].attrib_level_modifier = 0;
	ItemModTable[INV_AMMOCAP_INCREASE].tags = INV_ATTR_TAG_UTILITY;
	ItemModTable[INV_AMMOCAP_INCREASE].weight = 250;
	ItemModTable[INV_AMMOCAP_INCREASE].allowed_slots = DND_MODBASE_AMMO;
	
	ItemModTable[INV_SPEED_INCREASE].attrib_low = 1;
	ItemModTable[INV_SPEED_INCREASE].attrib_high = 3;
	ItemModTable[INV_SPEED_INCREASE].attrib_level_modifier = 2;
	ItemModTable[INV_SPEED_INCREASE].tags = INV_ATTR_TAG_UTILITY;
	ItemModTable[INV_SPEED_INCREASE].weight = 250;
	ItemModTable[INV_SPEED_INCREASE].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_BOOT | DND_MODBASE_SPECIALTY_ALL;
	
	ItemModTable[INV_MAGAZINE_INCREASE].attrib_low = 1;
	ItemModTable[INV_MAGAZINE_INCREASE].attrib_high = 10;
	ItemModTable[INV_MAGAZINE_INCREASE].attrib_level_modifier = 0;
	ItemModTable[INV_MAGAZINE_INCREASE].tags = INV_ATTR_TAG_UTILITY;
	ItemModTable[INV_MAGAZINE_INCREASE].weight = 300;
	ItemModTable[INV_MAGAZINE_INCREASE].allowed_slots = DND_MODBASE_AMMO;
	
	ItemModTable[INV_FLATPHYS_DAMAGE].attrib_low = 1;
	ItemModTable[INV_FLATPHYS_DAMAGE].attrib_high = 3;
	ItemModTable[INV_FLATPHYS_DAMAGE].attrib_level_modifier = 0;
	ItemModTable[INV_FLATPHYS_DAMAGE].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_PHYSICAL;
	ItemModTable[INV_FLATPHYS_DAMAGE].weight = 750;
	ItemModTable[INV_FLATPHYS_DAMAGE].allowed_slots = DND_MODBASE_PHYSICALATK;
	
	ItemModTable[INV_FLATENERGY_DAMAGE].attrib_low = 1;
	ItemModTable[INV_FLATENERGY_DAMAGE].attrib_high = 3;
	ItemModTable[INV_FLATENERGY_DAMAGE].attrib_level_modifier = 0;
	ItemModTable[INV_FLATENERGY_DAMAGE].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_ENERGY;
	ItemModTable[INV_FLATENERGY_DAMAGE].weight = 675;
	ItemModTable[INV_FLATENERGY_DAMAGE].allowed_slots = DND_MODBASE_ENERGYATK;
	
	ItemModTable[INV_FLATRADIUS_DAMAGE].attrib_low = 1;
	ItemModTable[INV_FLATRADIUS_DAMAGE].attrib_high = 2;
	ItemModTable[INV_FLATRADIUS_DAMAGE].attrib_level_modifier = 0;
	ItemModTable[INV_FLATRADIUS_DAMAGE].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_EXPLOSIVE;
	ItemModTable[INV_FLATRADIUS_DAMAGE].weight = 675;
	ItemModTable[INV_FLATRADIUS_DAMAGE].allowed_slots = DND_MODBASE_RADIUSATK;
	
	ItemModTable[INV_FLATMAGIC_DAMAGE].attrib_low = 1;
	ItemModTable[INV_FLATMAGIC_DAMAGE].attrib_high = 3;
	ItemModTable[INV_FLATMAGIC_DAMAGE].attrib_level_modifier = 0;
	ItemModTable[INV_FLATMAGIC_DAMAGE].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_OCCULT;
	ItemModTable[INV_FLATMAGIC_DAMAGE].weight = 675;
	ItemModTable[INV_FLATMAGIC_DAMAGE].allowed_slots = DND_MODBASE_MAGICALATK;
	
	ItemModTable[INV_FLATELEM_DAMAGE].attrib_low = 1;
	ItemModTable[INV_FLATELEM_DAMAGE].attrib_high = 3;
	ItemModTable[INV_FLATELEM_DAMAGE].attrib_level_modifier = 0;
	ItemModTable[INV_FLATELEM_DAMAGE].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_ELEMENTAL;
	ItemModTable[INV_FLATELEM_DAMAGE].weight = 750;
	ItemModTable[INV_FLATELEM_DAMAGE].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_PERCENTPHYS_DAMAGE].attrib_low = 5;
	ItemModTable[INV_PERCENTPHYS_DAMAGE].attrib_high = 15;
	ItemModTable[INV_PERCENTPHYS_DAMAGE].attrib_level_modifier = 0;
	ItemModTable[INV_PERCENTPHYS_DAMAGE].tags = INV_ATTR_TAG_DAMAGE | INV_ATTR_TAG_PHYSICAL;
	ItemModTable[INV_PERCENTPHYS_DAMAGE].weight = 675;
	ItemModTable[INV_PERCENTPHYS_DAMAGE].allowed_slots = DND_MODBASE_PHYSICALATK;
	
	ItemModTable[INV_PERCENTENERGY_DAMAGE].attrib_low = 5;
	ItemModTable[INV_PERCENTENERGY_DAMAGE].attrib_high = 15;
	ItemModTable[INV_PERCENTENERGY_DAMAGE].attrib_level_modifier = 0;
	ItemModTable[INV_PERCENTENERGY_DAMAGE].tags = INV_ATTR_TAG_DAMAGE | INV_ATTR_TAG_ENERGY;
	ItemModTable[INV_PERCENTENERGY_DAMAGE].weight = 600;
	ItemModTable[INV_PERCENTENERGY_DAMAGE].allowed_slots = DND_MODBASE_ENERGYATK;
	
	ItemModTable[INV_PERCENTRADIUS_DAMAGE].attrib_low = 2;
	ItemModTable[INV_PERCENTRADIUS_DAMAGE].attrib_high = 7;
	ItemModTable[INV_PERCENTRADIUS_DAMAGE].attrib_level_modifier = 0;
	ItemModTable[INV_PERCENTRADIUS_DAMAGE].tags = INV_ATTR_TAG_DAMAGE | INV_ATTR_TAG_EXPLOSIVE;
	ItemModTable[INV_PERCENTRADIUS_DAMAGE].weight = 600;
	ItemModTable[INV_PERCENTRADIUS_DAMAGE].allowed_slots = DND_MODBASE_RADIUSATK;
	
	ItemModTable[INV_PERCENTMAGIC_DAMAGE].attrib_low = 5;
	ItemModTable[INV_PERCENTMAGIC_DAMAGE].attrib_high = 15;
	ItemModTable[INV_PERCENTMAGIC_DAMAGE].attrib_level_modifier = 0;
	ItemModTable[INV_PERCENTMAGIC_DAMAGE].tags = INV_ATTR_TAG_DAMAGE | INV_ATTR_TAG_OCCULT;
	ItemModTable[INV_PERCENTMAGIC_DAMAGE].weight = 600;
	ItemModTable[INV_PERCENTMAGIC_DAMAGE].allowed_slots = DND_MODBASE_MAGICALATK;
	
	ItemModTable[INV_PERCENTELEM_DAMAGE].attrib_low = 5;
	ItemModTable[INV_PERCENTELEM_DAMAGE].attrib_high = 15;
	ItemModTable[INV_PERCENTELEM_DAMAGE].attrib_level_modifier = 0;
	ItemModTable[INV_PERCENTELEM_DAMAGE].tags = INV_ATTR_TAG_DAMAGE | INV_ATTR_TAG_ELEMENTAL;
	ItemModTable[INV_PERCENTELEM_DAMAGE].weight = 675;
	ItemModTable[INV_PERCENTELEM_DAMAGE].allowed_slots = DND_MODBASE_ELEMATK;

	ItemModTable[INV_HANDGUN_PERCENT].attrib_low = 3;
	ItemModTable[INV_HANDGUN_PERCENT].attrib_high = 12;
	ItemModTable[INV_HANDGUN_PERCENT].attrib_level_modifier = 0;
	ItemModTable[INV_HANDGUN_PERCENT].tags = INV_ATTR_TAG_DAMAGE;
	ItemModTable[INV_HANDGUN_PERCENT].weight = 500;
	ItemModTable[INV_HANDGUN_PERCENT].allowed_slots = DND_MODBASE_WEAPONATK;
	
	ItemModTable[INV_SHOTGUN_PERCENT].attrib_low = 3;
	ItemModTable[INV_SHOTGUN_PERCENT].attrib_high = 12;
	ItemModTable[INV_SHOTGUN_PERCENT].attrib_level_modifier = 0;
	ItemModTable[INV_SHOTGUN_PERCENT].tags = INV_ATTR_TAG_DAMAGE;
	ItemModTable[INV_SHOTGUN_PERCENT].weight = 500;
	ItemModTable[INV_SHOTGUN_PERCENT].allowed_slots = DND_MODBASE_WEAPONATK | DND_MODBASE_SPECIALTY_HOBO;
	
	ItemModTable[INV_AUTOMATIC_PERCENT].attrib_low = 3;
	ItemModTable[INV_AUTOMATIC_PERCENT].attrib_high = 12;
	ItemModTable[INV_AUTOMATIC_PERCENT].attrib_level_modifier = 0;
	ItemModTable[INV_AUTOMATIC_PERCENT].tags = INV_ATTR_TAG_DAMAGE;
	ItemModTable[INV_AUTOMATIC_PERCENT].weight = 500;
	ItemModTable[INV_AUTOMATIC_PERCENT].allowed_slots = DND_MODBASE_WEAPONATK;
	
	ItemModTable[INV_ARTILLERY_PERCENT].attrib_low = 3;
	ItemModTable[INV_ARTILLERY_PERCENT].attrib_high = 12;
	ItemModTable[INV_ARTILLERY_PERCENT].attrib_level_modifier = 0;
	ItemModTable[INV_ARTILLERY_PERCENT].tags = INV_ATTR_TAG_DAMAGE | INV_ATTR_TAG_EXPLOSIVE;
	ItemModTable[INV_ARTILLERY_PERCENT].weight = 500;
	ItemModTable[INV_ARTILLERY_PERCENT].allowed_slots = DND_MODBASE_WEAPONATK | DND_MODBASE_SPECIALTY_MARINE;
	
	ItemModTable[INV_PRECISION_PERCENT].attrib_low = 3;
	ItemModTable[INV_PRECISION_PERCENT].attrib_high = 12;
	ItemModTable[INV_PRECISION_PERCENT].attrib_level_modifier = 0;
	ItemModTable[INV_PRECISION_PERCENT].tags = INV_ATTR_TAG_DAMAGE;
	ItemModTable[INV_PRECISION_PERCENT].weight = 500;
	ItemModTable[INV_PRECISION_PERCENT].allowed_slots = DND_MODBASE_WEAPONATK;
	
	ItemModTable[INV_FLAT_HANDGUN].attrib_low = 1;
	ItemModTable[INV_FLAT_HANDGUN].attrib_high = 3;
	ItemModTable[INV_FLAT_HANDGUN].attrib_level_modifier = 0;
	ItemModTable[INV_FLAT_HANDGUN].tags = INV_ATTR_TAG_ATTACK;
	ItemModTable[INV_FLAT_HANDGUN].weight = 575;
	ItemModTable[INV_FLAT_HANDGUN].allowed_slots = DND_MODBASE_WEAPONATK;
	
	ItemModTable[INV_FLAT_SHOTGUN].attrib_low = 1;
	ItemModTable[INV_FLAT_SHOTGUN].attrib_high = 3;
	ItemModTable[INV_FLAT_SHOTGUN].attrib_level_modifier = 0;
	ItemModTable[INV_FLAT_SHOTGUN].tags = INV_ATTR_TAG_ATTACK;
	ItemModTable[INV_FLAT_SHOTGUN].weight = 575;
	ItemModTable[INV_FLAT_SHOTGUN].allowed_slots = DND_MODBASE_WEAPONATK | DND_MODBASE_SPECIALTY_HOBO;
	
	ItemModTable[INV_FLAT_AUTOMATIC].attrib_low = 1;
	ItemModTable[INV_FLAT_AUTOMATIC].attrib_high = 3;
	ItemModTable[INV_FLAT_AUTOMATIC].attrib_level_modifier = 0;
	ItemModTable[INV_FLAT_AUTOMATIC].tags = INV_ATTR_TAG_ATTACK;
	ItemModTable[INV_FLAT_AUTOMATIC].weight = 575;
	ItemModTable[INV_FLAT_AUTOMATIC].allowed_slots = DND_MODBASE_WEAPONATK;
	
	ItemModTable[INV_FLAT_ARTILLERY].attrib_low = 1;
	ItemModTable[INV_FLAT_ARTILLERY].attrib_high = 3;
	ItemModTable[INV_FLAT_ARTILLERY].attrib_level_modifier = 0;
	ItemModTable[INV_FLAT_ARTILLERY].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_EXPLOSIVE;
	ItemModTable[INV_FLAT_ARTILLERY].weight = 575;
	ItemModTable[INV_FLAT_ARTILLERY].allowed_slots = DND_MODBASE_WEAPONATK | DND_MODBASE_SPECIALTY_MARINE;
	
	ItemModTable[INV_PELLET_INCREASE].attrib_low = 0.02;
	ItemModTable[INV_PELLET_INCREASE].attrib_high = 0.04;
	ItemModTable[INV_PELLET_INCREASE].attrib_level_modifier = 0.02;
	ItemModTable[INV_PELLET_INCREASE].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_ATTACK;
	ItemModTable[INV_PELLET_INCREASE].weight = 400;
	ItemModTable[INV_PELLET_INCREASE].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_SPECIALTY_HOBO;
	
	ItemModTable[INV_EXPLOSION_RADIUS].attrib_low = 1;
	ItemModTable[INV_EXPLOSION_RADIUS].attrib_high = 8;
	ItemModTable[INV_EXPLOSION_RADIUS].attrib_level_modifier = 0;
	ItemModTable[INV_EXPLOSION_RADIUS].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_EXPLOSIVE;
	ItemModTable[INV_EXPLOSION_RADIUS].weight = 400;
	ItemModTable[INV_EXPLOSION_RADIUS].allowed_slots = DND_MODBASE_RADIUSATK;
	
	ItemModTable[INV_SELFDMG_RESIST].attrib_low = 1;
	ItemModTable[INV_SELFDMG_RESIST].attrib_high = 8;
	ItemModTable[INV_SELFDMG_RESIST].attrib_level_modifier = 0;
	ItemModTable[INV_SELFDMG_RESIST].tags = INV_ATTR_TAG_DEFENSE;
	ItemModTable[INV_SELFDMG_RESIST].weight = 300;
	ItemModTable[INV_SELFDMG_RESIST].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;
	
	ItemModTable[INV_AMMOGAIN_CHANCE].attrib_low = 1;
	ItemModTable[INV_AMMOGAIN_CHANCE].attrib_high = 3;
	ItemModTable[INV_AMMOGAIN_CHANCE].attrib_level_modifier = 0;
	ItemModTable[INV_AMMOGAIN_CHANCE].tags = INV_ATTR_TAG_UTILITY;
	ItemModTable[INV_AMMOGAIN_CHANCE].weight = 300;
	ItemModTable[INV_AMMOGAIN_CHANCE].allowed_slots = DND_MODBASE_AMMO;
	
	ItemModTable[INV_AMMOGAIN_INCREASE].attrib_low = 5;
	ItemModTable[INV_AMMOGAIN_INCREASE].attrib_high = 10;
	ItemModTable[INV_AMMOGAIN_INCREASE].attrib_level_modifier = 0;
	ItemModTable[INV_AMMOGAIN_INCREASE].tags = INV_ATTR_TAG_UTILITY;
	ItemModTable[INV_AMMOGAIN_INCREASE].weight = 400;
	ItemModTable[INV_AMMOGAIN_INCREASE].allowed_slots = DND_MODBASE_AMMO;
	
	ItemModTable[INV_SHOPSTOCK_INCREASE].attrib_low = 1;
	ItemModTable[INV_SHOPSTOCK_INCREASE].attrib_high = 10;
	ItemModTable[INV_SHOPSTOCK_INCREASE].attrib_level_modifier = 0;
	ItemModTable[INV_SHOPSTOCK_INCREASE].tags = INV_ATTR_TAG_UTILITY;
	ItemModTable[INV_SHOPSTOCK_INCREASE].weight = 400;
	ItemModTable[INV_SHOPSTOCK_INCREASE].allowed_slots = DND_MODBASE_CHARM;
	
	ItemModTable[INV_REGENCAP_INCREASE].attrib_low = 1;
	ItemModTable[INV_REGENCAP_INCREASE].attrib_high = 4;
	ItemModTable[INV_REGENCAP_INCREASE].attrib_level_modifier = 0;
	ItemModTable[INV_REGENCAP_INCREASE].tags = INV_ATTR_TAG_UTILITY | INV_ATTR_TAG_LIFE;
	ItemModTable[INV_REGENCAP_INCREASE].weight = 500;
	ItemModTable[INV_REGENCAP_INCREASE].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;
	
	ItemModTable[INV_CRITCHANCE_INCREASE].attrib_low = 0.005;
	ItemModTable[INV_CRITCHANCE_INCREASE].attrib_high = 0.008;
	ItemModTable[INV_CRITCHANCE_INCREASE].attrib_level_modifier = 0.004;
	ItemModTable[INV_CRITCHANCE_INCREASE].tags = INV_ATTR_TAG_CRIT;
	ItemModTable[INV_CRITCHANCE_INCREASE].weight = 400;
	ItemModTable[INV_CRITCHANCE_INCREASE].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_HELM | DND_MODBASE_SPECIALTY_ALL;
	
	ItemModTable[INV_CRITPERCENT_INCREASE].attrib_low = 0.01;
	ItemModTable[INV_CRITPERCENT_INCREASE].attrib_high = 0.05;
	ItemModTable[INV_CRITPERCENT_INCREASE].attrib_level_modifier = 0.05;
	ItemModTable[INV_CRITPERCENT_INCREASE].tags = INV_ATTR_TAG_CRIT;
	ItemModTable[INV_CRITPERCENT_INCREASE].weight = 600;
	ItemModTable[INV_CRITPERCENT_INCREASE].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_HELM | DND_MODBASE_SPECIALTY_ALL;
	
	ItemModTable[INV_CRITDAMAGE_INCREASE].attrib_low = 4;
	ItemModTable[INV_CRITDAMAGE_INCREASE].attrib_high = 9;
	ItemModTable[INV_CRITDAMAGE_INCREASE].attrib_level_modifier = 0;
	ItemModTable[INV_CRITDAMAGE_INCREASE].tags = INV_ATTR_TAG_CRIT;
	ItemModTable[INV_CRITDAMAGE_INCREASE].weight = 500;
	ItemModTable[INV_CRITDAMAGE_INCREASE].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_HELM | DND_MODBASE_SPECIALTY_ALL;
	
	ItemModTable[INV_KNOCKBACK_RESIST].attrib_low = 50;
	ItemModTable[INV_KNOCKBACK_RESIST].attrib_high = 500;
	ItemModTable[INV_KNOCKBACK_RESIST].attrib_level_modifier = 0;
	ItemModTable[INV_KNOCKBACK_RESIST].tags = INV_ATTR_TAG_UTILITY;
	ItemModTable[INV_KNOCKBACK_RESIST].weight = 400;
	ItemModTable[INV_KNOCKBACK_RESIST].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_BODYARMOR | DND_MODBASE_BOOT;
	
	ItemModTable[INV_DAMAGEPERCENT_MORE].attrib_low = 0.01;
	ItemModTable[INV_DAMAGEPERCENT_MORE].attrib_high = 0.025;
	ItemModTable[INV_DAMAGEPERCENT_MORE].attrib_level_modifier = 0.015;
	ItemModTable[INV_DAMAGEPERCENT_MORE].tags = INV_ATTR_TAG_DAMAGE;
	ItemModTable[INV_DAMAGEPERCENT_MORE].weight = 200;
	ItemModTable[INV_DAMAGEPERCENT_MORE].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_HELM | DND_MODBASE_SPECIALTY_TRICKSTER;
	
	ItemModTable[INV_ACCURACY_INCREASE].attrib_low = 25;
	ItemModTable[INV_ACCURACY_INCREASE].attrib_high = 124;
	ItemModTable[INV_ACCURACY_INCREASE].attrib_level_modifier = 0;
	ItemModTable[INV_ACCURACY_INCREASE].tags = INV_ATTR_TAG_ATTACK;
	ItemModTable[INV_ACCURACY_INCREASE].weight = 300;
	ItemModTable[INV_ACCURACY_INCREASE].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_HELM | DND_MODBASE_SPECIALTY_ALL;

	ItemModTable[INV_STAT_STRENGTH].attrib_low = 1;
	ItemModTable[INV_STAT_STRENGTH].attrib_high = 4;
	ItemModTable[INV_STAT_STRENGTH].attrib_level_modifier = 0;
	ItemModTable[INV_STAT_STRENGTH].tags = INV_ATTR_TAG_STAT;
	ItemModTable[INV_STAT_STRENGTH].weight = 500;
	ItemModTable[INV_STAT_STRENGTH].allowed_slots = DND_MODBASE_ALL;
	
	ItemModTable[INV_STAT_DEXTERITY].attrib_low = 1;
	ItemModTable[INV_STAT_DEXTERITY].attrib_high = 4;
	ItemModTable[INV_STAT_DEXTERITY].attrib_level_modifier = 0;
	ItemModTable[INV_STAT_DEXTERITY].tags = INV_ATTR_TAG_STAT;
	ItemModTable[INV_STAT_DEXTERITY].weight = 500;
	ItemModTable[INV_STAT_DEXTERITY].allowed_slots = DND_MODBASE_ALL;
	
	ItemModTable[INV_STAT_INTELLECT].attrib_low = 1;
	ItemModTable[INV_STAT_INTELLECT].attrib_high = 4;
	ItemModTable[INV_STAT_INTELLECT].attrib_level_modifier = 0;
	ItemModTable[INV_STAT_INTELLECT].tags = INV_ATTR_TAG_STAT;
	ItemModTable[INV_STAT_INTELLECT].weight = 500;
	ItemModTable[INV_STAT_INTELLECT].allowed_slots = DND_MODBASE_ALL;
	
	ItemModTable[INV_DMGREDUCE_ELEM].attrib_low = 1.0;
	ItemModTable[INV_DMGREDUCE_ELEM].attrib_high = 6.0;
	ItemModTable[INV_DMGREDUCE_ELEM].attrib_level_modifier = 6.0;
	ItemModTable[INV_DMGREDUCE_ELEM].tags = INV_ATTR_TAG_DEFENSE | INV_ATTR_TAG_ELEMENTAL;
	ItemModTable[INV_DMGREDUCE_ELEM].weight = 650;
	ItemModTable[INV_DMGREDUCE_ELEM].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;
	
	ItemModTable[INV_DMGREDUCE_PHYS].attrib_low = 1.0;
	ItemModTable[INV_DMGREDUCE_PHYS].attrib_high = 6.0;
	ItemModTable[INV_DMGREDUCE_PHYS].attrib_level_modifier = 6.0;
	ItemModTable[INV_DMGREDUCE_PHYS].tags = INV_ATTR_TAG_DEFENSE | INV_ATTR_TAG_PHYSICAL;
	ItemModTable[INV_DMGREDUCE_PHYS].weight = 650;
	ItemModTable[INV_DMGREDUCE_PHYS].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;
	
	ItemModTable[INV_DMGREDUCE_REFL].attrib_low = 1.0;
	ItemModTable[INV_DMGREDUCE_REFL].attrib_high = 6.0;
	ItemModTable[INV_DMGREDUCE_REFL].attrib_level_modifier = 6.0;
	ItemModTable[INV_DMGREDUCE_REFL].tags = INV_ATTR_TAG_DEFENSE;
	ItemModTable[INV_DMGREDUCE_REFL].weight = 400;
	ItemModTable[INV_DMGREDUCE_REFL].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;

	ItemModTable[INV_PEN_PHYSICAL].attrib_low = 1;
	ItemModTable[INV_PEN_PHYSICAL].attrib_high = 4;
	ItemModTable[INV_PEN_PHYSICAL].attrib_level_modifier = 0;
	ItemModTable[INV_PEN_PHYSICAL].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_PHYSICAL;
	ItemModTable[INV_PEN_PHYSICAL].weight = 750;
	ItemModTable[INV_PEN_PHYSICAL].allowed_slots = DND_MODBASE_PHYSICALATK;
	
	ItemModTable[INV_PEN_ENERGY].attrib_low = 1;
	ItemModTable[INV_PEN_ENERGY].attrib_high = 4;
	ItemModTable[INV_PEN_ENERGY].attrib_level_modifier = 0;
	ItemModTable[INV_PEN_ENERGY].tags = INV_ATTR_TAG_ATTACK	| INV_ATTR_TAG_ENERGY;
	ItemModTable[INV_PEN_ENERGY].weight = 750;
	ItemModTable[INV_PEN_ENERGY].allowed_slots = DND_MODBASE_ENERGYATK;
	
	ItemModTable[INV_CHANCE_IGNORERADIUSIMMUNITY].attrib_low = 1;
	ItemModTable[INV_CHANCE_IGNORERADIUSIMMUNITY].attrib_high = 5;
	ItemModTable[INV_CHANCE_IGNORERADIUSIMMUNITY].attrib_level_modifier = 0;
	ItemModTable[INV_CHANCE_IGNORERADIUSIMMUNITY].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_EXPLOSIVE;
	ItemModTable[INV_CHANCE_IGNORERADIUSIMMUNITY].weight = 300;
	ItemModTable[INV_CHANCE_IGNORERADIUSIMMUNITY].allowed_slots = DND_MODBASE_RADIUSATK;
	
	ItemModTable[INV_PEN_OCCULT].attrib_low = 1;
	ItemModTable[INV_PEN_OCCULT].attrib_high = 4;
	ItemModTable[INV_PEN_OCCULT].attrib_level_modifier = 0;
	ItemModTable[INV_PEN_OCCULT].tags = INV_ATTR_TAG_ATTACK	| INV_ATTR_TAG_OCCULT;
	ItemModTable[INV_PEN_OCCULT].weight = 750;
	ItemModTable[INV_PEN_OCCULT].allowed_slots = DND_MODBASE_MAGICALATK;
	
	ItemModTable[INV_PEN_ELEMENTAL].attrib_low = 1;
	ItemModTable[INV_PEN_ELEMENTAL].attrib_high = 3;
	ItemModTable[INV_PEN_ELEMENTAL].attrib_level_modifier = 0;
	ItemModTable[INV_PEN_ELEMENTAL].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_ELEMENTAL;
	ItemModTable[INV_PEN_ELEMENTAL].weight = 750;
	ItemModTable[INV_PEN_ELEMENTAL].allowed_slots = DND_MODBASE_ELEMATK;

	ItemModTable[INV_FLAT_FIREDMG].attrib_low = 1;
	ItemModTable[INV_FLAT_FIREDMG].attrib_high = 4;
	ItemModTable[INV_FLAT_FIREDMG].attrib_level_modifier = 0;
	ItemModTable[INV_FLAT_FIREDMG].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_FIRE;
	ItemModTable[INV_FLAT_FIREDMG].weight = 600;
	ItemModTable[INV_FLAT_FIREDMG].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_FLAT_ICEDMG].attrib_low = 1;
	ItemModTable[INV_FLAT_ICEDMG].attrib_high = 4;
	ItemModTable[INV_FLAT_ICEDMG].attrib_level_modifier = 0;
	ItemModTable[INV_FLAT_ICEDMG].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_ICE;
	ItemModTable[INV_FLAT_ICEDMG].weight = 600;
	ItemModTable[INV_FLAT_ICEDMG].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_FLAT_LIGHTNINGDMG].attrib_low = 1;
	ItemModTable[INV_FLAT_LIGHTNINGDMG].attrib_high = 4;
	ItemModTable[INV_FLAT_LIGHTNINGDMG].attrib_level_modifier = 0;
	ItemModTable[INV_FLAT_LIGHTNINGDMG].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_LIGHTNING;
	ItemModTable[INV_FLAT_LIGHTNINGDMG].weight = 600;
	ItemModTable[INV_FLAT_LIGHTNINGDMG].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_FLAT_POISONDMG].attrib_low = 1;
	ItemModTable[INV_FLAT_POISONDMG].attrib_high = 4;
	ItemModTable[INV_FLAT_POISONDMG].attrib_level_modifier = 0;
	ItemModTable[INV_FLAT_POISONDMG].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_POISON;
	ItemModTable[INV_FLAT_POISONDMG].weight = 600;
	ItemModTable[INV_FLAT_POISONDMG].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_LIFESTEAL].attrib_low = 0.125;
	ItemModTable[INV_LIFESTEAL].attrib_high = 0.5;
	ItemModTable[INV_LIFESTEAL].attrib_level_modifier = 0.375;
	ItemModTable[INV_LIFESTEAL].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_LIFE;
	ItemModTable[INV_LIFESTEAL].weight = 400;
	ItemModTable[INV_LIFESTEAL].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_SPECIALTY_PUNISHER;
	
	ItemModTable[INV_POISON_TICRATE].attrib_low = 5;
	ItemModTable[INV_POISON_TICRATE].attrib_high = 9;
	ItemModTable[INV_POISON_TICRATE].attrib_level_modifier = 0;
	ItemModTable[INV_POISON_TICRATE].tags = INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_POISON;
	ItemModTable[INV_POISON_TICRATE].weight = 400;
	ItemModTable[INV_POISON_TICRATE].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_POISON_DURATION].attrib_low = 5;
	ItemModTable[INV_POISON_DURATION].attrib_high = 9;
	ItemModTable[INV_POISON_DURATION].attrib_level_modifier = 0;
	ItemModTable[INV_POISON_DURATION].tags = INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_POISON;
	ItemModTable[INV_POISON_DURATION].weight = 500;
	ItemModTable[INV_POISON_DURATION].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_POISON_TICDMG].attrib_low = 1;
	ItemModTable[INV_POISON_TICDMG].attrib_high = 5;
	ItemModTable[INV_POISON_TICDMG].attrib_level_modifier = 0;
	ItemModTable[INV_POISON_TICDMG].tags = INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_POISON | INV_ATTR_TAG_DAMAGE;
	ItemModTable[INV_POISON_TICDMG].weight = 300;
	ItemModTable[INV_POISON_TICDMG].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_BLOCKERS_MOREDMG].attrib_low = 0.05;
	ItemModTable[INV_BLOCKERS_MOREDMG].attrib_high = 0.19;
	ItemModTable[INV_BLOCKERS_MOREDMG].attrib_level_modifier = 0.15;
	ItemModTable[INV_BLOCKERS_MOREDMG].tags = INV_ATTR_TAG_DAMAGE;
	ItemModTable[INV_BLOCKERS_MOREDMG].weight = 200;
	ItemModTable[INV_BLOCKERS_MOREDMG].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_SPECIALTY_DOOMGUY | DND_MODBASE_SPECIALTY_MARINE | DND_MODBASE_SPECIALTY_PUNISHER;
	
	ItemModTable[INV_FREEZECHANCE].attrib_low = 5;
	ItemModTable[INV_FREEZECHANCE].attrib_high = 9;
	ItemModTable[INV_FREEZECHANCE].attrib_level_modifier = 0;
	ItemModTable[INV_FREEZECHANCE].tags = INV_ATTR_TAG_ELEMENTAL;
	ItemModTable[INV_FREEZECHANCE].weight = 400;
	ItemModTable[INV_FREEZECHANCE].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_SLOWEFFECT].attrib_low = 2;
	ItemModTable[INV_SLOWEFFECT].attrib_high = 6;
	ItemModTable[INV_SLOWEFFECT].attrib_level_modifier = 0;
	ItemModTable[INV_SLOWEFFECT].tags = INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_ICE;
	ItemModTable[INV_SLOWEFFECT].weight = 500;
	ItemModTable[INV_SLOWEFFECT].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_CHILLTHRESHOLD].attrib_low = 1;
	ItemModTable[INV_CHILLTHRESHOLD].attrib_high = 4;
	ItemModTable[INV_CHILLTHRESHOLD].attrib_level_modifier = 0;
	ItemModTable[INV_CHILLTHRESHOLD].tags = INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_ICE;
	ItemModTable[INV_CHILLTHRESHOLD].weight = 400;
	ItemModTable[INV_CHILLTHRESHOLD].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_IGNITECHANCE].attrib_low = 5;
	ItemModTable[INV_IGNITECHANCE].attrib_high = 14;
	ItemModTable[INV_IGNITECHANCE].attrib_level_modifier = 0;
	ItemModTable[INV_IGNITECHANCE].tags = INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_FIRE;
	ItemModTable[INV_IGNITECHANCE].weight = 500;
	ItemModTable[INV_IGNITECHANCE].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_IGNITEDMG].attrib_low = 5;
	ItemModTable[INV_IGNITEDMG].attrib_high = 14;
	ItemModTable[INV_IGNITEDMG].attrib_level_modifier = 0;
	ItemModTable[INV_IGNITEDMG].tags = INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_FIRE | INV_ATTR_TAG_DAMAGE;
	ItemModTable[INV_IGNITEDMG].weight = 600;
	ItemModTable[INV_IGNITEDMG].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_IGNITEDURATION].attrib_low = 4;
	ItemModTable[INV_IGNITEDURATION].attrib_high = 12;
	ItemModTable[INV_IGNITEDURATION].attrib_level_modifier = 0;
	ItemModTable[INV_IGNITEDURATION].tags = INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_FIRE;
	ItemModTable[INV_IGNITEDURATION].weight = 400;
	ItemModTable[INV_IGNITEDURATION].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_OVERLOADCHANCE].attrib_low = 5;
	ItemModTable[INV_OVERLOADCHANCE].attrib_high = 14;
	ItemModTable[INV_OVERLOADCHANCE].attrib_level_modifier = 0;
	ItemModTable[INV_OVERLOADCHANCE].tags = INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_LIGHTNING;
	ItemModTable[INV_OVERLOADCHANCE].weight = 400;
	ItemModTable[INV_OVERLOADCHANCE].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_OVERLOAD_ZAPCOUNT].attrib_low = 1;
	ItemModTable[INV_OVERLOAD_ZAPCOUNT].attrib_high = 1;
	ItemModTable[INV_OVERLOAD_ZAPCOUNT].attrib_level_modifier = 1;
	ItemModTable[INV_OVERLOAD_ZAPCOUNT].tags = INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_LIGHTNING;
	ItemModTable[INV_OVERLOAD_ZAPCOUNT].weight = 300;
	ItemModTable[INV_OVERLOAD_ZAPCOUNT].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_OVERLOAD_DMGINCREASE].attrib_low = 0.01;
	ItemModTable[INV_OVERLOAD_DMGINCREASE].attrib_high = 0.04;
	ItemModTable[INV_OVERLOAD_DMGINCREASE].attrib_level_modifier = 0.04;
	ItemModTable[INV_OVERLOAD_DMGINCREASE].tags = INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_LIGHTNING | INV_ATTR_TAG_DAMAGE;
	ItemModTable[INV_OVERLOAD_DMGINCREASE].weight = 250;
	ItemModTable[INV_OVERLOAD_DMGINCREASE].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_CYBERNETIC].attrib_low = 1;
	ItemModTable[INV_CYBERNETIC].attrib_high = 1;
	ItemModTable[INV_CYBERNETIC].attrib_level_modifier = 1;
	ItemModTable[INV_CYBERNETIC].tags = INV_ATTR_TAG_UTILITY;
	ItemModTable[INV_CYBERNETIC].weight = 125;
	ItemModTable[INV_CYBERNETIC].allowed_slots = DND_MODBASE_ALL;
	
	ItemModTable[INV_MELEERANGE].attrib_low = 5;
	ItemModTable[INV_MELEERANGE].attrib_high = 10;
	ItemModTable[INV_MELEERANGE].attrib_level_modifier = 0;
	ItemModTable[INV_MELEERANGE].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_MELEE;
	ItemModTable[INV_MELEERANGE].weight = 300;
	ItemModTable[INV_MELEERANGE].allowed_slots = DND_MODBASE_MELEE;
	
	ItemModTable[INV_MELEEDAMAGE].attrib_low = 5;
	ItemModTable[INV_MELEEDAMAGE].attrib_high = 15;
	ItemModTable[INV_MELEEDAMAGE].attrib_level_modifier = 0;
	ItemModTable[INV_MELEEDAMAGE].tags = INV_ATTR_TAG_DAMAGE | INV_ATTR_TAG_MELEE;
	ItemModTable[INV_MELEEDAMAGE].weight = 750;
	ItemModTable[INV_MELEEDAMAGE].allowed_slots = DND_MODBASE_MELEE;
	
	ItemModTable[INV_DOTMULTI].attrib_low = 1;
	ItemModTable[INV_DOTMULTI].attrib_high = 5;
	ItemModTable[INV_DOTMULTI].attrib_level_modifier = 0;
	ItemModTable[INV_DOTMULTI].tags = INV_ATTR_TAG_DAMAGE;
	ItemModTable[INV_DOTMULTI].weight = 350;
	ItemModTable[INV_DOTMULTI].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_SPECIALTY_ALL;
	
	ItemModTable[INV_INCREASEDDOT].attrib_low = 5;
	ItemModTable[INV_INCREASEDDOT].attrib_high = 15;
	ItemModTable[INV_INCREASEDDOT].attrib_level_modifier = 0;
	ItemModTable[INV_INCREASEDDOT].tags = INV_ATTR_TAG_DAMAGE;
	ItemModTable[INV_INCREASEDDOT].weight = 600;
	ItemModTable[INV_INCREASEDDOT].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_SPECIALTY_ALL;
	
	ItemModTable[INV_PROJSPEED].attrib_low = 0.01;
	ItemModTable[INV_PROJSPEED].attrib_high = 0.03;
	ItemModTable[INV_PROJSPEED].attrib_level_modifier = 0;
	ItemModTable[INV_PROJSPEED].tags = INV_ATTR_TAG_UTILITY | INV_ATTR_TAG_ATTACK;
	ItemModTable[INV_PROJSPEED].weight = 350;
	ItemModTable[INV_PROJSPEED].allowed_slots = DND_MODBASE_CHARM;
	
	ItemModTable[INV_DMGREDUCE_ENERGY].attrib_low = 1.0;
	ItemModTable[INV_DMGREDUCE_ENERGY].attrib_high = 6.0;
	ItemModTable[INV_DMGREDUCE_ENERGY].attrib_level_modifier = 6.0;
	ItemModTable[INV_DMGREDUCE_ENERGY].tags = INV_ATTR_TAG_DEFENSE | INV_ATTR_TAG_ENERGY;
	ItemModTable[INV_DMGREDUCE_ENERGY].weight = 650;
	ItemModTable[INV_DMGREDUCE_ENERGY].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;
	
	ItemModTable[INV_PERCENT_KNOCKBACKRESIST].attrib_low = 1;
	ItemModTable[INV_PERCENT_KNOCKBACKRESIST].attrib_high = 10;
	ItemModTable[INV_PERCENT_KNOCKBACKRESIST].attrib_level_modifier = 0;
	ItemModTable[INV_PERCENT_KNOCKBACKRESIST].tags = INV_ATTR_TAG_UTILITY;
	ItemModTable[INV_PERCENT_KNOCKBACKRESIST].weight = 300;
	ItemModTable[INV_PERCENT_KNOCKBACKRESIST].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_BODYARMOR | DND_MODBASE_BOOT;
	
	ItemModTable[INV_DMGREDUCE_MAGIC].attrib_low = 1.0;
	ItemModTable[INV_DMGREDUCE_MAGIC].attrib_high = 6.0;
	ItemModTable[INV_DMGREDUCE_MAGIC].attrib_level_modifier = 6.0;
	ItemModTable[INV_DMGREDUCE_MAGIC].tags = INV_ATTR_TAG_DEFENSE | INV_ATTR_TAG_OCCULT;
	ItemModTable[INV_DMGREDUCE_MAGIC].weight = 650;
	ItemModTable[INV_DMGREDUCE_MAGIC].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;
	
	ItemModTable[INV_DOTMULTI_FIRE].attrib_low = 4;
	ItemModTable[INV_DOTMULTI_FIRE].attrib_high = 9;
	ItemModTable[INV_DOTMULTI_FIRE].attrib_level_modifier = 0;
	ItemModTable[INV_DOTMULTI_FIRE].tags = INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_FIRE | INV_ATTR_TAG_DAMAGE;
	ItemModTable[INV_DOTMULTI_FIRE].weight = 500;
	ItemModTable[INV_DOTMULTI_FIRE].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_DOTMULTI_POISON].attrib_low = 4;
	ItemModTable[INV_DOTMULTI_POISON].attrib_high = 9;
	ItemModTable[INV_DOTMULTI_POISON].attrib_level_modifier = 0;
	ItemModTable[INV_DOTMULTI_POISON].tags = INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_POISON | INV_ATTR_TAG_DAMAGE;
	ItemModTable[INV_DOTMULTI_POISON].weight = 500;
	ItemModTable[INV_DOTMULTI_FIRE].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_DOTMULTI_BLEED].attrib_low = 4;
	ItemModTable[INV_DOTMULTI_BLEED].attrib_high = 9;
	ItemModTable[INV_DOTMULTI_BLEED].attrib_level_modifier = 0;
	ItemModTable[INV_DOTMULTI_BLEED].tags = INV_ATTR_TAG_PHYSICAL | INV_ATTR_TAG_DAMAGE;
	ItemModTable[INV_DOTMULTI_BLEED].weight = 500;
	ItemModTable[INV_DOTMULTI_BLEED].allowed_slots = DND_MODBASE_PHYSICALATK;
	
	ItemModTable[INV_CHARGEDURATION].attrib_low = 5;
	ItemModTable[INV_CHARGEDURATION].attrib_high = 10;
	ItemModTable[INV_CHARGEDURATION].attrib_level_modifier = 0;
	ItemModTable[INV_CHARGEDURATION].tags = INV_ATTR_TAG_UTILITY;
	ItemModTable[INV_CHARGEDURATION].weight = 400;
	ItemModTable[INV_CHARGEDURATION].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_SPECIALTY_ALL;
	
	ItemModTable[INV_ADDEDMAXRESIST].attrib_low = 0.25;
	ItemModTable[INV_ADDEDMAXRESIST].attrib_high = 0.5;
	ItemModTable[INV_ADDEDMAXRESIST].attrib_level_modifier = 0.26;
	ItemModTable[INV_ADDEDMAXRESIST].tags = INV_ATTR_TAG_DEFENSE;
	ItemModTable[INV_ADDEDMAXRESIST].weight = 300;
	ItemModTable[INV_ADDEDMAXRESIST].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;
	
	ItemModTable[INV_REGENRATE].attrib_low = 5;
	ItemModTable[INV_REGENRATE].attrib_high = 10;
	ItemModTable[INV_REGENRATE].attrib_level_modifier = 0;
	ItemModTable[INV_REGENRATE].tags = INV_ATTR_TAG_UTILITY | INV_ATTR_TAG_LIFE;
	ItemModTable[INV_REGENRATE].weight = 400;
	ItemModTable[INV_REGENRATE].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;
	
	ItemModTable[INV_LIFESTEAL_RATE].attrib_low = 4;
	ItemModTable[INV_LIFESTEAL_RATE].attrib_high = 8;
	ItemModTable[INV_LIFESTEAL_RATE].attrib_level_modifier = 0;
	ItemModTable[INV_LIFESTEAL_RATE].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_LIFE;
	ItemModTable[INV_LIFESTEAL_RATE].weight = 400;
	ItemModTable[INV_LIFESTEAL_RATE].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_SPECIALTY_PUNISHER;
	
	ItemModTable[INV_LIFESTEAL_RECOVERY].attrib_low = 5;
	ItemModTable[INV_LIFESTEAL_RECOVERY].attrib_high = 10;
	ItemModTable[INV_LIFESTEAL_RECOVERY].attrib_level_modifier = 0;
	ItemModTable[INV_LIFESTEAL_RECOVERY].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_LIFE;
	ItemModTable[INV_LIFESTEAL_RECOVERY].weight = 400;
	ItemModTable[INV_LIFESTEAL_RECOVERY].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_SPECIALTY_PUNISHER;
	
	ItemModTable[INV_LIFESTEAL_CAP].attrib_low = 5;
	ItemModTable[INV_LIFESTEAL_CAP].attrib_high = 10;
	ItemModTable[INV_LIFESTEAL_CAP].attrib_level_modifier = 0;
	ItemModTable[INV_LIFESTEAL_CAP].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_LIFE;
	ItemModTable[INV_LIFESTEAL_CAP].weight = 350;
	ItemModTable[INV_LIFESTEAL_CAP].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_SPECIALTY_PUNISHER;
	
	ItemModTable[INV_LIFESTEAL_DAMAGE].attrib_low = 0.01;
	ItemModTable[INV_LIFESTEAL_DAMAGE].attrib_high = 0.03;
	ItemModTable[INV_LIFESTEAL_DAMAGE].attrib_level_modifier = 0.025;
	ItemModTable[INV_LIFESTEAL_DAMAGE].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_LIFE;
	ItemModTable[INV_LIFESTEAL_DAMAGE].weight = 350;
	ItemModTable[INV_LIFESTEAL_DAMAGE].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_SPECIALTY_PUNISHER;
	
	ItemModTable[INV_OVERLOAD_DURATION].attrib_low = 0.1;
	ItemModTable[INV_OVERLOAD_DURATION].attrib_high = 0.5;
	ItemModTable[INV_OVERLOAD_DURATION].attrib_level_modifier = 0.5;
	ItemModTable[INV_OVERLOAD_DURATION].tags = INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_LIGHTNING;
	ItemModTable[INV_OVERLOAD_DURATION].weight = 400;
	ItemModTable[INV_OVERLOAD_DURATION].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_IGNITE_PROLIFCHANCE].attrib_low = 5;
	ItemModTable[INV_IGNITE_PROLIFCHANCE].attrib_high = 14;
	ItemModTable[INV_IGNITE_PROLIFCHANCE].attrib_level_modifier = 0;
	ItemModTable[INV_IGNITE_PROLIFCHANCE].tags = INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_FIRE;
	ItemModTable[INV_IGNITE_PROLIFCHANCE].weight = 300;
	ItemModTable[INV_IGNITE_PROLIFCHANCE].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_IGNITE_PROLIFCOUNT].attrib_low = 1;
	ItemModTable[INV_IGNITE_PROLIFCOUNT].attrib_high = 1;
	ItemModTable[INV_IGNITE_PROLIFCOUNT].attrib_level_modifier = 1;
	ItemModTable[INV_IGNITE_PROLIFCOUNT].tags = INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_FIRE;
	ItemModTable[INV_IGNITE_PROLIFCOUNT].weight = 400;
	ItemModTable[INV_IGNITE_PROLIFCOUNT].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_IGNITE_PROLIFRANGE].attrib_low = 0.05;
	ItemModTable[INV_IGNITE_PROLIFRANGE].attrib_high = 0.14;
	ItemModTable[INV_IGNITE_PROLIFRANGE].attrib_level_modifier = 0.10;
	ItemModTable[INV_IGNITE_PROLIFRANGE].tags = INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_FIRE;
	ItemModTable[INV_IGNITE_PROLIFRANGE].weight = 400;
	ItemModTable[INV_IGNITE_PROLIFRANGE].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_CHANCE_AILMENTIGNORE].attrib_low = 5;
	ItemModTable[INV_CHANCE_AILMENTIGNORE].attrib_high = 9;
	ItemModTable[INV_CHANCE_AILMENTIGNORE].attrib_level_modifier = 0;
	ItemModTable[INV_CHANCE_AILMENTIGNORE].tags = INV_ATTR_TAG_ELEMENTAL;
	ItemModTable[INV_CHANCE_AILMENTIGNORE].weight = 200;
	ItemModTable[INV_CHANCE_AILMENTIGNORE].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_SPECIALTY_ALL;
	
	ItemModTable[INV_CHANCE_FLATIGNITE].attrib_low = 1;
	ItemModTable[INV_CHANCE_FLATIGNITE].attrib_high = 2;
	ItemModTable[INV_CHANCE_FLATIGNITE].attrib_level_modifier = 0;
	ItemModTable[INV_CHANCE_FLATIGNITE].tags = INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_FIRE;
	ItemModTable[INV_CHANCE_FLATIGNITE].weight = 400;
	ItemModTable[INV_CHANCE_FLATIGNITE].allowed_slots = DND_MODBASE_ELEMATK;
	
	ItemModTable[INV_CHANCE_FLATPROLIF].attrib_low = 1;
	ItemModTable[INV_CHANCE_FLATPROLIF].attrib_high = 2;
	ItemModTable[INV_CHANCE_FLATPROLIF].attrib_level_modifier = 0;
	ItemModTable[INV_CHANCE_FLATPROLIF].tags = INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_FIRE;
	ItemModTable[INV_CHANCE_FLATPROLIF].weight = 300;
	ItemModTable[INV_CHANCE_FLATPROLIF].allowed_slots = DND_MODBASE_ELEMATK;

	ItemModTable[INV_SHIELD_INCREASE].attrib_low = 1;
	ItemModTable[INV_SHIELD_INCREASE].attrib_high = 4;
	ItemModTable[INV_SHIELD_INCREASE].attrib_level_modifier = 0;
	ItemModTable[INV_SHIELD_INCREASE].tags = INV_ATTR_TAG_DEFENSE | INV_ATTR_TAG_ENERGY;
	ItemModTable[INV_SHIELD_INCREASE].weight = 650;
	ItemModTable[INV_SHIELD_INCREASE].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;

	ItemModTable[INV_PERCENTSHIELD_INCREASE].attrib_low = 1;
	ItemModTable[INV_PERCENTSHIELD_INCREASE].attrib_high = 9;
	ItemModTable[INV_PERCENTSHIELD_INCREASE].attrib_level_modifier = 0;
	ItemModTable[INV_PERCENTSHIELD_INCREASE].tags = INV_ATTR_TAG_DEFENSE | INV_ATTR_TAG_ENERGY;
	ItemModTable[INV_PERCENTSHIELD_INCREASE].weight = 650;
	ItemModTable[INV_PERCENTSHIELD_INCREASE].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;

	ItemModTable[INV_SHIELD_RECOVERYRATE].attrib_low = 5;
	ItemModTable[INV_SHIELD_RECOVERYRATE].attrib_high = 9;
	ItemModTable[INV_SHIELD_RECOVERYRATE].attrib_level_modifier = 0;
	ItemModTable[INV_SHIELD_RECOVERYRATE].tags = INV_ATTR_TAG_DEFENSE | INV_ATTR_TAG_ENERGY;
	ItemModTable[INV_SHIELD_RECOVERYRATE].weight = 500;
	ItemModTable[INV_SHIELD_RECOVERYRATE].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;

	ItemModTable[INV_SHIELD_RECHARGEDELAY].attrib_low = 5;
	ItemModTable[INV_SHIELD_RECHARGEDELAY].attrib_high = 10;
	ItemModTable[INV_SHIELD_RECHARGEDELAY].attrib_level_modifier = 0;
	ItemModTable[INV_SHIELD_RECHARGEDELAY].tags = INV_ATTR_TAG_DEFENSE | INV_ATTR_TAG_ENERGY;
	ItemModTable[INV_SHIELD_RECHARGEDELAY].weight = 450;
	ItemModTable[INV_SHIELD_RECHARGEDELAY].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;

	ItemModTable[INV_MIT_INCREASE].attrib_low = 0.5;
	ItemModTable[INV_MIT_INCREASE].attrib_high = 1.25;
	ItemModTable[INV_MIT_INCREASE].attrib_level_modifier = 1.5;
	ItemModTable[INV_MIT_INCREASE].tags = INV_ATTR_TAG_DEFENSE;
	ItemModTable[INV_MIT_INCREASE].weight = 750;
	ItemModTable[INV_MIT_INCREASE].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;

	ItemModTable[INV_MITEFFECT_INCREASE].attrib_low = 0.3;
	ItemModTable[INV_MITEFFECT_INCREASE].attrib_high = 0.875;
	ItemModTable[INV_MITEFFECT_INCREASE].attrib_level_modifier = 0.575;
	ItemModTable[INV_MITEFFECT_INCREASE].tags = INV_ATTR_TAG_DEFENSE;
	ItemModTable[INV_MITEFFECT_INCREASE].weight = 400;
	ItemModTable[INV_MITEFFECT_INCREASE].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;

	ItemModTable[INV_PERCENTFIRE_DAMAGE].attrib_low = 5;
	ItemModTable[INV_PERCENTFIRE_DAMAGE].attrib_high = 15;
	ItemModTable[INV_PERCENTFIRE_DAMAGE].attrib_level_modifier = 0;
	ItemModTable[INV_PERCENTFIRE_DAMAGE].tags = INV_ATTR_TAG_DAMAGE | INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_FIRE;
	ItemModTable[INV_PERCENTFIRE_DAMAGE].weight = 750;
	ItemModTable[INV_PERCENTFIRE_DAMAGE].allowed_slots = DND_MODBASE_ELEMATK;

	ItemModTable[INV_PERCENTICE_DAMAGE].attrib_low = 5;
	ItemModTable[INV_PERCENTICE_DAMAGE].attrib_high = 15;
	ItemModTable[INV_PERCENTICE_DAMAGE].attrib_level_modifier = 0;
	ItemModTable[INV_PERCENTICE_DAMAGE].tags = INV_ATTR_TAG_DAMAGE | INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_ICE;
	ItemModTable[INV_PERCENTICE_DAMAGE].weight = 750;
	ItemModTable[INV_PERCENTICE_DAMAGE].allowed_slots = DND_MODBASE_ELEMATK;

	ItemModTable[INV_PERCENTPOISON_DAMAGE].attrib_low = 5;
	ItemModTable[INV_PERCENTPOISON_DAMAGE].attrib_high = 15;
	ItemModTable[INV_PERCENTPOISON_DAMAGE].attrib_level_modifier = 0;
	ItemModTable[INV_PERCENTPOISON_DAMAGE].tags = INV_ATTR_TAG_DAMAGE | INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_POISON;
	ItemModTable[INV_PERCENTPOISON_DAMAGE].weight = 750;
	ItemModTable[INV_PERCENTPOISON_DAMAGE].allowed_slots = DND_MODBASE_ELEMATK;

	ItemModTable[INV_PERCENTLIGHTNING_DAMAGE].attrib_low = 5;
	ItemModTable[INV_PERCENTLIGHTNING_DAMAGE].attrib_high = 15;
	ItemModTable[INV_PERCENTLIGHTNING_DAMAGE].attrib_level_modifier = 0;
	ItemModTable[INV_PERCENTLIGHTNING_DAMAGE].tags = INV_ATTR_TAG_DAMAGE | INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_LIGHTNING;
	ItemModTable[INV_PERCENTLIGHTNING_DAMAGE].weight = 750;
	ItemModTable[INV_PERCENTLIGHTNING_DAMAGE].allowed_slots = DND_MODBASE_ELEMATK;

	ItemModTable[INV_PEN_FIRE].attrib_low = 1;
	ItemModTable[INV_PEN_FIRE].attrib_high = 4;
	ItemModTable[INV_PEN_FIRE].attrib_level_modifier = 0;
	ItemModTable[INV_PEN_FIRE].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_FIRE;
	ItemModTable[INV_PEN_FIRE].weight = 650;
	ItemModTable[INV_PEN_FIRE].allowed_slots = DND_MODBASE_ELEMATK;

	ItemModTable[INV_PEN_ICE].attrib_low = 1;
	ItemModTable[INV_PEN_ICE].attrib_high = 4;
	ItemModTable[INV_PEN_ICE].attrib_level_modifier = 0;
	ItemModTable[INV_PEN_ICE].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_ICE;
	ItemModTable[INV_PEN_ICE].weight = 650;
	ItemModTable[INV_PEN_ICE].allowed_slots = DND_MODBASE_ELEMATK;

	ItemModTable[INV_PEN_LIGHTNING].attrib_low = 1;
	ItemModTable[INV_PEN_LIGHTNING].attrib_high = 4;
	ItemModTable[INV_PEN_LIGHTNING].attrib_level_modifier = 0;
	ItemModTable[INV_PEN_LIGHTNING].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_LIGHTNING;
	ItemModTable[INV_PEN_LIGHTNING].weight = 650;
	ItemModTable[INV_PEN_LIGHTNING].allowed_slots = DND_MODBASE_ELEMATK;

	ItemModTable[INV_PEN_POISON].attrib_low = 1;
	ItemModTable[INV_PEN_POISON].attrib_high = 4;
	ItemModTable[INV_PEN_POISON].attrib_level_modifier = 0;
	ItemModTable[INV_PEN_POISON].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_POISON;
	ItemModTable[INV_PEN_POISON].weight = 650;
	ItemModTable[INV_PEN_POISON].allowed_slots = DND_MODBASE_ELEMATK;

	ItemModTable[INV_MAGIC_NEGATION].attrib_low = 1;
	ItemModTable[INV_MAGIC_NEGATION].attrib_high = 5;
	ItemModTable[INV_MAGIC_NEGATION].attrib_level_modifier = 0;
	ItemModTable[INV_MAGIC_NEGATION].tags = INV_ATTR_TAG_DEFENSE | INV_ATTR_TAG_OCCULT;
	ItemModTable[INV_MAGIC_NEGATION].weight = 500;
	ItemModTable[INV_MAGIC_NEGATION].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;

	ItemModTable[INV_FLAT_TECH].attrib_low = 1;
	ItemModTable[INV_FLAT_TECH].attrib_high = 3;
	ItemModTable[INV_FLAT_TECH].attrib_level_modifier = 0;
	ItemModTable[INV_FLAT_TECH].tags = INV_ATTR_TAG_ATTACK;
	ItemModTable[INV_FLAT_TECH].weight = 600;
	ItemModTable[INV_FLAT_TECH].allowed_slots = DND_MODBASE_WEAPONATK;

	ItemModTable[INV_FLAT_PRECISION].attrib_low = 1;
	ItemModTable[INV_FLAT_PRECISION].attrib_high = 3;
	ItemModTable[INV_FLAT_PRECISION].attrib_level_modifier = 0;
	ItemModTable[INV_FLAT_PRECISION].tags = INV_ATTR_TAG_ATTACK;
	ItemModTable[INV_FLAT_PRECISION].weight = 600;
	ItemModTable[INV_FLAT_PRECISION].allowed_slots = DND_MODBASE_WEAPONATK;

	ItemModTable[INV_TECH_PERCENT].attrib_low = 3;
	ItemModTable[INV_TECH_PERCENT].attrib_high = 12;
	ItemModTable[INV_TECH_PERCENT].attrib_level_modifier = 0;
	ItemModTable[INV_TECH_PERCENT].tags = INV_ATTR_TAG_DAMAGE;
	ItemModTable[INV_TECH_PERCENT].weight = 600;
	ItemModTable[INV_TECH_PERCENT].allowed_slots = DND_MODBASE_WEAPONATK;

	ItemModTable[INV_FLAT_MAGIC].attrib_low = 1;
	ItemModTable[INV_FLAT_MAGIC].attrib_high = 3;
	ItemModTable[INV_FLAT_MAGIC].attrib_level_modifier = 0;
	ItemModTable[INV_FLAT_MAGIC].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_OCCULT;
	ItemModTable[INV_FLAT_MAGIC].weight = 600;
	ItemModTable[INV_FLAT_MAGIC].allowed_slots = DND_MODBASE_MAGICALATK;

	ItemModTable[INV_MAGIC_PERCENT].attrib_low = 3;
	ItemModTable[INV_MAGIC_PERCENT].attrib_high = 12;
	ItemModTable[INV_MAGIC_PERCENT].attrib_level_modifier = 0;
	ItemModTable[INV_MAGIC_PERCENT].tags = INV_ATTR_TAG_DAMAGE | INV_ATTR_TAG_OCCULT;
	ItemModTable[INV_MAGIC_PERCENT].weight = 600;
	ItemModTable[INV_MAGIC_PERCENT].allowed_slots = DND_MODBASE_MAGICALATK;

	ItemModTable[INV_REDUCED_OVERHEAT].attrib_low = 1;
	ItemModTable[INV_REDUCED_OVERHEAT].attrib_high = 4;
	ItemModTable[INV_REDUCED_OVERHEAT].attrib_level_modifier = 0;
	ItemModTable[INV_REDUCED_OVERHEAT].tags = INV_ATTR_TAG_UTILITY;
	ItemModTable[INV_REDUCED_OVERHEAT].weight = 400;
	ItemModTable[INV_REDUCED_OVERHEAT].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_SPECIALTY_DOOMGUY | DND_MODBASE_SPECIALTY_CYBORG;

	ItemModTable[INV_DMGREDUCE_ALL].attrib_low = 1.0;
	ItemModTable[INV_DMGREDUCE_ALL].attrib_high = 2.0;
	ItemModTable[INV_DMGREDUCE_ALL].attrib_level_modifier = 1.0;
	ItemModTable[INV_DMGREDUCE_ALL].tags = INV_ATTR_TAG_DEFENSE;
	ItemModTable[INV_DMGREDUCE_ALL].weight = 300;
	ItemModTable[INV_DMGREDUCE_ALL].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;

	ItemModTable[INV_ITEMRARITY].attrib_low = 0.015;
	ItemModTable[INV_ITEMRARITY].attrib_high = 0.035;
	ItemModTable[INV_ITEMRARITY].attrib_level_modifier = 0;
	ItemModTable[INV_ITEMRARITY].tags = INV_ATTR_TAG_UTILITY;
	ItemModTable[INV_ITEMRARITY].weight = 250;
	ItemModTable[INV_ITEMRARITY].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_SPECIALTY_ALL;

	ItemModTable[INV_RIPCOUNT].attrib_low = 5;
	ItemModTable[INV_RIPCOUNT].attrib_high = 15;
	ItemModTable[INV_RIPCOUNT].attrib_level_modifier = 0;
	ItemModTable[INV_RIPCOUNT].tags = INV_ATTR_TAG_UTILITY | INV_ATTR_TAG_ATTACK;
	ItemModTable[INV_RIPCOUNT].weight = 400;
	ItemModTable[INV_RIPCOUNT].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_SPECIALTY_ALL;

	ItemModTable[INV_RIPDAMAGE].attrib_low = 1;
	ItemModTable[INV_RIPDAMAGE].attrib_high = 4;
	ItemModTable[INV_RIPDAMAGE].attrib_level_modifier = 0;
	ItemModTable[INV_RIPDAMAGE].tags = INV_ATTR_TAG_UTILITY | INV_ATTR_TAG_ATTACK;
	ItemModTable[INV_RIPDAMAGE].weight = 400;
	ItemModTable[INV_RIPDAMAGE].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_SPECIALTY_ALL;

	ItemModTable[INV_LOCKONAREA].attrib_low = 5;
	ItemModTable[INV_LOCKONAREA].attrib_high = 10;
	ItemModTable[INV_LOCKONAREA].attrib_level_modifier = 0;
	ItemModTable[INV_LOCKONAREA].tags = INV_ATTR_TAG_UTILITY | INV_ATTR_TAG_ATTACK;
	ItemModTable[INV_LOCKONAREA].weight = 250;
	ItemModTable[INV_LOCKONAREA].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_HELM;

	ItemModTable[INV_LOCKONRANGE].attrib_low = 5;
	ItemModTable[INV_LOCKONRANGE].attrib_high = 10;
	ItemModTable[INV_LOCKONRANGE].attrib_level_modifier = 0;
	ItemModTable[INV_LOCKONRANGE].tags = INV_ATTR_TAG_UTILITY | INV_ATTR_TAG_ATTACK;
	ItemModTable[INV_LOCKONRANGE].weight = 250;
	ItemModTable[INV_LOCKONRANGE].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_HELM;

	ItemModTable[INV_INCKILLINGSPREE].attrib_low = 5;
	ItemModTable[INV_INCKILLINGSPREE].attrib_high = 15;
	ItemModTable[INV_INCKILLINGSPREE].attrib_level_modifier = 0;
	ItemModTable[INV_INCKILLINGSPREE].tags = INV_ATTR_TAG_UTILITY;
	ItemModTable[INV_INCKILLINGSPREE].weight = 350;
	ItemModTable[INV_INCKILLINGSPREE].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_SPECIALTY_PUNISHER;

	ItemModTable[INV_REDUCEDCURSEEFFECT].attrib_low = 1;
	ItemModTable[INV_REDUCEDCURSEEFFECT].attrib_high = 3;
	ItemModTable[INV_REDUCEDCURSEEFFECT].attrib_level_modifier = 0;
	ItemModTable[INV_REDUCEDCURSEEFFECT].tags = INV_ATTR_TAG_UTILITY;
	ItemModTable[INV_REDUCEDCURSEEFFECT].weight = 350;
	ItemModTable[INV_REDUCEDCURSEEFFECT].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;

	ItemModTable[INV_REDUCEDCURSEDURATION].attrib_low = 1;
	ItemModTable[INV_REDUCEDCURSEDURATION].attrib_high = 4;
	ItemModTable[INV_REDUCEDCURSEDURATION].attrib_level_modifier = 0;
	ItemModTable[INV_REDUCEDCURSEDURATION].tags = INV_ATTR_TAG_UTILITY;
	ItemModTable[INV_REDUCEDCURSEDURATION].weight = 350;
	ItemModTable[INV_REDUCEDCURSEDURATION].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;

	ItemModTable[INV_AVOID_IGNITE].attrib_low = 1;
	ItemModTable[INV_AVOID_IGNITE].attrib_high = 6;
	ItemModTable[INV_AVOID_IGNITE].attrib_level_modifier = 0;
	ItemModTable[INV_AVOID_IGNITE].tags = INV_ATTR_TAG_FIRE | INV_ATTR_TAG_ELEMENTAL;
	ItemModTable[INV_AVOID_IGNITE].weight = 500;
	ItemModTable[INV_AVOID_IGNITE].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;

	ItemModTable[INV_AVOID_CHILLFREEZE].attrib_low = 1;
	ItemModTable[INV_AVOID_CHILLFREEZE].attrib_high = 6;
	ItemModTable[INV_AVOID_CHILLFREEZE].attrib_level_modifier = 0;
	ItemModTable[INV_AVOID_CHILLFREEZE].tags = INV_ATTR_TAG_ICE | INV_ATTR_TAG_ELEMENTAL;
	ItemModTable[INV_AVOID_CHILLFREEZE].weight = 500;
	ItemModTable[INV_AVOID_CHILLFREEZE].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;

	ItemModTable[INV_AVOID_POISON].attrib_low = 1;
	ItemModTable[INV_AVOID_POISON].attrib_high = 6;
	ItemModTable[INV_AVOID_POISON].attrib_level_modifier = 0;
	ItemModTable[INV_AVOID_POISON].tags = INV_ATTR_TAG_POISON | INV_ATTR_TAG_ELEMENTAL;
	ItemModTable[INV_AVOID_POISON].weight = 500;
	ItemModTable[INV_AVOID_POISON].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;

	ItemModTable[INV_AVOID_OVERLOAD].attrib_low = 1;
	ItemModTable[INV_AVOID_OVERLOAD].attrib_high = 6;
	ItemModTable[INV_AVOID_OVERLOAD].attrib_level_modifier = 0;
	ItemModTable[INV_AVOID_OVERLOAD].tags = INV_ATTR_TAG_LIGHTNING | INV_ATTR_TAG_ELEMENTAL;
	ItemModTable[INV_AVOID_OVERLOAD].weight = 500;
	ItemModTable[INV_AVOID_OVERLOAD].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;

	ItemModTable[INV_AVOID_ELEAILMENTS].attrib_low = 1;
	ItemModTable[INV_AVOID_ELEAILMENTS].attrib_high = 3;
	ItemModTable[INV_AVOID_ELEAILMENTS].attrib_level_modifier = 0;
	ItemModTable[INV_AVOID_ELEAILMENTS].tags = INV_ATTR_TAG_ELEMENTAL;
	ItemModTable[INV_AVOID_ELEAILMENTS].weight = 125;
	ItemModTable[INV_AVOID_ELEAILMENTS].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;

	ItemModTable[INV_AVOID_BLEED].attrib_low = 1;
	ItemModTable[INV_AVOID_BLEED].attrib_high = 6;
	ItemModTable[INV_AVOID_BLEED].attrib_level_modifier = 0;
	ItemModTable[INV_AVOID_BLEED].tags = INV_ATTR_TAG_PHYSICAL;
	ItemModTable[INV_AVOID_BLEED].weight = 500;
	ItemModTable[INV_AVOID_BLEED].allowed_slots = DND_MODBASE_NOTRICKSTERCLAW;
	
	ItemModTable[INV_CHANCE_BLEED].attrib_low = 1;
	ItemModTable[INV_CHANCE_BLEED].attrib_high = 9;
	ItemModTable[INV_CHANCE_BLEED].attrib_level_modifier = 0;
	ItemModTable[INV_CHANCE_BLEED].tags = INV_ATTR_TAG_PHYSICAL | INV_ATTR_TAG_ATTACK;
	ItemModTable[INV_CHANCE_BLEED].weight = 500;
	ItemModTable[INV_CHANCE_BLEED].allowed_slots = DND_MODBASE_PHYSICALATK;
	
	ItemModTable[INV_PERCENTDMG_BLEED].attrib_low = 5;
	ItemModTable[INV_PERCENTDMG_BLEED].attrib_high = 10;
	ItemModTable[INV_PERCENTDMG_BLEED].attrib_level_modifier = 0;
	ItemModTable[INV_PERCENTDMG_BLEED].tags = INV_ATTR_TAG_PHYSICAL | INV_ATTR_TAG_DAMAGE;
	ItemModTable[INV_PERCENTDMG_BLEED].weight = 600;
	ItemModTable[INV_PERCENTDMG_BLEED].allowed_slots = DND_MODBASE_PHYSICALATK;

	ItemModTable[INV_BLEED_DURATION].attrib_low = 1;
	ItemModTable[INV_BLEED_DURATION].attrib_high = 10;
	ItemModTable[INV_BLEED_DURATION].attrib_level_modifier = 0;
	ItemModTable[INV_BLEED_DURATION].tags = INV_ATTR_TAG_PHYSICAL;
	ItemModTable[INV_BLEED_DURATION].weight = 600;
	ItemModTable[INV_BLEED_DURATION].allowed_slots = DND_MODBASE_PHYSICALATK;

	ItemModTable[INV_CRITPERCENT_FORWEPTYPE].attrib_low = 0.05;
	ItemModTable[INV_CRITPERCENT_FORWEPTYPE].attrib_high = 0.1;
	ItemModTable[INV_CRITPERCENT_FORWEPTYPE].attrib_level_modifier = 0.05;
	ItemModTable[INV_CRITPERCENT_FORWEPTYPE].attrib_extra_low = DND_WEPTYPE_TECH;
	ItemModTable[INV_CRITPERCENT_FORWEPTYPE].attrib_extra_high = DND_WEPTYPE_LAST;
	ItemModTable[INV_CRITPERCENT_FORWEPTYPE].attrib_level_extra_modifier = -1;
	ItemModTable[INV_CRITPERCENT_FORWEPTYPE].tags = INV_ATTR_TAG_CRIT;
	ItemModTable[INV_CRITPERCENT_FORWEPTYPE].weight = 400;
	ItemModTable[INV_CRITPERCENT_FORWEPTYPE].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_HELM;

	ItemModTable[INV_FRENZYCHARGE_ONSHATTER].attrib_low = 1;
	ItemModTable[INV_FRENZYCHARGE_ONSHATTER].attrib_high = 4;
	ItemModTable[INV_FRENZYCHARGE_ONSHATTER].attrib_level_modifier = 0;
	ItemModTable[INV_FRENZYCHARGE_ONSHATTER].tags = INV_ATTR_TAG_UTILITY | INV_ATTR_TAG_ICE;
	ItemModTable[INV_FRENZYCHARGE_ONSHATTER].weight = 300;
	ItemModTable[INV_FRENZYCHARGE_ONSHATTER].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_SPECIALTY_ALL;

	ItemModTable[INV_ENDURANCECHARGE_ONMELEE].attrib_low = 1;
	ItemModTable[INV_ENDURANCECHARGE_ONMELEE].attrib_high = 4;
	ItemModTable[INV_ENDURANCECHARGE_ONMELEE].attrib_level_modifier = 0;
	ItemModTable[INV_ENDURANCECHARGE_ONMELEE].tags = INV_ATTR_TAG_UTILITY | INV_ATTR_TAG_MELEE;
	ItemModTable[INV_ENDURANCECHARGE_ONMELEE].weight = 300;
	ItemModTable[INV_ENDURANCECHARGE_ONMELEE].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_SPECIALTY_ALL;

	ItemModTable[INV_POWERCHARGE_ONOVERLOAD].attrib_low = 1;
	ItemModTable[INV_POWERCHARGE_ONOVERLOAD].attrib_high = 4;
	ItemModTable[INV_POWERCHARGE_ONOVERLOAD].attrib_level_modifier = 0;
	ItemModTable[INV_POWERCHARGE_ONOVERLOAD].tags = INV_ATTR_TAG_UTILITY | INV_ATTR_TAG_LIGHTNING;
	ItemModTable[INV_POWERCHARGE_ONOVERLOAD].weight = 300;
	ItemModTable[INV_POWERCHARGE_ONOVERLOAD].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_SPECIALTY_ALL;

	ItemModTable[INV_INC_STAMINA].attrib_low = 1;
	ItemModTable[INV_INC_STAMINA].attrib_high = 9;
	ItemModTable[INV_INC_STAMINA].attrib_level_modifier = 0;
	ItemModTable[INV_INC_STAMINA].tags = INV_ATTR_TAG_MELEE | INV_ATTR_TAG_STAMINA;
	ItemModTable[INV_INC_STAMINA].weight = 400;
	ItemModTable[INV_INC_STAMINA].allowed_slots = DND_MODBASE_MELEE;
	
	ItemModTable[INV_INC_STAMINARECOVERYRATE].attrib_low = 1;
	ItemModTable[INV_INC_STAMINARECOVERYRATE].attrib_high = 6;
	ItemModTable[INV_INC_STAMINARECOVERYRATE].attrib_level_modifier = 0;
	ItemModTable[INV_INC_STAMINARECOVERYRATE].tags = INV_ATTR_TAG_MELEE | INV_ATTR_TAG_STAMINA;
	ItemModTable[INV_INC_STAMINARECOVERYRATE].weight = 500;
	ItemModTable[INV_INC_STAMINARECOVERYRATE].allowed_slots = DND_MODBASE_MELEE;
	
	ItemModTable[INV_INC_STAMINAGAINED].attrib_low = 1;
	ItemModTable[INV_INC_STAMINAGAINED].attrib_high = 6;
	ItemModTable[INV_INC_STAMINAGAINED].attrib_level_modifier = 0;
	ItemModTable[INV_INC_STAMINAGAINED].tags = INV_ATTR_TAG_MELEE | INV_ATTR_TAG_STAMINA;
	ItemModTable[INV_INC_STAMINAGAINED].weight = 500;
	ItemModTable[INV_INC_STAMINAGAINED].allowed_slots = DND_MODBASE_MELEE;
	
	ItemModTable[INV_MELEECRIT_NOTONLOWSTAMINA].attrib_low = 0.01;
	ItemModTable[INV_MELEECRIT_NOTONLOWSTAMINA].attrib_high = 0.1;
	ItemModTable[INV_MELEECRIT_NOTONLOWSTAMINA].attrib_level_modifier = 0.09;
	ItemModTable[INV_MELEECRIT_NOTONLOWSTAMINA].tags = INV_ATTR_TAG_MELEE | INV_ATTR_TAG_CRIT | INV_ATTR_TAG_STAMINA;
	ItemModTable[INV_MELEECRIT_NOTONLOWSTAMINA].weight = 500;
	ItemModTable[INV_MELEECRIT_NOTONLOWSTAMINA].allowed_slots = DND_MODBASE_MELEE;
	
	ItemModTable[INV_MELEESPLASH_NOTONLOWSTAMINA].attrib_low = 1;
	ItemModTable[INV_MELEESPLASH_NOTONLOWSTAMINA].attrib_high = 6;
	ItemModTable[INV_MELEESPLASH_NOTONLOWSTAMINA].attrib_level_modifier = 0;
	ItemModTable[INV_MELEESPLASH_NOTONLOWSTAMINA].tags = INV_ATTR_TAG_MELEE | INV_ATTR_TAG_STAMINA;
	ItemModTable[INV_MELEESPLASH_NOTONLOWSTAMINA].weight = 400;
	ItemModTable[INV_MELEESPLASH_NOTONLOWSTAMINA].allowed_slots = DND_MODBASE_MELEE;

	ItemModTable[INV_MELEE_ATKCDR].attrib_low = 1;
	ItemModTable[INV_MELEE_ATKCDR].attrib_high = 8;
	ItemModTable[INV_MELEE_ATKCDR].attrib_level_modifier = 0;
	ItemModTable[INV_MELEE_ATKCDR].tags = INV_ATTR_TAG_MELEE | INV_ATTR_TAG_ATTACK;
	ItemModTable[INV_MELEE_ATKCDR].weight = 500;
	ItemModTable[INV_MELEE_ATKCDR].allowed_slots = DND_MODBASE_MELEE;

	ItemModTable[INV_CRUSHINGBLOW].attrib_low = 1;
	ItemModTable[INV_CRUSHINGBLOW].attrib_high = 4;
	ItemModTable[INV_CRUSHINGBLOW].attrib_level_modifier = 0;
	ItemModTable[INV_CRUSHINGBLOW].tags = INV_ATTR_TAG_MELEE | INV_ATTR_TAG_ATTACK;
	ItemModTable[INV_CRUSHINGBLOW].weight = 350;
	ItemModTable[INV_CRUSHINGBLOW].allowed_slots = DND_MODBASE_MELEE;

	ItemModTable[INV_DEEPCUTS].attrib_low = 1;
	ItemModTable[INV_DEEPCUTS].attrib_high = 5;
	ItemModTable[INV_DEEPCUTS].attrib_level_modifier = 0;
	ItemModTable[INV_DEEPCUTS].tags = INV_ATTR_TAG_MELEE | INV_ATTR_TAG_ATTACK;
	ItemModTable[INV_DEEPCUTS].weight = 450;
	ItemModTable[INV_DEEPCUTS].allowed_slots = DND_MODBASE_MELEE;
		
	ItemModTable[INV_OPENWOUNDS].attrib_low = 1;
	ItemModTable[INV_OPENWOUNDS].attrib_high = 5;
	ItemModTable[INV_OPENWOUNDS].attrib_level_modifier = 0;
	ItemModTable[INV_OPENWOUNDS].tags = INV_ATTR_TAG_MELEE | INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_PHYSICAL;
	ItemModTable[INV_OPENWOUNDS].weight = 450;
	ItemModTable[INV_OPENWOUNDS].allowed_slots = DND_MODBASE_MELEE;

	ItemModTable[INV_DEADLYSTRIKE].attrib_low = 1;
	ItemModTable[INV_DEADLYSTRIKE].attrib_high = 3;
	ItemModTable[INV_DEADLYSTRIKE].attrib_level_modifier = 0;
	ItemModTable[INV_DEADLYSTRIKE].tags = INV_ATTR_TAG_MELEE | INV_ATTR_TAG_ATTACK;
	ItemModTable[INV_DEADLYSTRIKE].weight = 300;
	ItemModTable[INV_DEADLYSTRIKE].allowed_slots = DND_MODBASE_MELEE;

	ItemModTable[INV_REAPINGCLEAVE].attrib_low = 1;
	ItemModTable[INV_REAPINGCLEAVE].attrib_high = 3;
	ItemModTable[INV_REAPINGCLEAVE].attrib_level_modifier = 0;
	ItemModTable[INV_REAPINGCLEAVE].tags = INV_ATTR_TAG_MELEE | INV_ATTR_TAG_ATTACK;
	ItemModTable[INV_REAPINGCLEAVE].weight = 300;
	ItemModTable[INV_REAPINGCLEAVE].allowed_slots = DND_MODBASE_MELEE;

	ItemModTable[INV_INCFLASKCHARGEGAINED].attrib_low = 1;
	ItemModTable[INV_INCFLASKCHARGEGAINED].attrib_high = 4;
	ItemModTable[INV_INCFLASKCHARGEGAINED].attrib_level_modifier = 0;
	ItemModTable[INV_INCFLASKCHARGEGAINED].tags = INV_ATTR_TAG_UTILITY | INV_ATTR_TAG_FLASK;
	ItemModTable[INV_INCFLASKCHARGEGAINED].weight = 500;
	ItemModTable[INV_INCFLASKCHARGEGAINED].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_SPECIALTY_ALL;

	ItemModTable[INV_FLASKLIFERECOVERYRATE].attrib_low = 1;
	ItemModTable[INV_FLASKLIFERECOVERYRATE].attrib_high = 4;
	ItemModTable[INV_FLASKLIFERECOVERYRATE].attrib_level_modifier = 0;
	ItemModTable[INV_FLASKLIFERECOVERYRATE].tags = INV_ATTR_TAG_UTILITY | INV_ATTR_TAG_FLASK;
	ItemModTable[INV_FLASKLIFERECOVERYRATE].weight = 500;
	ItemModTable[INV_FLASKLIFERECOVERYRATE].allowed_slots = DND_MODBASE_CHARM | DND_MODBASE_SPECIALTY_ALL;
	
	/////////////////////////
	// corrupted implicits //
	/////////////////////////
	ItemModTable[INV_CORR_WEAPONDMG].attrib_low = 1.15;
	ItemModTable[INV_CORR_WEAPONDMG].attrib_high = 1.33;
	ItemModTable[INV_CORR_WEAPONDMG].attrib_level_modifier = 0;
	ItemModTable[INV_CORR_WEAPONDMG].tags = INV_ATTR_TAG_DAMAGE;

	ItemModTable[INV_CORR_WEAPONCRIT].attrib_low = 0.5;
	ItemModTable[INV_CORR_WEAPONCRIT].attrib_high = 1.0;
	ItemModTable[INV_CORR_WEAPONCRIT].attrib_level_modifier = 0;
	ItemModTable[INV_CORR_WEAPONCRIT].tags = INV_ATTR_TAG_CRIT;

	ItemModTable[INV_CORR_WEAPONCRITDMG].attrib_low = 50;
	ItemModTable[INV_CORR_WEAPONCRITDMG].attrib_high = 200;
	ItemModTable[INV_CORR_WEAPONCRITDMG].attrib_level_modifier = 0;
	ItemModTable[INV_CORR_WEAPONCRITDMG].tags = INV_ATTR_TAG_CRIT;

	ItemModTable[INV_CORR_SPEED].attrib_low = 0.1;
	ItemModTable[INV_CORR_SPEED].attrib_high = 0.25;
	ItemModTable[INV_CORR_SPEED].attrib_level_modifier = 0;
	ItemModTable[INV_CORR_SPEED].tags = INV_ATTR_TAG_UTILITY;

	ItemModTable[INV_CORR_DROPCHANCE].attrib_low = 0.1;
	ItemModTable[INV_CORR_DROPCHANCE].attrib_high = 0.2;
	ItemModTable[INV_CORR_DROPCHANCE].attrib_level_modifier = 0;
	ItemModTable[INV_CORR_DROPCHANCE].tags = INV_ATTR_TAG_UTILITY;

	ItemModTable[INV_CORR_PERCENTSTATS].attrib_low = 10;
	ItemModTable[INV_CORR_PERCENTSTATS].attrib_high = 33;
	ItemModTable[INV_CORR_PERCENTSTATS].attrib_level_modifier = 0;
	ItemModTable[INV_CORR_PERCENTSTATS].tags = INV_ATTR_TAG_STAT;

	ItemModTable[INV_CORR_WEAPONPLUSPROJ].attrib_low = 1;
	ItemModTable[INV_CORR_WEAPONPLUSPROJ].attrib_high = 1;
	ItemModTable[INV_CORR_WEAPONPLUSPROJ].attrib_level_modifier = -1;
	ItemModTable[INV_CORR_WEAPONPLUSPROJ].tags = INV_ATTR_TAG_ATTACK;

	ItemModTable[INV_CORR_WEAPONPOISONPCT].attrib_low = 5;
	ItemModTable[INV_CORR_WEAPONPOISONPCT].attrib_high = 10;
	ItemModTable[INV_CORR_WEAPONPOISONPCT].attrib_level_modifier = 0;
	ItemModTable[INV_CORR_WEAPONPOISONPCT].tags = INV_ATTR_TAG_ELEMENTAL;
	
	ItemModTable[INV_CORR_WEAPONFORCEPAIN].attrib_low = 1;
	ItemModTable[INV_CORR_WEAPONFORCEPAIN].attrib_high = 20;
	ItemModTable[INV_CORR_WEAPONFORCEPAIN].attrib_level_modifier = 0;
	ItemModTable[INV_CORR_WEAPONFORCEPAIN].tags = INV_ATTR_TAG_UTILITY;

	ItemModTable[INV_CORR_CYBERNETIC].attrib_low = 1;
	ItemModTable[INV_CORR_CYBERNETIC].attrib_high = 1;
	ItemModTable[INV_CORR_CYBERNETIC].attrib_level_modifier = 0;
	ItemModTable[INV_CORR_CYBERNETIC].tags = INV_ATTR_TAG_UTILITY;

	ItemModTable[INV_CORR_DMGDOESNTSTOPREGEN].attrib_low = 1;
	ItemModTable[INV_CORR_DMGDOESNTSTOPREGEN].attrib_high = 1;
	ItemModTable[INV_CORR_DMGDOESNTSTOPREGEN].attrib_level_modifier = 0;
	ItemModTable[INV_CORR_DMGDOESNTSTOPREGEN].tags = INV_ATTR_TAG_UTILITY;

	ItemModTable[INV_CORR_INSTALEECHPCT].attrib_low = 5;
	ItemModTable[INV_CORR_INSTALEECHPCT].attrib_high = 10;
	ItemModTable[INV_CORR_INSTALEECHPCT].attrib_level_modifier = 0;
	ItemModTable[INV_CORR_INSTALEECHPCT].tags = INV_ATTR_TAG_LIFE;

	ItemModTable[INV_CORR_MOREAOE].attrib_low = 0.01;
	ItemModTable[INV_CORR_MOREAOE].attrib_high = 0.2;
	ItemModTable[INV_CORR_MOREAOE].attrib_level_modifier = 0;
	ItemModTable[INV_CORR_MOREAOE].tags = INV_ATTR_TAG_EXPLOSIVE;

	ItemModTable[INV_CORR_ALLPIERCE].attrib_low = 1;
	ItemModTable[INV_CORR_ALLPIERCE].attrib_high = 10;
	ItemModTable[INV_CORR_ALLPIERCE].attrib_level_modifier = 0;
	ItemModTable[INV_CORR_ALLPIERCE].tags = INV_ATTR_TAG_ATTACK;

	ItemModTable[INV_CORR_WEPCULL].attrib_low = 1;
	ItemModTable[INV_CORR_WEPCULL].attrib_high = 1;
	ItemModTable[INV_CORR_WEPCULL].attrib_level_modifier = 0;
	ItemModTable[INV_CORR_WEPCULL].tags = INV_ATTR_TAG_ATTACK;

	ItemModTable[INV_CORR_MAXFRENZY].attrib_low = 1;
	ItemModTable[INV_CORR_MAXFRENZY].attrib_high = 1;
	ItemModTable[INV_CORR_MAXFRENZY].attrib_level_modifier = 0;
	ItemModTable[INV_CORR_MAXFRENZY].tags = INV_ATTR_TAG_UTILITY;

	ItemModTable[INV_CORR_MAXENDURANCE].attrib_low = 1;
	ItemModTable[INV_CORR_MAXENDURANCE].attrib_high = 1;
	ItemModTable[INV_CORR_MAXENDURANCE].attrib_level_modifier = 0;
	ItemModTable[INV_CORR_MAXENDURANCE].tags = INV_ATTR_TAG_UTILITY;

	ItemModTable[INV_CORR_MAXPOWER].attrib_low = 1;
	ItemModTable[INV_CORR_MAXPOWER].attrib_high = 1;
	ItemModTable[INV_CORR_MAXPOWER].attrib_level_modifier = 0;
	ItemModTable[INV_CORR_MAXPOWER].tags = INV_ATTR_TAG_UTILITY;

	///////////////////////
	// regular implicits //
	///////////////////////

	// we dont care what they have, they get loaded in hardcoded values from outside
	for(int i = FIRST_REGULAR_IMPLICIT; i <= LAST_REGULAR_IMPLICIT; ++i) {
		ItemModTable[i].attrib_low = 100000;
		ItemModTable[i].attrib_high = -1;
		ItemModTable[i].attrib_level_modifier = 0;
		ItemModTable[i].tags = INV_ATTR_TAG_DEFENSE;
	}

	///////////////////////////////
	// essences from here on out //
	///////////////////////////////
	ItemModTable[INV_ESS_VAAJ].attrib_low = 1;
	ItemModTable[INV_ESS_VAAJ].attrib_high = 4;
	ItemModTable[INV_ESS_VAAJ].attrib_extra_low = 1;
	ItemModTable[INV_ESS_VAAJ].attrib_extra_high = 2;
	ItemModTable[INV_ESS_VAAJ].attrib_level_modifier = 0;
	ItemModTable[INV_ESS_VAAJ].attrib_level_extra_modifier = 0;
	ItemModTable[INV_ESS_VAAJ].tags = INV_ATTR_TAG_EXPLOSIVE;
	
	ItemModTable[INV_ESS_SSRATH].attrib_low = 3;
	ItemModTable[INV_ESS_SSRATH].attrib_high = 5;
	ItemModTable[INV_ESS_SSRATH].attrib_level_modifier = 0;
	ItemModTable[INV_ESS_SSRATH].tags = INV_ATTR_TAG_OCCULT;
	
	ItemModTable[INV_ESS_OMNISIGHT].attrib_low = 500;
	ItemModTable[INV_ESS_OMNISIGHT].attrib_high = 1000;
	ItemModTable[INV_ESS_OMNISIGHT].attrib_level_modifier = 0;
	ItemModTable[INV_ESS_OMNISIGHT].tags = INV_ATTR_TAG_ATTACK;
	
	ItemModTable[INV_ESS_OMNISIGHT2].attrib_low = 2;
	ItemModTable[INV_ESS_OMNISIGHT2].attrib_high = 5;
	ItemModTable[INV_ESS_OMNISIGHT2].attrib_level_modifier = 0;
	ItemModTable[INV_ESS_OMNISIGHT2].tags = INV_ATTR_TAG_ATTACK;
	
	ItemModTable[INV_ESS_CHEGOVAX].attrib_low = 1;
	ItemModTable[INV_ESS_CHEGOVAX].attrib_high = 4;
	ItemModTable[INV_ESS_CHEGOVAX].attrib_level_modifier = 0;
	ItemModTable[INV_ESS_CHEGOVAX].tags = INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_FIRE;
	
	ItemModTable[INV_ESS_HARKIMONDE].attrib_low = 3;
	ItemModTable[INV_ESS_HARKIMONDE].attrib_high = 6;
	ItemModTable[INV_ESS_HARKIMONDE].attrib_level_modifier = 0;
	ItemModTable[INV_ESS_HARKIMONDE].tags = INV_ATTR_TAG_ATTACK;
	
	ItemModTable[INV_ESS_LESHRAC].attrib_low = 1;
	ItemModTable[INV_ESS_LESHRAC].attrib_high = 1;
	ItemModTable[INV_ESS_LESHRAC].attrib_level_modifier = 1;
	ItemModTable[INV_ESS_LESHRAC].tags = INV_ATTR_TAG_POISON;
	
	ItemModTable[INV_ESS_KRULL].attrib_low = 5;
	ItemModTable[INV_ESS_KRULL].attrib_high = 9;
	ItemModTable[INV_ESS_KRULL].attrib_level_modifier = 0;
	ItemModTable[INV_ESS_KRULL].tags = INV_ATTR_TAG_EXPLOSIVE;
	
	ItemModTable[INV_ESS_THORAX].attrib_low = 1;
	ItemModTable[INV_ESS_THORAX].attrib_high = 1;
	ItemModTable[INV_ESS_THORAX].attrib_level_modifier = 1;
	ItemModTable[INV_ESS_THORAX].tags = INV_ATTR_TAG_ATTACK;
	
	ItemModTable[INV_ESS_ZRAVOG].attrib_low = 1;
	ItemModTable[INV_ESS_ZRAVOG].attrib_high = 2;
	ItemModTable[INV_ESS_ZRAVOG].attrib_level_modifier = 0;
	ItemModTable[INV_ESS_ZRAVOG].tags = INV_ATTR_TAG_OCCULT;
	
	ItemModTable[INV_ESS_ERYXIA].attrib_low = 0.05;
	ItemModTable[INV_ESS_ERYXIA].attrib_high = 0.075;
	ItemModTable[INV_ESS_ERYXIA].attrib_level_modifier = 0.025;
	ItemModTable[INV_ESS_ERYXIA].tags = INV_ATTR_TAG_ELEMENTAL | INV_ATTR_TAG_ICE;

	////////////////////////////////
	// incursion from here on out //
	////////////////////////////////
	ItemModTable[INV_INC_DOUBLEHPBONUS].attrib_low = 1;
	ItemModTable[INV_INC_DOUBLEHPBONUS].attrib_high = 1;
	ItemModTable[INV_INC_DOUBLEHPBONUS].attrib_level_modifier = 0;
	ItemModTable[INV_INC_DOUBLEHPBONUS].attrib_extra_low = 300;
	ItemModTable[INV_INC_DOUBLEHPBONUS].attrib_extra_high = 300;
	ItemModTable[INV_INC_DOUBLEHPBONUS].attrib_level_extra_modifier = -1;
	ItemModTable[INV_INC_DOUBLEHPBONUS].tags = INV_ATTR_TAG_LIFE;

	ItemModTable[INV_INC_MAXPOISONSTACK].attrib_low = 1;
	ItemModTable[INV_INC_MAXPOISONSTACK].attrib_high = 1;
	ItemModTable[INV_INC_MAXPOISONSTACK].attrib_level_modifier = 0;
	ItemModTable[INV_INC_MAXPOISONSTACK].tags = INV_ATTR_TAG_POISON | INV_ATTR_TAG_ELEMENTAL;

	ItemModTable[INV_INC_POISONSPREAD].attrib_low = 1;
	ItemModTable[INV_INC_POISONSPREAD].attrib_high = 3;
	ItemModTable[INV_INC_POISONSPREAD].attrib_level_modifier = 0;
	ItemModTable[INV_INC_POISONSPREAD].tags = INV_ATTR_TAG_POISON | INV_ATTR_TAG_ELEMENTAL;

	ItemModTable[INV_INC_CRITFORDOT].attrib_low = 1;
	ItemModTable[INV_INC_CRITFORDOT].attrib_high = 1;
	ItemModTable[INV_INC_CRITFORDOT].attrib_level_modifier = 0;
	ItemModTable[INV_INC_CRITFORDOT].tags = INV_ATTR_TAG_CRIT | INV_ATTR_TAG_DAMAGE;

	ItemModTable[INV_INC_ALLOVERLOAD].attrib_low = 25;
	ItemModTable[INV_INC_ALLOVERLOAD].attrib_high = 40;
	ItemModTable[INV_INC_ALLOVERLOAD].attrib_level_modifier = -1;
	ItemModTable[INV_INC_ALLOVERLOAD].tags = INV_ATTR_TAG_LIGHTNING | INV_ATTR_TAG_ELEMENTAL;

	ItemModTable[INV_INC_ESHIELDNOINTERRUPT].attrib_low = 1;
	ItemModTable[INV_INC_ESHIELDNOINTERRUPT].attrib_high = 1;
	ItemModTable[INV_INC_ESHIELDNOINTERRUPT].attrib_level_modifier = 0;
	ItemModTable[INV_INC_ESHIELDNOINTERRUPT].tags = INV_ATTR_TAG_DEFENSE;

	ItemModTable[INV_INC_PLUSPROJ].attrib_low = 1;
	ItemModTable[INV_INC_PLUSPROJ].attrib_high = 1;
	ItemModTable[INV_INC_PLUSPROJ].attrib_level_modifier = -1;
	ItemModTable[INV_INC_PLUSPROJ].tags = INV_ATTR_TAG_ATTACK;

	ItemModTable[INV_INC_PLUSTWOPROJ].attrib_low = 2;
	ItemModTable[INV_INC_PLUSTWOPROJ].attrib_high = 2;
	ItemModTable[INV_INC_PLUSTWOPROJ].attrib_level_modifier = -1;
	ItemModTable[INV_INC_PLUSTWOPROJ].tags = INV_ATTR_TAG_ATTACK;

	ItemModTable[INV_INC_INSTANTLIFESTEAL].attrib_low = 1;
	ItemModTable[INV_INC_INSTANTLIFESTEAL].attrib_high = 2;
	ItemModTable[INV_INC_INSTANTLIFESTEAL].attrib_level_modifier = 0;
	ItemModTable[INV_INC_INSTANTLIFESTEAL].attrib_extra_low = 100;
	ItemModTable[INV_INC_INSTANTLIFESTEAL].attrib_extra_high = 100;
	ItemModTable[INV_INC_INSTANTLIFESTEAL].attrib_level_extra_modifier = -1;
	ItemModTable[INV_INC_INSTANTLIFESTEAL].tags = INV_ATTR_TAG_ATTACK | INV_ATTR_TAG_LIFE;

	ItemModTable[INV_INC_TWICEARMORDEFENSE].attrib_low = 1;
	ItemModTable[INV_INC_TWICEARMORDEFENSE].attrib_high = 2;
	ItemModTable[INV_INC_TWICEARMORDEFENSE].attrib_level_modifier = 0;
	ItemModTable[INV_INC_TWICEARMORDEFENSE].tags = INV_ATTR_TAG_DEFENSE;

	ItemModTable[INV_INC_MITIGATIONTODODGE].attrib_low = 1;
	ItemModTable[INV_INC_MITIGATIONTODODGE].attrib_high = 1;
	ItemModTable[INV_INC_MITIGATIONTODODGE].attrib_level_modifier = 0;
	ItemModTable[INV_INC_MITIGATIONTODODGE].tags = INV_ATTR_TAG_DEFENSE;

	ItemModTable[INV_INC_ACCURACYFORPRECISION].attrib_low = 1;
	ItemModTable[INV_INC_ACCURACYFORPRECISION].attrib_high = 2;
	ItemModTable[INV_INC_ACCURACYFORPRECISION].attrib_level_modifier = -1;
	ItemModTable[INV_INC_ACCURACYFORPRECISION].tags = INV_ATTR_TAG_ATTACK;

	ItemModTable[INV_INC_HPREGENINTERRUPT].attrib_low = 1;
	ItemModTable[INV_INC_HPREGENINTERRUPT].attrib_high = 1;
	ItemModTable[INV_INC_HPREGENINTERRUPT].attrib_level_modifier = 0;
	ItemModTable[INV_INC_HPREGENINTERRUPT].tags = INV_ATTR_TAG_LIFE;

	ItemModTable[INV_INC_PASSIVEREGEN].attrib_low = 0.01;
	ItemModTable[INV_INC_PASSIVEREGEN].attrib_high = 0.03;
	ItemModTable[INV_INC_PASSIVEREGEN].attrib_extra_low = 100;
	ItemModTable[INV_INC_PASSIVEREGEN].attrib_extra_high = 100;
	ItemModTable[INV_INC_PASSIVEREGEN].attrib_level_modifier = 0.02;
	ItemModTable[INV_INC_PASSIVEREGEN].attrib_level_extra_modifier = -1;
	ItemModTable[INV_INC_PASSIVEREGEN].tags = INV_ATTR_TAG_LIFE;

	ItemModTable[INV_INC_ENEMYRIPCHANCE].attrib_low = 1;
	ItemModTable[INV_INC_ENEMYRIPCHANCE].attrib_high = 3;
	ItemModTable[INV_INC_ENEMYRIPCHANCE].attrib_level_modifier = 0;
	ItemModTable[INV_INC_ENEMYRIPCHANCE].tags = INV_ATTR_TAG_UTILITY;

	ItemModTable[INV_INC_BLOCKPREVENTION].attrib_low = 1;
	ItemModTable[INV_INC_BLOCKPREVENTION].attrib_high = 8;
	ItemModTable[INV_INC_BLOCKPREVENTION].attrib_level_modifier = 0;
	ItemModTable[INV_INC_BLOCKPREVENTION].tags = INV_ATTR_TAG_UTILITY | INV_ATTR_TAG_ATTACK;

	ItemModTable[INV_INC_RIPPERSEXPLODE].attrib_low = 1;
	ItemModTable[INV_INC_RIPPERSEXPLODE].attrib_high = 2;
	ItemModTable[INV_INC_RIPPERSEXPLODE].attrib_level_modifier = 0;
	ItemModTable[INV_INC_RIPPERSEXPLODE].tags = INV_ATTR_TAG_ATTACK;

	ItemModTable[INV_INC_INVERTRESISTANCES].attrib_low = 1;
	ItemModTable[INV_INC_INVERTRESISTANCES].attrib_high = 2;
	ItemModTable[INV_INC_INVERTRESISTANCES].attrib_level_modifier = 0;
	ItemModTable[INV_INC_INVERTRESISTANCES].tags = INV_ATTR_TAG_ATTACK;

	ItemModTable[INV_INC_ACCURACYREVERSED].attrib_low = 1;
	ItemModTable[INV_INC_ACCURACYREVERSED].attrib_high = 1;
	ItemModTable[INV_INC_ACCURACYREVERSED].attrib_level_modifier = -1;
	ItemModTable[INV_INC_ACCURACYREVERSED].tags = INV_ATTR_TAG_ATTACK;

	ItemModTable[INV_INC_PROJREVERSE].attrib_low = 0.1;
	ItemModTable[INV_INC_PROJREVERSE].attrib_high = 2.0;
	ItemModTable[INV_INC_PROJREVERSE].attrib_level_modifier = -1;
	ItemModTable[INV_INC_PROJREVERSE].tags = INV_ATTR_TAG_ATTACK;

	ItemModTable[INV_INC_EXCESSCRIT].attrib_low = 0.2;
	ItemModTable[INV_INC_EXCESSCRIT].attrib_high = 0.2;
	ItemModTable[INV_INC_EXCESSCRIT].attrib_level_modifier = -1;
	ItemModTable[INV_INC_EXCESSCRIT].tags = INV_ATTR_TAG_CRIT;

	///////////////////////////////
	// flask mods from here out  //
	///////////////////////////////
	ItemModTable[INV_FLASK_INCCHARGES].attrib_low = 5;
	ItemModTable[INV_FLASK_INCCHARGES].attrib_high = 10;
	ItemModTable[INV_FLASK_INCCHARGES].attrib_level_modifier = 0;
	ItemModTable[INV_FLASK_INCCHARGES].tags = INV_ATTR_TAG_FLASK;

	ItemModTable[INV_FLASK_REDUCEDCHARGEUSE].attrib_low = 1;
	ItemModTable[INV_FLASK_REDUCEDCHARGEUSE].attrib_high = 10;
	ItemModTable[INV_FLASK_REDUCEDCHARGEUSE].attrib_level_modifier = 0;
	ItemModTable[INV_FLASK_REDUCEDCHARGEUSE].tags = INV_ATTR_TAG_FLASK;

	ItemModTable[INV_FLASK_INCAMOUNTRECOVER].attrib_low = 1;
	ItemModTable[INV_FLASK_INCAMOUNTRECOVER].attrib_high = 6;
	ItemModTable[INV_FLASK_INCAMOUNTRECOVER].attrib_level_modifier = 0;
	ItemModTable[INV_FLASK_INCAMOUNTRECOVER].attrib_extra_low = 20;
	ItemModTable[INV_FLASK_INCAMOUNTRECOVER].attrib_extra_high = 25;
	ItemModTable[INV_FLASK_INCAMOUNTRECOVER].attrib_level_extra_modifier = -1;
	ItemModTable[INV_FLASK_INCAMOUNTRECOVER].tags = INV_ATTR_TAG_FLASK;
    
	ItemModTable[INV_FLASK_INSTANTRECOVERY].attrib_low = 1;
	ItemModTable[INV_FLASK_INSTANTRECOVERY].attrib_high = 1;
	ItemModTable[INV_FLASK_INSTANTRECOVERY].attrib_level_modifier = 0;
	ItemModTable[INV_FLASK_INSTANTRECOVERY].attrib_extra_low = 50;
	ItemModTable[INV_FLASK_INSTANTRECOVERY].attrib_extra_high = 66;
	ItemModTable[INV_FLASK_INSTANTRECOVERY].attrib_level_extra_modifier = -1;
	ItemModTable[INV_FLASK_INSTANTRECOVERY].tags = INV_ATTR_TAG_FLASK;

	ItemModTable[INV_FLASK_INCEFFECT].attrib_low = 4;
	ItemModTable[INV_FLASK_INCEFFECT].attrib_high = 10;
	ItemModTable[INV_FLASK_INCEFFECT].attrib_level_modifier = 0;
	ItemModTable[INV_FLASK_INCEFFECT].attrib_extra_low = 2;
	ItemModTable[INV_FLASK_INCEFFECT].attrib_extra_high = 6;
	ItemModTable[INV_FLASK_INCEFFECT].attrib_level_extra_modifier = 0;
	ItemModTable[INV_FLASK_INCEFFECT].tags = INV_ATTR_TAG_FLASK;
    
	ItemModTable[INV_FLASK_INCDURATION].attrib_low = 1;
	ItemModTable[INV_FLASK_INCDURATION].attrib_high = 6;
	ItemModTable[INV_FLASK_INCDURATION].attrib_level_modifier = 0;
	ItemModTable[INV_FLASK_INCDURATION].tags = INV_ATTR_TAG_FLASK;
    
	ItemModTable[INV_FLASK_IMMUNE_BLEED].attrib_low = 1;
	ItemModTable[INV_FLASK_IMMUNE_BLEED].attrib_high = 1;
	ItemModTable[INV_FLASK_IMMUNE_BLEED].attrib_level_modifier = 0;
	ItemModTable[INV_FLASK_IMMUNE_BLEED].tags = INV_ATTR_TAG_FLASK;
    
	ItemModTable[INV_FLASK_IMMUNE_POISON].attrib_low = 1;
	ItemModTable[INV_FLASK_IMMUNE_POISON].attrib_high = 1;
	ItemModTable[INV_FLASK_IMMUNE_POISON].attrib_level_modifier = 0;
	ItemModTable[INV_FLASK_IMMUNE_POISON].tags = INV_ATTR_TAG_FLASK;

	ItemModTable[INV_FLASK_IMMUNE_SHOCK].attrib_low = 1;
	ItemModTable[INV_FLASK_IMMUNE_SHOCK].attrib_high = 1;
	ItemModTable[INV_FLASK_IMMUNE_SHOCK].attrib_level_modifier = 0;
	ItemModTable[INV_FLASK_IMMUNE_SHOCK].tags = INV_ATTR_TAG_FLASK;

	ItemModTable[INV_FLASK_IMMUNE_IGNITE].attrib_low = 1;
	ItemModTable[INV_FLASK_IMMUNE_IGNITE].attrib_high = 1;
	ItemModTable[INV_FLASK_IMMUNE_IGNITE].attrib_level_modifier = 0;
	ItemModTable[INV_FLASK_IMMUNE_IGNITE].tags = INV_ATTR_TAG_FLASK;

	ItemModTable[INV_FLASK_IMMUNE_CHILLFREEZE].attrib_low = 1;
	ItemModTable[INV_FLASK_IMMUNE_CHILLFREEZE].attrib_high = 1;
	ItemModTable[INV_FLASK_IMMUNE_CHILLFREEZE].attrib_level_modifier = 0;
	ItemModTable[INV_FLASK_IMMUNE_CHILLFREEZE].tags = INV_ATTR_TAG_FLASK;

	ItemModTable[INV_FLASK_CHANCEGAINCRIT].attrib_low = 1;
	ItemModTable[INV_FLASK_CHANCEGAINCRIT].attrib_high = 6;
	ItemModTable[INV_FLASK_CHANCEGAINCRIT].attrib_level_modifier = 0;
	ItemModTable[INV_FLASK_CHANCEGAINCRIT].tags = INV_ATTR_TAG_FLASK;
    
	ItemModTable[INV_FLASK_CHANCEGAINONHIT].attrib_low = 1;
	ItemModTable[INV_FLASK_CHANCEGAINONHIT].attrib_high = 14;
	ItemModTable[INV_FLASK_CHANCEGAINONHIT].attrib_level_modifier = 0;
	ItemModTable[INV_FLASK_CHANCEGAINONHIT].attrib_level_extra_modifier = -1;
	ItemModTable[INV_FLASK_CHANCEGAINONHIT].tags = INV_ATTR_TAG_FLASK;

	ItemModTable[INV_FLASK_INCCHARGERECOVERY].attrib_low = 5;
	ItemModTable[INV_FLASK_INCCHARGERECOVERY].attrib_high = 10;
	ItemModTable[INV_FLASK_INCCHARGERECOVERY].attrib_level_modifier = 0;
	ItemModTable[INV_FLASK_INCCHARGERECOVERY].attrib_extra_low = 25;
	ItemModTable[INV_FLASK_INCCHARGERECOVERY].attrib_extra_high = 25;
	ItemModTable[INV_FLASK_INCCHARGERECOVERY].attrib_level_extra_modifier = -1;
	ItemModTable[INV_FLASK_INCCHARGERECOVERY].tags = INV_ATTR_TAG_FLASK;

	ItemModTable[INV_FLASK_INCRECOVERYRATE].attrib_low = 1;
	ItemModTable[INV_FLASK_INCRECOVERYRATE].attrib_high = 10;
	ItemModTable[INV_FLASK_INCRECOVERYRATE].attrib_level_modifier = 0;
	ItemModTable[INV_FLASK_INCRECOVERYRATE].tags = INV_ATTR_TAG_FLASK;

	ItemModTable[INV_FLASK_INSTANTONLOWLIFE].attrib_low = 1;
	ItemModTable[INV_FLASK_INSTANTONLOWLIFE].attrib_high = 1;
	ItemModTable[INV_FLASK_INSTANTONLOWLIFE].attrib_level_modifier = 0;
	ItemModTable[INV_FLASK_INSTANTONLOWLIFE].attrib_extra_low = 25;
	ItemModTable[INV_FLASK_INSTANTONLOWLIFE].attrib_extra_high = 40;
	ItemModTable[INV_FLASK_INSTANTONLOWLIFE].attrib_level_extra_modifier = -1;
	ItemModTable[INV_FLASK_INSTANTONLOWLIFE].tags = INV_ATTR_TAG_FLASK;

	ItemModTable[INV_FLASK_MORERECOVERYONLOWLIFE].attrib_low = 6;
	ItemModTable[INV_FLASK_MORERECOVERYONLOWLIFE].attrib_high = 10;
	ItemModTable[INV_FLASK_MORERECOVERYONLOWLIFE].attrib_level_modifier = 0;
	ItemModTable[INV_FLASK_MORERECOVERYONLOWLIFE].tags = INV_ATTR_TAG_FLASK;
}

#endif