#ifndef DND_ITEMMODPOOL_IN
#define DND_ITEMMODPOOL_IN

#define DND_ITEM_SLOT_SHIFT 6 // 6 bits to store the item slot (type)

typedef struct {
    int count;
    int[]* mod_list;
} mod_pool_T;

// maps: Item Slot (6 bits) | Allowed mod bases (DND_IMPFLAG_ARMOR | DND_IMPFLAG_MITIGATION etc etc.) to mod_pool_T*
LIBBCS_T_MAP_DEFN(CachedModPoolIdMap, int, int, LIBBCS_SIMPLE_CMP);

typedef struct {
    int curr_size;
    CachedModPoolIdMapT CachedModPools;
} mod_info_data_T;

global mod_info_data_T 35: ModPoolTables;

void FreeModPool(mod_pool_T* m) {
    bcs::arrDelete(m.mod_list);
    bcs::free(m);
}

// Check if the slot this mod is for is appropriate, as well as the implicit properties of the item
// first part solves "what items can roll this mod" problem
// second part solves "is this mod tag even eligible to appear" problem
// third part solves "is there an implicit conflict" problem, ie. Armor|Mitigation base trying to roll energy shield
bool CanRollMod(int item_base_mask, int item_allowed_tags, int mod) {
    return  (ItemModTable[mod].allowed_slots & item_base_mask) && 
            (ItemModTable[mod].tags & item_allowed_tags) == ItemModTable[mod].tags;
}

// sets up mod pool for a given item base, with given mod tags that can be applied to it for eligibility (this is used as a cached pool for monster drops)
mod_pool_T* BuildModPool(int item_base_mask, int item_allowed_tags) {
    int buf[NORMAL_ATTRIBUTE_COUNT];
    int count = 0;

    for(int i = FIRST_INV_ATTRIBUTE; i <= LAST_INV_ATTRIBUTE; ++i) {
        if(!CanRollMod(item_base_mask, item_allowed_tags, i))
            continue;
        buf[count++] = i;
    }

    mod_pool_T* m = bcs::malloc(SIZEOF_INT * 2);
    m.mod_list = bcs::arrNew(count);
    m.count = count;

    for(i = 0; i < count; ++i)
        m.mod_list[i] = buf[i];

    return m;
}

// when something that isn't found on the modpool cache is requested, we will create it for the first time and use it later
void RegisterModPoolCache(int item_type, int item_allowed_tags) {
    mod_pool_T* m = null;
    int id = item_type | (item_allowed_tags << DND_ITEM_SLOT_SHIFT);
    if((m = CachedModPoolIdMap_Get(ModPoolTables.CachedModPools, id)) == null) {
        // get the pool for a given item slot mapped to its mod base flag and its propety flags
        m = BuildModPool(
            ItemTypeToModBaseFlag(item_type), 
            item_allowed_tags
        );
        CachedModPoolIdMap_Put(ModPoolTables.CachedModPools, id, (int)m);
    }
}

// ids of mod pools are generated by the flags created by DND_IMPFLAG_ARMOR | DND_IMPFLAG_MITIGATION etc.
mod_pool_T* GetModPool(int item_type, int item_allowed_tags) {
    int id = item_type | (item_allowed_tags << DND_ITEM_SLOT_SHIFT);
    return CachedModPoolIdMap_Get(ModPoolTables.CachedModPools, id);
}

void InitModPoolCache() {
    ModPoolTables.CachedModPools = CachedModPoolIdMap_New();
    ModPoolTables.curr_size = 0;
}

#endif