#ifndef DND_INV_IMG_IN
#define DND_INV_IMG_IN

enum {
	IIMG_SC_1,
	IIMG_SC_2,
	IIMG_SC_3,
	
	IIMG_MC_1 = 20,
	IIMG_MC_2,
	IIMG_MC_3,
	
	IIMG_LC_1 = 40,
	IIMG_LC_2,
	IIMG_LC_3,
	
	// unique charm images
	IIMG_UCHRM_1 = 60,
	IIMG_UCHRM_2,
	IIMG_UCHRM_3,
	IIMG_UCHRM_4,
	IIMG_UCHRM_5,
	IIMG_UCHRM_6,
	IIMG_UCHRM_7,
	IIMG_UCHRM_8,
	IIMG_UCHRM_9,
	IIMG_UCHRM_10,
	IIMG_UCHRM_11,
	IIMG_UCHRM_12,
	IIMG_UCHRM_13,
	IIMG_UCHRM_14,
	IIMG_UCHRM_15,
	IIMG_UCHRM_16,
	IIMG_UCHRM_17,
	IIMG_UCHRM_18,
	IIMG_UCHRM_19,
	IIMG_UCHRM_20,
	IIMG_UCHRM_21,
	IIMG_UCHRM_22,

	// drop only charms
	IIMG_UDCHRM_1 = 400,
	IIMG_UDCHRM_2,
	IIMG_UDCHRM_3,
	IIMG_UDCHRM_4,
	IIMG_UDCHRM_5,

	IIMG_UCORE_1 = 600,
	IIMG_UCORE_R2,
	IIMG_UCORE_R3,
	IIMG_UCORE_R4,
	IIMG_UCORE_R5,
	IIMG_UCORE_R6,

	IIMG_UBODY_1 = 700,
	IIMG_UBODY_2,
	IIMG_UBODY_3,
	IIMG_UBODY_R4,
	IIMG_UBODY_R5,
	IIMG_UBODY_R6,
	IIMG_UBODY_R7,
	IIMG_UBODY_R8,
	IIMG_UBODY_R9,
	IIMG_UBODY_R10,
	IIMG_UBODY_R11,
	IIMG_UBODY_R12,
	IIMG_UBODY_R13,
	IIMG_UBODY_R14,
	IIMG_UBODY_R15,
	IIMG_UBODY_R16,

	IIMG_UBOOT_1 = 1000,
	IIMG_UBOOT_2,
	IIMG_UBOOT_3,
	IIMG_UBOOT_R4,
	IIMG_UBOOT_R5,
	IIMG_UBOOT_R6,
	IIMG_UBOOT_R7,
	IIMG_UBOOT_R8,
	IIMG_UBOOT_R9,
	IIMG_UBOOT_R10,
	IIMG_UBOOT_R11,
	IIMG_UBOOT_R12,
	IIMG_UBOOT_R13,
	IIMG_UBOOT_R14,
	IIMG_UBOOT_R15,
	IIMG_UBOOT_R16,

	IIMG_UHELM_1 = 1300,
	IIMG_UHELM_2,
	IIMG_UHELM_3,
	IIMG_UHELM_4,
	IIMG_UHELM_R5,
	IIMG_UHELM_R6,
	IIMG_UHELM_R7,
	IIMG_UHELM_R8,
	IIMG_UHELM_R9,
	IIMG_UHELM_R10,
	IIMG_UHELM_R11,
	IIMG_UHELM_R12,
	IIMG_UHELM_R13,
	IIMG_UHELM_R14,
	IIMG_UHELM_R15,
	IIMG_UHELM_R16,
	
	IIMG_ORB_1 = 1500,
	IIMG_ORB_2,
	IIMG_ORB_3,
	IIMG_ORB_4,
	IIMG_ORB_5,
	IIMG_ORB_6,
	IIMG_ORB_7,
	IIMG_ORB_8,
	IIMG_ORB_9,
	IIMG_ORB_10,
	IIMG_ORB_11,
	IIMG_ORB_12,
	IIMG_ORB_13,
	IIMG_ORB_14,
	IIMG_ORB_15,
	IIMG_ORB_16,
	IIMG_ORB_17,
	IIMG_ORB_18,
	IIMG_ORB_19,
	IIMG_ORB_20,
	IIMG_ORB_21,
	IIMG_ORB_22,
	IIMG_ORB_23,
	IIMG_ORB_24,
	IIMG_ORB_25,
	IIMG_ORB_26,
	IIMG_ORB_27,
	IIMG_ORB_28,
	IIMG_ORB_29,
	IIMG_ORB_30,
	IIMG_ORB_31,

	// monster specific orb drops
	IIMG_MORB_1 = 1640,
	IIMG_MORB_2,
	IIMG_MORB_3,
	IIMG_MORB_4,
	IIMG_MORB_5,
	IIMG_MORB_6,

	// armor
	IIMG_ARM_1 = 1800,
	IIMG_ARM_2,
	IIMG_ARM_3,
	IIMG_ARM_4,

	IIMG_ARM_5,
	IIMG_ARM_6,
	IIMG_ARM_7,
	IIMG_ARM_8,
	IIMG_ARM_9,

	IIMG_ARM_10,
	IIMG_ARM_11,
	IIMG_ARM_12,
	IIMG_ARM_13,
	IIMG_ARM_14,
	IIMG_ARM_15,
	IIMG_ARM_16,
	
	IIMG_ARM_17,
	IIMG_ARM_18,

	// boots
	IIMG_BOO_1 = 2000,
	IIMG_BOO_2,
	IIMG_BOO_3,
	IIMG_BOO_4,
	IIMG_BOO_5,
	IIMG_BOO_6,
	IIMG_BOO_7,
	IIMG_BOO_8,
	IIMG_BOO_9,
	IIMG_BOO_10,
	IIMG_BOO_11,
	IIMG_BOO_12,
	
	// helm
	IIMG_HLM_1 = 2200,
	IIMG_HLM_2,
	IIMG_HLM_3,
	IIMG_HLM_4,
	IIMG_HLM_5,
	IIMG_HLM_6,
	IIMG_HLM_7,
	IIMG_HLM_8,
	IIMG_HLM_9,

	// specialty items
	IIMG_SLAYERCARD_1 = 2300,
	IIMG_SLAYERCARD_2,
	IIMG_SLAYERCARD_3,

	IIMG_DOGTAG_1 = 2310,
	IIMG_DOGTAG_2,
	IIMG_DOGTAG_3,

	IIMG_SUNGLASS_1 = 2320,
	IIMG_SUNGLASS_2,
	IIMG_SUNGLASS_3,

	IIMG_CIGAR_1 = 2330,
	IIMG_CIGAR_2,
	IIMG_CIGAR_3,

	IIMG_POWERRING_1 = 2340,
	IIMG_POWERRING_2,
	IIMG_POWERRING_3,

	IIMG_CORE_1 = 2350,
	IIMG_CORE_2,
	IIMG_CORE_3,
	IIMG_CORE_4,

	IIMG_BELT_1	= 2360,
	IIMG_BELT_2,
	IIMG_BELT_3,

	IIMG_CLAW_1 = 2370,
	IIMG_CLAW_2,
	IIMG_CLAW_3,
	
	// chest keys
	IIMG_CKEY_1 = 2600,
	IIMG_CKEY_2,
	IIMG_CKEY_3,
	
	// tokens
	IIMG_TOKEN_ARMORER = 2800,
	IIMG_TOKEN_GUNSMITH,
	IIMG_TOKEN_ARTISAN,
	IIMG_TOKEN_CARTOGRAPHER,

	// flasks
	IIMG_FLASK_LIFE_SMALL = 3000,
	IIMG_FLASK_LIFE_MEDIUM,
	IIMG_FLASK_LIFE_LARGE,
	IIMG_FLASK_LIFE_GRAND,
	IIMG_FLASK_LIFE_EXQUISITE,

	IIMG_FLASK_UTILITY_GRANITE,
	IIMG_FLASK_UTILITY_BASALT,
	IIMG_FLASK_UTILITY_BISMUTH,
	IIMG_FLASK_UTILITY_INSULAR,
	IIMG_FLASK_UTILITY_OAK,
	IIMG_FLASK_UTILITY_ARCANE,
	IIMG_FLASK_UTILITY_DIAMOND,
	IIMG_FLASK_UTILITY_SILVER,
	IIMG_FLASK_UTILITY_SULPHUR,
	IIMG_FLASK_UTILITY_QUICKSILVER,
	IIMG_FLASK_UTILITY_QUARTZ,

	// dungeon keys -- in matching order with dnd_dungeons.h enum
	IIMG_DUNGEONKEY_VOIDKEEP = 4000,

	MAX_ITEM_IMAGES
};

#define DND_SMALLCHARM_IMAGEBEGIN IIMG_SC_1
#define DND_SMALLCHARM_IMAGEEND IIMG_SC_3
#define DND_MEDIUMCHARM_IMAGEBEGIN IIMG_MC_1
#define DND_MEDIUMCHARM_IMAGEEND IIMG_MC_3
#define DND_LARGECHARM_IMAGEBEGIN IIMG_LC_1
#define DND_LARGECHARM_IMAGEEND IIMG_LC_3

#define ITEM_IMAGE_ORB_BEGIN IIMG_ORB_1
#define ITEM_IMAGE_KEY_BEGIN IIMG_CKEY_1
#define ITEM_IMAGE_TOKEN_BEGIN IIMG_TOKEN_ARMORER

#define ITEM_IMAGE_DUNGEONKEY_BEGIN IIMG_DUNGEONKEY_VOIDKEEP
#define ITEM_IMAGE_DUNGEONKEY_END IIMG_DUNGEONKEY_VOIDKEEP

#define ITEM_IMAGE_ARMOR_BEGIN IIMG_ARM_1
#define ITEM_IMAGE_ARMOR_END IIMG_ARM_18

#define ITEM_IMAGE_BOOT_BEGIN IIMG_BOO_1
#define ITEM_IMAGE_BOOT_END IIMG_BOO_12

#define ITEM_IMAGE_HELM_BEGIN IIMG_HLM_1
#define ITEM_IMAGE_HELM_END IIMG_HLM_9

#define ITEM_IMAGE_MONSTERORB_BEGIN IIMG_MORB_1

#define ITEM_IMAGE_SLAYERCARD_BEGIN IIMG_SLAYERCARD_1
#define ITEM_IMAGE_SLAYERCARD_END IIMG_SLAYERCARD_3

#define ITEM_IMAGE_DOGTAG_BEGIN IIMG_DOGTAG_1
#define ITEM_IMAGE_DOGTAG_END IIMG_DOGTAG_3

#define ITEM_IMAGE_SUNGLASSES_BEGIN IIMG_SUNGLASS_1
#define ITEM_IMAGE_SUNGLASSES_END IIMG_SUNGLASS_3

#define ITEM_IMAGE_CIGAR_BEGIN IIMG_CIGAR_1
#define ITEM_IMAGE_CIGAR_END IIMG_CIGAR_3

#define ITEM_IMAGE_POWERRING_BEGIN IIMG_POWERRING_1
#define ITEM_IMAGE_POWERRING_END IIMG_POWERRING_3

#define ITEM_IMAGE_POWERCORE_BEGIN IIMG_CORE_1
#define ITEM_IMAGE_POWERCORE_END IIMG_CORE_4

#define ITEM_IMAGE_BELT_BEGIN IIMG_BELT_1
#define ITEM_IMAGE_BELT_END IIMG_BELT_3

#define ITEM_IMAGE_CLAW_BEGIN IIMG_CLAW_1
#define ITEM_IMAGE_CLAW_END IIMG_CLAW_3

#define ITEM_IMAGE_CHARM_END IIMG_LC_3
#define ITEM_IMAGE_ORB_END IIMG_ORB_31
#define ITEM_IMAGE_MONSTERORB_END IIMG_MORB_6
#define ITEM_IMAGE_KEY_END IIMG_CKEY_3
#define ITEM_IMAGE_TOKEN_END IIMG_TOKEN_CARTOGRAPHER

// uniques
#define ITEM_IMAGE_UCHARM_BEGIN IIMG_UCHRM_1
#define ITEM_IMAGE_UCHARM_END IIMG_UCHRM_22

#define ITEM_IMAGE_DROPONLY_UCHARM_BEGIN IIMG_UDCHRM_1
#define ITEM_IMAGE_DROPONLY_UCHARM_END IIMG_UDCHRM_5

#define ITEM_IMAGE_UCORE_BEGIN IIMG_UCORE_1
#define ITEM_IMAGE_UCORE_END IIMG_UCORE_1

#define ITEM_IMAGE_UBODYARM_BEGIN IIMG_UBODY_1
#define ITEM_IMAGE_UBODYARM_END IIMG_UBODY_3

#define ITEM_IMAGE_UBOOT_BEGIN IIMG_UBOOT_1
#define ITEM_IMAGE_UBOOT_END IIMG_UBOOT_3

#define ITEM_IMAGE_UHELM_BEGIN IIMG_UHELM_1
#define ITEM_IMAGE_UHELM_END IIMG_UHELM_4

#define ITEM_IMAGE_FLASK_BEGIN IIMG_FLASK_LIFE_SMALL
#define ITEM_IMAGE_FLASK_END IIMG_FLASK_UTILITY_QUARTZ

// wide returns wider version
str GetItemImage(int id, bool wide = false) {
	str img_prefix = "";
	int suffix = 0;
	if(id <= ITEM_IMAGE_CHARM_END) {
		if(id >= DND_LARGECHARM_IMAGEBEGIN) {
			suffix = id - DND_LARGECHARM_IMAGEBEGIN + 1;
			img_prefix = "CG";
		}
		else if(id >= DND_MEDIUMCHARM_IMAGEBEGIN) {
			suffix = id - DND_MEDIUMCHARM_IMAGEBEGIN + 1;
			img_prefix = "CM";
		}
		else {
			suffix = id + 1;
			img_prefix = "CS";
		}
	}
	else if(id <= ITEM_IMAGE_UCHARM_END) {
		img_prefix = "UC";
		suffix = id - ITEM_IMAGE_UCHARM_BEGIN + 1;
	}
	else if(id <= ITEM_IMAGE_DROPONLY_UCHARM_END) {
		img_prefix = "UDC";
		suffix = id - ITEM_IMAGE_DROPONLY_UCHARM_BEGIN + 1;
	}
	else if(id <= ITEM_IMAGE_UCORE_END) {
		img_prefix = "UCOR";
		suffix = id - ITEM_IMAGE_UCORE_BEGIN + 1;
	}
	else if(id <= ITEM_IMAGE_UBODYARM_END) {
		img_prefix = "UARM";
		suffix = id - ITEM_IMAGE_UBODYARM_BEGIN + 1;
	}
	else if(id <= ITEM_IMAGE_UBOOT_END) {
		img_prefix = "UBOO";
		suffix = id - ITEM_IMAGE_UBOOT_BEGIN + 1;
	}
	else if(id <= ITEM_IMAGE_UHELM_END) {
		img_prefix = "UHELM";
		suffix = id - ITEM_IMAGE_UHELM_BEGIN + 1;
	}
	else if(id <= ITEM_IMAGE_ORB_END) {
		img_prefix = "O";
		suffix = id - ITEM_IMAGE_ORB_BEGIN + 1;
	}
	else if(id <= ITEM_IMAGE_MONSTERORB_END) {
		img_prefix = "MO";
		suffix = id - ITEM_IMAGE_MONSTERORB_BEGIN + 1;
	}
	else if(id <= ITEM_IMAGE_ARMOR_END) {
		img_prefix = "AR";
		suffix = id - ITEM_IMAGE_ARMOR_BEGIN + 1;
		if(wide)
			img_prefix = "ARW";
	}
	else if(id <= ITEM_IMAGE_BOOT_END)  {
		img_prefix = "BO";
		suffix = id - ITEM_IMAGE_BOOT_BEGIN + 1;
	}
	else if(id <= ITEM_IMAGE_HELM_END) {
		img_prefix = "HL";
		suffix = id - ITEM_IMAGE_HELM_BEGIN + 1;
	}
	else if(id <= ITEM_IMAGE_SLAYERCARD_END) {
		img_prefix = "SC";
		suffix = id - ITEM_IMAGE_SLAYERCARD_BEGIN + 1;
	}
	else if(id <= ITEM_IMAGE_DOGTAG_END) {
		img_prefix = "DT";
		suffix = id - ITEM_IMAGE_DOGTAG_BEGIN + 1;
	}
	else if(id <= ITEM_IMAGE_SUNGLASSES_END) {
		img_prefix = "SG";
		suffix = id - ITEM_IMAGE_SUNGLASSES_BEGIN + 1;
	}
	else if(id <= ITEM_IMAGE_CIGAR_END) {
		img_prefix = "CI";
		suffix = id - ITEM_IMAGE_CIGAR_BEGIN + 1;
	}
	else if(id <= ITEM_IMAGE_POWERRING_END) {
		img_prefix = "RN";
		suffix = id - ITEM_IMAGE_POWERRING_BEGIN + 1;
	}
	else if(id <= ITEM_IMAGE_POWERCORE_END) {
		img_prefix = "PC";
		suffix = id - ITEM_IMAGE_POWERCORE_BEGIN + 1;
	}
	else if(id <= ITEM_IMAGE_BELT_END) {
		img_prefix = "BL";
		suffix = id - ITEM_IMAGE_BELT_BEGIN + 1;
	}
	else if(id <= ITEM_IMAGE_CLAW_END) {
		img_prefix = "CL";
		suffix = id - ITEM_IMAGE_CLAW_BEGIN + 1;
	}
	else if(id <= ITEM_IMAGE_KEY_END) {
		img_prefix = "K";
		suffix = id - ITEM_IMAGE_KEY_BEGIN + 1;
	}
	else if(id <= ITEM_IMAGE_TOKEN_END) {
		img_prefix = "T";
		suffix = id - ITEM_IMAGE_TOKEN_BEGIN + 1;
	}
	else if(id <= ITEM_IMAGE_FLASK_END) {
		// flask
		img_prefix = "FL";
		suffix = id - ITEM_IMAGE_FLASK_BEGIN + 1;
	}
	else {
		// dungeon key
		img_prefix = "DK";
		suffix = id - ITEM_IMAGE_DUNGEONKEY_BEGIN + 1;
	}
	//Log(l:StrParam(d:id, s:" ==>", s:"DND_", s:img_prefix, s:"IMG", d:suffix));
	return StrParam(l:StrParam(s:"DND_", s:img_prefix, s:"IMG", d:suffix));
}

#endif