slider SlimeSlide //Used for all Chex Decals
{
	DistY -15
	SlideTime 1	
}

Decal QuadrumpusSplat1
{
	pic LSB7C0
	randomflipx
	randomflipy
	solid
}

Decal QuadrumpusSplat2
{
	pic LSB7D0
	randomflipx
	randomflipy
	solid
}

Decal QuadrumpusSplat3
{
	pic LSB7E0
	randomflipx
	randomflipy
	solid
}

Decal QuadrumpusSplat4
{
	pic LSB7D0
	randomflipx
	randomflipy 
	solid
}

decal BipedBallSplat1
{
	pic SSL1C0
	randomflipx
	randomflipy
	solid
}

decal BipedBallSplat2
{
	pic SSL1D0 
	randomflipx
	randomflipy
	solid
	animator SlimeSlide
}

decal BipedBallSplat3
{
	pic SSL1E0
	randomflipx
	randomflipy
	solid
	animator SlimeSlide
}

Decal CycloptisSplat1
{
	pic MSB2C0
	randomflipx
	randomflipy
	solid
}

Decal CycloptisSplat2
{
	pic MSB2D0
	randomflipx
	randomflipy
	solid
}



Decal MaximusSplat1
{
	pic LSB7C0
	randomflipx
	randomflipy
	solid
}

Decal MaximusSplat2
{
	pic LSB7D0
	randomflipx
	randomflipy
	solid
}

Decal MaximusSplat3
{
	pic LSB7E0
	randomflipx
	randomflipy
	solid
}

Decal MaximusSplat4
{
	pic LSB7B3B7
	randomflipx
	randomflipy
	solid
}

Decalgroup QuadrumpusSplat
{
	QuadrumpusSplat1 1
	QuadrumpusSplat2 1
	QuadrumpusSplat3 1
	QuadrumpusSplat4 1
}

Decalgroup BipedBallSplat
{
	BipedBallSplat1 1
	BipedBallSplat2 1
	BipedBallSplat3 1
}

Decalgroup CycloptisSplat
{
	CycloptisSplat1 1
	CycloptisSplat2 3
}

Decalgroup MaximusSplat
{
	MaximusSplat1 1
	MaximusSplat2 1
	MaximusSplat3 1
	MaximusSplat4 1
}