[enu default]

// little note: leftimg, rightimg and mugshot DONT NEED TRANSLATING, i know, but at least this way I know they are in memory and not on stack

CLASS_SELECT			= "SELECT YOUR CHARACTER";
CLASS_LOAD				= "LOAD YOUR CHARACTER";
CLASS_TOSELECT			= "to select";
CLASS_OVERWRITE			= "to overwrite existing character";
CLASS_TOCLOSE			= "to close";
CLASS_PRESS				= "Press";
CLASS_INNATE			= "Innate";

// Doomguy

CLASS0_NAME				= "Doomguy";
CLASS0_LEFTIMG			= "P1_LIMG";
CLASS0_RIGHTIMG			= "P1_RIMG";
CLASS0_MUGSHOT			= "STFEVL0";
CLASS0_TEXT				= "The original hero. Mean, tough and ready to kick the ass of the demon menace! "
						  "Milennia of experience fighting demons has certainly taken its toll on him however...    ";

CLASS0_PERK1			= "Mercy Kill";
CLASS0_PERK2			= "Soul Taker"; 
CLASS0_PERK3			= "True Grit"; 
CLASS0_PERK4			= "The Guillotine";
CLASS0_PERK5			= "Striking Fear";

CLASS0_PERK1_DESC		= "Enemies within cull range (15% health) can be executed by pressing '+zoom' key to heal for 15% of maximum health. If an enemy can be executed, they'll do 50% less damage to you.";
CLASS0_PERK2_DESC		= "Demons have 5% chance to drop their essence on kill. Anyone can pick these to heal for 1% of enemy max health (can overheal up to 50%) and gain 25% more damage for 10 seconds. If an enemy is executed, you get the full benefits with damage bonus for 20 seconds instead.";
CLASS0_PERK3_DESC		= "Enemies that can be executed deal 90% less damage to you instead.";
CLASS0_PERK4_DESC		= "Your cull range is 20%.";
CLASS0_PERK5_DESC		= "Your attacks reduce resists of enemies by 33% for 5 seconds. Slain enemies rest in peace.";

// Marine

CLASS1_NAME				= "Marine";
CLASS1_LEFTIMG			= "P2_LIMG";
CLASS1_RIGHTIMG			= "P2_RIMG";
CLASS1_MUGSHOT			= "MAREVL0";
CLASS1_TEXT				= "Marine has been through a lot, military complexes, other dimensions... "
						  "All kinds of evil. And the kinds of evil he's seen, has made him a bit... different.";

CLASS1_PERK1			= "Safety First";
CLASS1_PERK2			= "Loaded Explosives";
CLASS1_PERK3			= "Overhauled Powder";
CLASS1_PERK4			= "Blast Pads";
CLASS1_PERK5			= "Rage Fuel";

CLASS1_PERK1_DESC		= "Your explosives do 25% less self damage.";
CLASS1_PERK2_DESC		= "Your explosive projectiles can't be reflected.";
CLASS1_PERK3_DESC		= "Take 33% less damage from radius damage. Your explosives ignore radius damage immunity.";
CLASS1_PERK4_DESC		= "Losing 40% of your health in the span of two seconds makes you take 50% less damage for 15 seconds. At the end of the buff, gain 1% of your health per 250 damage dealt. This effect can only occur once every 3 minutes. Cooldown reduced per kill by 1 second.";
CLASS1_PERK5_DESC		= "Regular explosives gain 25% chance to trigger again scaling up to 100% per 1% missing health. The effect is maximized at 50% missing health.";

// Hobo

CLASS2_NAME				= "Hobo";
CLASS2_LEFTIMG			= "P3_LIMG";
CLASS2_RIGHTIMG			= "P3_RIMG";
CLASS2_MUGSHOT			= "RENEVL0";
CLASS2_TEXT				= "Can't tie him, a loose cannon. He'll do whatever he god damn pleases because that's just how he is. "
						  "Give him a shotgun and leave the rest to him.";

CLASS2_PERK1			= "Sheer Charisma";
CLASS2_PERK2			= "Locked & Loaded";
CLASS2_PERK3			= "Shotgun Frenzy";
CLASS2_PERK4			= "Amphetamine Boost";
CLASS2_PERK5			= "Shotgun Rampage";

CLASS2_PERK1_DESC		= "Shotgun weapons cost 20% less to buy and research.";
CLASS2_PERK2_DESC		= "Shotguns have 10% resist pierce and 25% more pellets. Every 20 levels afterward additionally increases this pierce by 5% and pellets by 15%.";
CLASS2_PERK3_DESC		= "Hitting the same enemy with any shotgun's standard ammo more than 3 times within 10 seconds triggers 'Shotgun Frenzy', if not already frenzied. During this, shotguns have 25% chance to not use any ammo for 10 seconds, have 33% increased accuracy and gain up to 50% more damage depending on your distance to the enemy.";
CLASS2_PERK4_DESC		= "Once per map, use the '+zoom' key to self-administer a syringe. While active, the user moves 33% faster, gains 20% to mitigation chance and 10% to mitigation effect for 30 seconds.";
CLASS2_PERK5_DESC		= "Shotgun Frenzy instead grants 33% chance to not use ammo, 50% increased accuracy, 100% more damage with distance and kills extend duration by 1 second up to 15 seconds.";

// Punisher

CLASS3_NAME				= "Punisher";
CLASS3_LEFTIMG			= "P4_LIMG";
CLASS3_RIGHTIMG			= "P4_RIMG";
CLASS3_MUGSHOT			= "BADEVL0";
CLASS3_TEXT				= "Was a chill guy, until the fateful day his wife died and his dog was murdered right before his very eyes... "
						  "Ever since, he hasn't been the same, it's as if something ticked in him and he became the greatest murder machine...";

CLASS3_PERK1			= "Retained Tempo";
CLASS3_PERK2			= "Sustenance";
CLASS3_PERK3			= "Headhunter";
CLASS3_PERK4			= "No End in Sight";
CLASS3_PERK5			= "Unstoppable";

CLASS3_PERK1_DESC		= "Being on a killing spree gives 10% movement speed as well as 10% of current weapon's ammo capacity for starting the spree.";
CLASS3_PERK2_DESC		= "During the 'Merciless' killing spree and onwards, gain 2% lifesteal and 10% increased life recovery from lifesteal per tier up to 20% and 100% respectively.";
CLASS3_PERK3_DESC		= "Gain a stacking 6.015% more damage buff when you obtain enough points from kills, up to maxium 200% more damage. Gain 33% increased amount of points if you are in a killing spree.";
CLASS3_PERK4_DESC		= "Killing sprees last 25% longer. You can overleech 50% of the lifesteal amount up to twice your cap, with the overflowing pool taking 33% of the damage taken for you.";
CLASS3_PERK5_DESC		= "During any killing spree, you are immune to bleeding and 20% of the overkill damage on an enemy is leeched as life.";

// Wanderer

CLASS4_NAME				= "Wanderer";
CLASS4_LEFTIMG			= "P5_LIMG";
CLASS4_RIGHTIMG			= "P5_RIMG";
CLASS4_MUGSHOT			= "CRVEVL0";
CLASS4_TEXT				= "The lone wolf, excels in being the only hero to clean up the menace. "
						  "When he sets his gaze upon something, that thing hits the ground, lifeless.";

CLASS4_PERK1			= "Potent Blood";
CLASS4_PERK2			= "Master of Pain";
CLASS4_PERK3			= "Vile Bastion";
CLASS4_PERK4			= "Misery loves Company";
CLASS4_PERK5			= "Astral Form";

CLASS4_PERK1_DESC		= "Debuffs on you expire 25% faster.";
CLASS4_PERK2_DESC		= "Applying ailments to enemies reduce their resists by 10 per different ailment on them.";
CLASS4_PERK3_DESC		= "While you have energy shield, you can't be affected by ailments. Energy shield recovery has 20% chance to start immediately when you inflict an ailment on an enemy.";
CLASS4_PERK4_DESC		= "Enemies killed by you have 25% chance to explode for 15% of their maximum health in a 160 unit radius with a random element. You can't be hurt by this damage.";
CLASS4_PERK5_DESC		= "Once per map, use the '+zoom' key to leave your body behind, becoming ethereal. Gain access to \ctPsionic Wave\c-, which charges up a massive nova to deal incredible damage with 5 second cooldown. "
						  "\ctRay of Disintegration\c-, which can deal constant damage in a line to all enemies in front of you. And \ctEthereal Walk\c-, which lets you travel freely with 4 second cooldown, dealing damage at start and the end. "
						  "Lasts 30 seconds. You return to your body once the effect ends. Press '+zoom' key to end early.";

// Cyborg

CLASS5_NAME				= "Cyborg";
CLASS5_LEFTIMG			= "P6_LIMG";
CLASS5_RIGHTIMG			= "P6_RIMG";
CLASS5_MUGSHOT			= "CYGEVL0";
CLASS5_TEXT				= "Finest specimen from the Russian laboratories, the Cyborg is employed when all negotiations have failed. "
						  "The last thing many see is the cold metallic enforcer's visage, before they perish.";

CLASS5_PERK1			= "Augmented";
CLASS5_PERK2			= "Amplified";
CLASS5_PERK3			= "Instability";
CLASS5_PERK4			= "Volatility";
CLASS5_PERK5			= "Ascension";

CLASS5_PERK1_DESC		= "Cybernetic equipments are 33% more effective.";
CLASS5_PERK2_DESC		= "Recovery effects have 25% chance to not be interrupted on taking damage.";
CLASS5_PERK3_DESC		= "Tech weapons build instability stacks on enemy direct hits, granting +2 flat damage per stack up to 10 stacks. 50% chance to have energy shield recovery start immediately after losing max stacks. Stacks last 5 seconds.";
CLASS5_PERK4_DESC		= "At max instability stacks, your tech weapons may fire additional energy particles. Stacks last an additional 5 seconds.";
CLASS5_PERK5_DESC		= "Half your life becomes energy shield. Lifesteal applies to energy shield at half of its value instead.";

// Berserker

CLASS6_NAME				= "Berserker";
CLASS6_LEFTIMG			= "P7_LIMG";
CLASS6_RIGHTIMG			= "P7_RIMG";
CLASS6_MUGSHOT			= "BEREVL0";
CLASS6_TEXT				= "Hailing from the mountains, his courage, bravery... recklessness, all impeccable tools against destroying demons. "
					      "After having lost his fellow townsfolk to a demon invasion, he volunteered to fight for UAC. It's time for demons to meet Ragnarok.";

CLASS6_PERK1			= "Highlander";
CLASS6_PERK2			= "Enduring Composure";
CLASS6_PERK3			= "Barbaric Strength";
CLASS6_PERK4			= "Relentless Fury";
CLASS6_PERK5			= "God of War";

CLASS6_PERK1_DESC		= "Can carry unlimited melee weapons. Can't buy any super weapon. While holding a melee weapon, gain 20% less damage taken.";
CLASS6_PERK2_DESC		= "Gain stacking 2% damage reduction when hurt up to 30% for 3 seconds. Cooldown of 0.3 seconds between stacks. Heal for 25% of max health at the end at max stacks. Gain 20% chance to recover 8 stamina on kill.";
CLASS6_PERK3_DESC		= "Your melee hits splash on targets hit, dealing 33% of its damage in a cone of 128 unit radius (affected by melee range) and a 120 degree arc.";
CLASS6_PERK4_DESC		= "Melee hits or kills give fury stacks, each granting 10% more melee damage. Max 30 stacks. At max stacks, gain 30% movement speed and 100% crit damage. Lose a stack every 2 seconds off combat.";
CLASS6_PERK5_DESC		= "Once per map, use the '+zoom' key to instantly gain maximum stacks of \"Enduring Composure\" and \"Relentless Fury\" for an extended 30 seconds, after which they can start losing stacks.";
	
// Trickster

CLASS7_NAME				= "Trickster";
CLASS7_LEFTIMG			= "P8_LIMG";
CLASS7_RIGHTIMG			= "P8_RIMG";
CLASS7_MUGSHOT			= "ELENEVL0";

CLASS7_TEXT				= "Not many know the origin of the Trickster, she wanders planes of existence in search of entertainment... Or so many assume, as she seems to relish every encounter. One thing is for sure, when she stops toying with her subjects her true form shows, and it's not pretty.";
CLASS7_PERK1			= "Deadly Maneuvers";
CLASS7_PERK2			= "Opportunistic";
CLASS7_PERK3			= "Shadow Dance";
CLASS7_PERK4			= "Acrobat";
CLASS7_PERK5			= "Doppelganger";

CLASS7_PERK1_DESC		= "Gain 0.1% crit chance per 1% mitigation chance.";
CLASS7_PERK2_DESC		= "20% chance to gain phasing on critical strike. (Phasing grants 4 seconds of projectile damage avoidance)";
CLASS7_PERK3_DESC		= "When your health drops below 40%, create shadow clones that distract every enemy in their path by taunting them. You are phasing when the shadow clone is first created. Cooldown of 90 seconds. Clones last 15 seconds.";
CLASS7_PERK4_DESC		= "You are phasing during dashing. This goes on cooldown after the dash ends for 2 seconds. Phasing lasts 25% longer.";
CLASS7_PERK5_DESC		= "Once per map, use the '+zoom' key to create a single shadow clone that goes towards where you're looking, staying and taunting nearby enemies for 10 seconds. You can swap places with this clone once it reaches its destination, twice before it expires. Cooldown of 90 seconds. Clone lasts 20 seconds.";
