[enu default]

// little note: leftimg, rightimg and mugshot DONT NEED TRANSLATING, i know, but at least this way I know they are in memory and not on stack

CLASS_SELECT			= "SELECT YOUR CHARACTER";
CLASS_TOSELECT			= "to select";
CLASS_TOCLOSE			= "to close";
CLASS_PRESS				= "Press";

// Doomguy

CLASS0_ACTOR 			= "TheDoomguy";
CLASS0_NAME				= "Doomguy";
CLASS0_LEFTIMG			= "P1_LIMG";
CLASS0_RIGHTIMG			= "P1_RIMG";
CLASS0_MUGSHOT			= "STFEVL0";
CLASS0_TEXT				= "The original hero. Mean, tough and ready to kick ass of the demon menace! "
						  "Milennia of experience fighting demons has certainly taken its toll on him however...";

CLASS0_PERK1			= "Damage taken from demons is reduced by 10%.";
CLASS0_PERK2			= "Demons have 5% chance to drop their essence. Anyone can pick these to heal for 1% of enemy max health and gain 18% more damage for 5 seconds.";
CLASS0_PERK3			= "Your attacks reduce resists of demons by 33% for 5 seconds.";

// Marine

CLASS1_ACTOR 			= "TheMarine";
CLASS1_NAME				= "Marine";
CLASS1_LEFTIMG			= "P2_LIMG";
CLASS1_RIGHTIMG			= "P2_RIMG";
CLASS1_MUGSHOT			= "MAREVL0";
CLASS1_TEXT				= "Marine has been through a lot, military complexes, other dimensions... "
						  "All kinds of evil. And the kinds of evil he's seen, has made him a bit... different.";

CLASS1_PERK1			= "Your explosives do 25% less self damage. Explosive projectiles can't be reflected";
CLASS1_PERK2			= "Enemy explosives deal 33% less damage. Explosives ignore radius damage immunity.";
CLASS1_PERK3			= "Losing 50% of your health in the span of a second makes you take 50% less damage for 15 seconds. At the end of the buff, gain 1% of your health per 250 damage dealt. This effect can only occur once every 3 minutes. Cooldown reduced per kill by 1 second.";

// Hobo

CLASS2_ACTOR 			= "TheHobo";
CLASS2_NAME				= "Hobo";
CLASS2_LEFTIMG			= "P3_LIMG";
CLASS2_RIGHTIMG			= "P3_RIMG";
CLASS2_MUGSHOT			= "RENEVL0";
CLASS2_TEXT				= "Can't tie him, a loose cannon. He'll do whatever he god damn pleases because that's just how he is. "
						  "Give him a shotgun and leave the rest to him.";

CLASS2_PERK1			= "Shotgun weapons have 25% discount.";
CLASS2_PERK2			= "Shotguns have 25% resist penetration, and have 50% more pellets.";
CLASS2_PERK3			= "Hitting the same enemy with any shotgun more than 3 times within 10 seconds triggers \ciShotgun Frenzy\c-, if not already frenzied. During this, shotguns don't consume any ammo for 10 seconds, have 50% increased accuracy and gain up to 100% more damage depending on your distance to the enemy. Each kill extends the frenzy by 1 second up to a maximum of 20 seconds.";

// Punisher

CLASS3_ACTOR 			= "ThePunisher";
CLASS3_NAME				= "Punisher";
CLASS3_LEFTIMG			= "P4_LIMG";
CLASS3_RIGHTIMG			= "P4_RIMG";
CLASS3_MUGSHOT			= "BADEVL0";
CLASS3_TEXT				= "Was a chill guy, until the fateful day his wife died and his dog was murdered right before his very eyes... "
						  "Ever since, he hasn't been the same, it's as if something ticked in him and he became the greatest murder machine...";

CLASS3_PERK1			= "Being on a killing spree gives 10% movement speed as well as 10% of current weapon's ammo capacity for starting the spree.";
CLASS3_PERK2			= "At the end of at least the \ckMerciless\c- killing spree, heal for 24% plus 8% per spree of your max health.";
CLASS3_PERK3			= "Every 10 kills you get increases your damage by 4% for that map. Caps at 400%.";

// Wanderer

CLASS4_ACTOR 			= "TheWanderer";
CLASS4_NAME				= "Wanderer";
CLASS4_LEFTIMG			= "P5_LIMG";
CLASS4_RIGHTIMG			= "P5_RIMG";
CLASS4_MUGSHOT			= "CRVEVL0";
CLASS4_TEXT				= "The lone wolf, excels in being the only hero to clean up the menace. "
						  "When he sets his gaze upon something, that thing hits the ground, lifeless.";

CLASS4_PERK1			= "Poison damage taken reduced by 75%.";
CLASS4_PERK2			= "Elemental and Occult attacks and spells do 25% more damage.";
CLASS4_PERK3			= "Enemies killed by you have 25% chance to explode for 5% of their maximum health in a 100 unit radius with a random elemental damage. You can't be hurt by this damage.";

// Cyborg

CLASS5_ACTOR 			= "TheCyborg";
CLASS5_NAME				= "Cyborg";
CLASS5_LEFTIMG			= "P6_LIMG";
CLASS5_RIGHTIMG			= "P6_RIMG";
CLASS5_MUGSHOT			= "CYGEVL0";
CLASS5_TEXT				= "Finest specimen from the Russian laboratories, the Cyborg is employed when all negotiations have failed. "
						  "The last thing many see is the cold metallic enforcer's visage, before they perish.";

CLASS5_PERK1			= "Cybernetic equipments are 30% more effective.";
CLASS5_PERK2			= "Can make use of Power Cores in the equipment slot.";
CLASS5_PERK3			= "Tech weapons build instability stacks on enemy direct hits, granting +2 flat damage per stack up to 10 stacks. At max stacks, your tech weapons may fire additional energy particles. Stacks last 5 seconds. 50% chance to have energy shield recovery start immediately after losing max stacks.";

// Berserker

CLASS6_ACTOR 			= "TheBerserker";
CLASS6_NAME				= "Berserker";
CLASS6_LEFTIMG			= "P7_LIMG";
CLASS6_RIGHTIMG			= "P7_RIMG";
CLASS6_MUGSHOT			= "BEREVL0";
CLASS6_TEXT				= "Hailing from the mountains, his courage, bravery... recklessness, all impeccable tools against destroying demons. "
					      "After having lost his fellow townsfolk to a demon invasion, he volunteered to fight for UAC. It's time for demons to meet Ragnarok.";

CLASS6_PERK1			= "Can carry unlimited melee weapons. Can't buy any super weapon.";
CLASS6_PERK2			= "Gain 2% damage reduction when hurt up to 30% for 3 seconds. Cooldown of 0.3 seconds. Heal for 15% of max health at the end at max stacks.";
CLASS6_PERK3			= "Melee hits or kills give 8% damage. Max 30 stacks. At max stacks, +30% movement speed and +50% crit damage. Lose a stack every 2 seconds off combat.";