[enu default]

// little note: leftimg, rightimg and mugshot DONT NEED TRANSLATING, i know, but at least this way I know they are in memory and not on stack

CLASS_SELECT			= "SELECT YOUR CHARACTER";
CLASS_LOAD				= "LOAD YOUR CHARACTER";
CLASS_TOSELECT			= "to select";
CLASS_OVERWRITE			= "to overwrite existing character";
CLASS_TOCLOSE			= "to close";
CLASS_PRESS				= "Press";

// Doomguy

CLASS0_NAME				= "Doomguy";
CLASS0_LEFTIMG			= "P1_LIMG";
CLASS0_RIGHTIMG			= "P1_RIMG";
CLASS0_MUGSHOT			= "STFEVL0";
CLASS0_TEXT				= "The original hero. Mean, tough and ready to kick the ass of the demon menace! "
						  "Milennia of experience fighting demons has certainly taken its toll on him however...    ";

CLASS0_PERK1			= "Enemies within cull range (15% health by default) can be executed by pressing '+zoom' key to heal for 15% of maximum health. If an enemy can be executed, they'll do 90% less damage to you.";
CLASS0_PERK2			= "Demons have 5% chance to drop their essence on kill. Anyone can pick these to heal for 1% of enemy max health (can overheal up to 50%) and gain 25% more damage for 10 seconds. If an enemy is executed, you get the full benefits with damage bonus for 20 seconds instead.";
CLASS0_PERK3			= "Your attacks reduce resists of enemies by 33% for 5 seconds. Slain enemies rest in peace.";

// Marine

CLASS1_NAME				= "Marine";
CLASS1_LEFTIMG			= "P2_LIMG";
CLASS1_RIGHTIMG			= "P2_RIMG";
CLASS1_MUGSHOT			= "MAREVL0";
CLASS1_TEXT				= "Marine has been through a lot, military complexes, other dimensions... "
						  "All kinds of evil. And the kinds of evil he's seen, has made him a bit... different.";

CLASS1_PERK1			= "Your explosives do 25% less self damage. Your explosive projectiles can't be reflected";
CLASS1_PERK2			= "Enemy radius damage deals 33% less damage. Your explosives ignore radius damage immunity.";
CLASS1_PERK3			= "Losing 40% of your health in the span of a two seconds makes you take 50% less damage for 15 seconds. At the end of the buff, gain 1% of your health per 250 damage dealt. This effect can only occur once every 3 minutes. Cooldown reduced per kill by 1 second.";

// Hobo

CLASS2_NAME				= "Hobo";
CLASS2_LEFTIMG			= "P3_LIMG";
CLASS2_RIGHTIMG			= "P3_RIMG";
CLASS2_MUGSHOT			= "RENEVL0";
CLASS2_TEXT				= "Can't tie him, a loose cannon. He'll do whatever he god damn pleases because that's just how he is. "
						  "Give him a shotgun and leave the rest to him.";

CLASS2_PERK1			= "Shotgun weapons have 25% discount.";
CLASS2_PERK2			= "Shotguns have 25% resist penetration, and have 50% more pellets.";
CLASS2_PERK3			= "Hitting the same enemy with any shotgun's standard ammo more than 3 times within 10 seconds triggers 'Shotgun Frenzy', if not already frenzied. During this, shotguns have 30% chance to not use any ammo for 12 seconds, have 50% increased accuracy and gain up to 100% more damage depending on your distance to the enemy. Each kill extends the frenzy by 1 second up to a maximum of 20 seconds.";

// Punisher

CLASS3_NAME				= "Punisher";
CLASS3_LEFTIMG			= "P4_LIMG";
CLASS3_RIGHTIMG			= "P4_RIMG";
CLASS3_MUGSHOT			= "BADEVL0";
CLASS3_TEXT				= "Was a chill guy, until the fateful day his wife died and his dog was murdered right before his very eyes... "
						  "Ever since, he hasn't been the same, it's as if something ticked in him and he became the greatest murder machine...";

CLASS3_PERK1			= "Being on a killing spree gives 10% movement speed as well as 10% of current weapon's ammo capacity for starting the spree.";
CLASS3_PERK2			= "During the 'Merciless' killing spree and onwards, gain 2% lifesteal and 10% increased life recovery from lifesteal per tier up to 20% and 100% respectively.";
CLASS3_PERK3			= "Gain a stacking 6.015% more damage buff when you obtain enough points from kills, up to maxium 200% more damage. Gain 33% increased amount of points if you are in a killing spree.";

// Wanderer

CLASS4_NAME				= "Wanderer";
CLASS4_LEFTIMG			= "P5_LIMG";
CLASS4_RIGHTIMG			= "P5_RIMG";
CLASS4_MUGSHOT			= "CRVEVL0";
CLASS4_TEXT				= "The lone wolf, excels in being the only hero to clean up the menace. "
						  "When he sets his gaze upon something, that thing hits the ground, lifeless.";

CLASS4_PERK1			= "Debuffs on you last 25% less.";
CLASS4_PERK2			= "Applying ailments to enemies reduce their resists by 10 per different ailment on them.";
CLASS4_PERK3			= "Enemies killed by you have 25% chance to explode for 10% of their maximum health in a 160 unit radius with a random elemental damage. You can't be hurt by this damage.";

// Cyborg

CLASS5_NAME				= "Cyborg";
CLASS5_LEFTIMG			= "P6_LIMG";
CLASS5_RIGHTIMG			= "P6_RIMG";
CLASS5_MUGSHOT			= "CYGEVL0";
CLASS5_TEXT				= "Finest specimen from the Russian laboratories, the Cyborg is employed when all negotiations have failed. "
						  "The last thing many see is the cold metallic enforcer's visage, before they perish.";

CLASS5_PERK1			= "Cybernetic equipments are 33% more effective.";
CLASS5_PERK2			= "Can make use of Power Cores in the equipment slot.";
CLASS5_PERK3			= "Tech weapons build instability stacks on enemy direct hits, granting +2 flat damage per stack up to 10 stacks. At max stacks, your tech weapons may fire additional energy particles. Stacks last 5 seconds. 50% chance to have energy shield recovery start immediately after losing max stacks.";

// Berserker

CLASS6_NAME				= "Berserker";
CLASS6_LEFTIMG			= "P7_LIMG";
CLASS6_RIGHTIMG			= "P7_RIMG";
CLASS6_MUGSHOT			= "BEREVL0";
CLASS6_TEXT				= "Hailing from the mountains, his courage, bravery... recklessness, all impeccable tools against destroying demons. "
					      "After having lost his fellow townsfolk to a demon invasion, he volunteered to fight for UAC. It's time for demons to meet Ragnarok.";

CLASS6_PERK1			= "Can carry unlimited melee weapons. Can't buy any super weapon.";
CLASS6_PERK2			= "Gain 2% damage reduction when hurt up to 30% for 3 seconds. Cooldown of 0.3 seconds. Heal for 15% of max health at the end at max stacks.";
CLASS6_PERK3			= "Melee hits or kills give 8% damage. Max 30 stacks. At max stacks, +30% movement speed and +50% crit damage. Lose a stack every 2 seconds off combat.";

// Trickster

CLASS7_NAME				= "Trickster";
CLASS7_LEFTIMG			= "P8_LIMG";
CLASS7_RIGHTIMG			= "P8_RIMG";
CLASS7_MUGSHOT			= "ELENEVL0";

CLASS7_TEXT				= "Not many know the origin of the Trickster, she wanders planes of existence in search of entertainment... Or so many assume, as she seems to relish every encounter. One thing is for sure, when she stops toying with her subjects her true form shows, and it's not pretty.";
CLASS7_PERK1			= "Critical strike chance is increased by half of mitigation chance.";
CLASS7_PERK2			= "10% chance to gain phasing on critical strike. (Phasing grants 3 seconds of projectile damage avoidance)";
CLASS7_PERK3			= "When your health drops below 33%, create a shadow clone that runs towards the last enemy that hit you, distracting every enemy in its path by taunting them for 5 seconds. You are phasing when the shadow clone is first created. Cooldown of 90 seconds. Clone lasts 15 seconds.";
