$pitchshiftrange 2

// Abyssal

abyssal_human/sight1		"Sounds/Monsters/Incursion/Abyssal/sfposit1.ogg"
abyssal_human/sight2		"Sounds/Monsters/Incursion/Abyssal/sfposit2.ogg"
abyssal_human/sight3		"Sounds/Monsters/Incursion/Abyssal/sfposit3.ogg"
$random abyssal_human/sight { abyssal_human/sight1 abyssal_human/sight2 abyssal_human/sight3 }
abyssal_human/active		"Sounds/Monsters/Incursion/Abyssal/sfposact.ogg"
abyssal_human/death1		"Sounds/Monsters/Incursion/Abyssal/sfpodth1.ogg"
abyssal_human/death2		"Sounds/Monsters/Incursion/Abyssal/sfpodth2.ogg"
abyssal_human/death3		"Sounds/Monsters/Incursion/Abyssal/sfpodth3.ogg"
$random abyssal_human/death { abyssal_human/death1 abyssal_human/death2 abyssal_human/death3 }
abyssal_human/pain			"Sounds/Monsters/Incursion/Abyssal/sfpopain.ogg"

abyssal_human/gunshot		"Sounds/Monsters/Incursion/Abyssal/sfpistol.ogg"
abyssal_human/shotgun		"Sounds/Monsters/Incursion/Abyssal/sfdshtgn.ogg"
abyssal_demon/fireball		"Sounds/Monsters/Incursion/Abyssal/sffirsht.ogg"
abyssal_demon/fireballhit	"Sounds/Monsters/Incursion/Abyssal/sffirxpl.ogg"
abyssal_arachno/attack		"Sounds/Monsters/Incursion/Abyssal/sfplasma.ogg"

abyssal_demon/sight			"Sounds/Monsters/Incursion/Abyssal/sfsgtsit.ogg"
abyssal_demon/death			"Sounds/Monsters/Incursion/Abyssal/sfsgtdth.ogg"
abyssal_demon/attack		"Sounds/Monsters/Incursion/Abyssal/sfsgtatk.ogg"
abyssal_demon/pain			"Sounds/Monsters/Incursion/Abyssal/sfdmpain.ogg"
abyssal_demon/active		"Sounds/Monsters/Incursion/Abyssal/sfdmact.ogg"

abyssal_caco/sight			"Sounds/Monsters/Incursion/Abyssal/sfcacsit.ogg"
abyssal_caco/death			"Sounds/Monsters/Incursion/Abyssal/sfcacdth.ogg"

abyssal_lostsoul/attack		"Sounds/Monsters/Incursion/Abyssal/sfsklatk.ogg"

abyssal_pain/sight			"Sounds/Monsters/Incursion/Abyssal/sfpesit.ogg"
abyssal_pain/pain			"Sounds/Monsters/Incursion/Abyssal/sfpepain.ogg" // lol
abyssal_pain/death			"Sounds/Monsters/Incursion/Abyssal/sfpedth.ogg"

abyssal_knight/sight		"Sounds/Monsters/Incursion/Abyssal/sfkntsit.ogg"
abyssal_knight/pain			"Sounds/Monsters/Incursion/Abyssal/sfbdpain.ogg"
abyssal_knight/death		"Sounds/Monsters/Incursion/Abyssal/sfkntdth.ogg"

abyssal_baron/sight			"Sounds/Monsters/Incursion/Abyssal/sfbrssit.ogg"
abyssal_baron/death			"Sounds/Monsters/Incursion/Abyssal/sfbrsdth.ogg"

abyssal_fatso/sight			"Sounds/Monsters/Incursion/Abyssal/sfmansit.ogg"
abyssal_fatso/pain			"Sounds/Monsters/Incursion/Abyssal/sfmnpain.ogg"
abyssal_fatso/death			"Sounds/Monsters/Incursion/Abyssal/sfmandth.ogg"
abyssal_fatso/attack		"Sounds/Monsters/Incursion/Abyssal/sfmanatk.ogg"

abyssal_arachno/sight		"Sounds/Monsters/Incursion/Abyssal/sfbspsit.ogg"
abyssal_arachno/death		"Sounds/Monsters/Incursion/Abyssal/sfbspdth.ogg"
abyssal_arachno/walk		"Sounds/Monsters/Incursion/Abyssal/sfbspwlk.ogg"
abyssal_arachno/active		"Sounds/Monsters/Incursion/Abyssal/sfbspact.ogg"

abyssal_vile/sight			"Sounds/Monsters/Incursion/Abyssal/sfvilsit.ogg"
abyssal_vile/pain			"Sounds/Monsters/Incursion/Abyssal/sfvilpn.ogg"
abyssal_vile/death			"Sounds/Monsters/Incursion/Abyssal/sfvildth.ogg"
abyssal_vile/active			"Sounds/Monsters/Incursion/Abyssal/sfvilact.ogg"
abyssal_vile/fire			"Sounds/Monsters/Incursion/Abyssal/sfvilfir.ogg"
abyssal_vile/attack			"Sounds/Monsters/Incursion/Abyssal/sfvilatk.ogg"

abyssal_spider/sight		"Sounds/Monsters/Incursion/Abyssal/sfspisit.ogg"
abyssal_spider/death		"Sounds/Monsters/Incursion/Abyssal/sfspidth.ogg"

abyssal_cyber/sight			"Sounds/Monsters/Incursion/Abyssal/sfcybsit.ogg"
abyssal_cyber/death			"Sounds/Monsters/Incursion/Abyssal/sfcybdth.ogg"
abyssal_cyber/hoof			"Sounds/Monsters/Incursion/Abyssal/sfhoof.ogg"
abyssal_cyber/metal			"Sounds/Monsters/Incursion/Abyssal/sfmetal.ogg"

abyssal_hound/sight			"Sounds/Monsters/Incursion/Abyssal/HH_SIGHT.ogg"
abyssal_hound/attack		"Sounds/Monsters/Incursion/Abyssal/HH_ATACK.ogg"
abyssal_hound/death			"Sounds/Monsters/Incursion/Abyssal/HH_DEATH.ogg"

abyssal_mother/sight		"Sounds/Monsters/Incursion/Abyssal/sfrectsi.ogg"
abyssal_mother/pain			"Sounds/Monsters/Incursion/Abyssal/sfrectpn.ogg"
abyssal_mother/active		"Sounds/Monsters/Incursion/Abyssal/sfrectac.ogg"
abyssal_mother/death		"Sounds/Monsters/Incursion/Abyssal/sfrectdi.ogg"
abyssal_mother/attack		"Sounds/Monsters/Incursion/Abyssal/sfrectat.ogg"

// Chex
// Common Flemoid



$random qgrunt/sight 		{ qgrunt/sight1  qgrunt/sight2  qgrunt/sight3 }
$random qgrunt/death		{ qgrunt/death1  qgrunt/death2  qgrunt/death3 }
qgrunt/sight1			"Sounds/Monsters/Incursion/Chex/cqposit1.ogg"
qgrunt/sight2			"Sounds/Monsters/Incursion/Chex/cqposit2.ogg"
qgrunt/sight3			"Sounds/Monsters/Incursion/Chex/cqposit3.ogg"
qgrunt/active			"Sounds/Monsters/Incursion/Chex/cqcommon.ogg"
qgrunt/pain				"Sounds/Monsters/Incursion/Chex/cqpopain.ogg"
qgrunt/death1			"Sounds/Monsters/Incursion/Chex/cqpodth1.ogg"
qgrunt/death2			"Sounds/Monsters/Incursion/Chex/cqpodth2.ogg"
qgrunt/death3			"Sounds/Monsters/Incursion/Chex/cqpodth3.ogg"
$pitchshiftrange 5
qgrunt/attack			"Sounds/Monsters/Incursion/Chex/dssplat1.ogg"

$limit qgrunt/sight 0
$limit qgrunt/death 0
$limit qgrunt/active 0
$limit qgrunt/pain 0
$limit qgrunt/attack 0

$rolloff qgrunt/sight 200 2400
$rolloff qgrunt/death 200 2400
$rolloff qgrunt/active 200 2400
$rolloff qgrunt/pain 200 2400
$rolloff qgrunt/attack 200 2400

// Bipedal Flemoid
$pitchshiftrange 4
$random qshotguy/sight		{ qshotguy/sight1  qshotguy/sight2  qshotguy/sight3 }
$random qshotguy/death		{ qshotguy/death1  qshotguy/death2  qshotguy/death3 }
qshotguy/sight1			"Sounds/Monsters/Incursion/Chex/cqposit1.ogg"
qshotguy/sight2			"Sounds/Monsters/Incursion/Chex/cqposit2.ogg"
qshotguy/sight3			"Sounds/Monsters/Incursion/Chex/cqposit3.ogg"
qshotguy/active			"Sounds/Monsters/Incursion/Chex/cqcommon.ogg"
qshotguy/pain			"Sounds/Monsters/Incursion/Chex/cqpopain.ogg"
qshotguy/death1			"Sounds/Monsters/Incursion/Chex/cqpodth1.ogg"
qshotguy/death2			"Sounds/Monsters/Incursion/Chex/cqpodth2.ogg"
qshotguy/death3			"Sounds/Monsters/Incursion/Chex/cqpodth3.ogg"
$pitchshiftrange 5
qshotguy/attack			"Sounds/Monsters/Incursion/Chex/dssplat2.ogg"

$limit qshotguy/sight 0
$limit qshotguy/death 0
$limit qshotguy/active 0
$limit qshotguy/pain 0
$limit qshotguy/attack 0

$rolloff qshotguy/sight 200 2400
$rolloff qshotguy/death 200 2400
$rolloff qshotguy/active 200 2400
$rolloff qshotguy/pain 200 2400
$rolloff qshotguy/attack 200 2400


// Stridicus
$pitchshiftrange 4
q3demon/sight 			"Sounds/Monsters/Incursion/Chex/cqcybsit.ogg"
q3demon/death			"Sounds/Monsters/Incursion/Chex/cqspidth.ogg"
q3demon/active			"Sounds/Monsters/Incursion/Chex/dsstrid1.ogg"
q3demon/pain			"Sounds/Monsters/Incursion/Chex/cqpopain.ogg"
$pitchshiftrange 5
q3demon/melee			"Sounds/Monsters/Incursion/Chex/dsstrid2.ogg"

$limit q3demon/sight 0
$limit q3demon/death 0
$limit q3demon/active 0
$limit q3demon/pain 0
$limit q3demon/melee 0

$rolloff q3demon/sight 200 2400
$rolloff q3demon/death 200 2400
$rolloff q3demon/active 200 2400
$rolloff q3demon/pain 200 2400
$rolloff q3demon/melee 200 2400


// Flem Mine
$pitchshiftrange 4
q3skull/active			"Sounds/Monsters/Incursion/Chex/dsflem3.ogg"
q3skull/pain			"Sounds/Monsters/Incursion/Chex/dsflem2.ogg"
q3skull/melee			"Sounds/Monsters/Incursion/Chex/dsflem1.ogg"
$pitchshiftrange 5
q3skull/death			"Sounds/Monsters/Incursion/Chex/cqpodth1.ogg"
asplode					"Sounds/Monsters/Incursion/Chex/cqrlaunc.ogg"

$limit asplode 0
$limit q3skull/death 0
$limit q3skull/active 0
$limit q3skull/pain 0
$limit q3skull/melee 0

$rolloff asplode 500 2400
$rolloff q3skull/death 200 2400
$rolloff q3skull/active 300 2400
$rolloff q3skull/pain 200 2400
$rolloff q3skull/melee 200 2400



// Flembomination
$pitchshiftrange 4
q3spider/sight			"Sounds/Monsters/Incursion/Chex/dsbomin1.ogg"
q3spider/active			"Sounds/Monsters/Incursion/Chex/dsbomin2.ogg"
q3spider/pain			"Sounds/Monsters/Incursion/Chex/dsbomin3.ogg"
$pitchshiftrange 5
q3spider/attack			"Sounds/Monsters/Incursion/Chex/dsbomin4.ogg"
$pitchshiftrange 4
q3spider/death			"Sounds/Monsters/Incursion/Chex/cqspidth.ogg"

$limit q3spider/sight 0
$limit q3spider/death 0
$limit q3spider/active 0
$limit q3spider/pain 0
$limit q3spider/attack 0

$rolloff q3spider/sight 400 2400
$rolloff q3spider/death 2400 3600
$rolloff q3spider/active 200 2400
$rolloff q3spider/pain 200 2400
$rolloff q3spider/attack 250 2400


// Lord Snotfolus

q3cyber/sight			"Sounds/Monsters/Incursion/Chex/dssnotf1.ogg"
q3cyber/active			"Sounds/Monsters/Incursion/Chex/dssnotf3.ogg"
q3cyber/pain			"Sounds/Monsters/Incursion/Chex/dssnotf2.ogg"
q3cyber/death			"Sounds/Monsters/Incursion/Chex/cqcybdth.ogg"

$limit q3cyber/sight 0
$limit q3cyber/death 0
$limit q3cyber/active 0
$limit q3cyber/pain 0

$rolloff q3cyber/sight 400 2400
$rolloff q3cyber/death 2400 3600
$rolloff q3cyber/active 200 2400
$rolloff q3cyber/pain 200 2400


// Armored Bipedicus/Quadrumpus

$random qimp/sight		{ qimp/sight1  qimp/sight2 }
$random qimp/death		{ qimp/death1  qimp/death2 }
qimp/sight1			"Sounds/Monsters/Incursion/Chex/cqbgsit1.ogg"
qimp/sight2			"Sounds/Monsters/Incursion/Chex/cqbgsit2.ogg"
qimp/active			"Sounds/Monsters/Incursion/Chex/cqbgact.ogg"
qimp/pain			"Sounds/Monsters/Incursion/Chex/cqpopain.ogg"
$pitchshiftrange 5
qimp/melee			"Sounds/Monsters/Incursion/Chex/dssplat2.ogg"
qimp/shotx			"Sounds/Monsters/Incursion/Chex/dssplat3.ogg"
$pitchshiftrange 4
qimp/death1			"Sounds/Monsters/Incursion/Chex/cqbgdth1.ogg"
qimp/death2			"Sounds/Monsters/Incursion/Chex/cqbgdth2.ogg"
$pitchshiftrange 5
qimp/attack			"Sounds/Monsters/Incursion/Chex/cqfirsht.ogg"

$limit qimp/sight 0
$limit qimp/death 0
$limit qimp/active 0
$limit qimp/pain 0
$limit qimp/attack 0
$limit qimp/melee 0
$limit qimp/shotx 0

$rolloff qimp/sight 200 2400
$rolloff qimp/death 200 2400
$rolloff qimp/active 200 2400
$rolloff qimp/pain 200 2400
$rolloff qimp/attack 200 2400
$rolloff qimp/melee 200 2400
$rolloff qimp/shotx 250 2400


// Cyclops/Larva
$pitchshiftrange 4
qspectre/sight			"Sounds/Monsters/Incursion/Chex/cqsgtsit.ogg"
qspectre/active			"Sounds/Monsters/Incursion/Chex/cqdmact.ogg"
qspectre/pain			"Sounds/Monsters/Incursion/Chex/cqdmpain.ogg"
$pitchshiftrange 5
qspectre/melee			"Sounds/Monsters/Incursion/Chex/cqsgtatk.ogg"
$pitchshiftrange 4
qspectre/death			"Sounds/Monsters/Incursion/Chex/cqsgtdth.ogg"

$limit qspectre/sight 0
$limit qspectre/death 0
$limit qspectre/active 0
$limit qspectre/pain 0
$limit qspectre/melee 0

$rolloff qspectre/sight 200 2400
$rolloff qspectre/death 200 2400
$rolloff qspectre/active 200 2400
$rolloff qspectre/pain 200 2400
$rolloff qspectre/melee 200 2400


// Super Cyclops Flemoid

qcaco/sight				"Sounds/Monsters/Incursion/Chex/cqsgtsit.ogg"
qcaco/active			"Sounds/Monsters/Incursion/Chex/cqdmact.ogg"
qcaco/pain				"Sounds/Monsters/Incursion/Chex/cqdmpain.ogg"
qcaco/death				"Sounds/Monsters/Incursion/Chex/cqcacdth.ogg"
$pitchshiftrange 5
qcaco/attack			"Sounds/Monsters/Incursion/Chex/cqfirsht.ogg"
qcaco/shotx				"Sounds/Monsters/Incursion/Chex/dssplat4.ogg"

$limit qcaco/sight 0
$limit qcaco/death 0
$limit qcaco/active 0
$limit qcaco/pain 0
$limit qcaco/attack 0
$limit qcaco/shotx 0

$rolloff qcaco/sight 200 2400
$rolloff qcaco/death 200 2400
$rolloff qcaco/active 200 2400
$rolloff qcaco/pain 200 2400
$rolloff qcaco/attack 200 2400
$rolloff qcaco/shotx 225 2400


// Maximus
$pitchshiftrange 4
qbaron/sight			"Sounds/Monsters/Incursion/Chex/cqbrssit.ogg"
qbaron/active			"Sounds/Monsters/Incursion/Chex/cqdmact.ogg"
qbaron/pain				"Sounds/Monsters/Incursion/Chex/cqdmpain.ogg"
$pitchshiftrange 5
qbaron/melee			"Sounds/Monsters/Incursion/Chex/cqclaw.ogg"
$pitchshiftrange 4
qbaron/death			"Sounds/Monsters/Incursion/Chex/cqbrsdth.ogg"
$pitchshiftrange 5
qbaron/attack			"Sounds/Monsters/Incursion/Chex/cqfirsht.ogg"
qbaron/shotx			"Sounds/Monsters/Incursion/Chex/dssplat4.ogg"
flemb/summon			"Sounds/Monsters/Incursion/Chex/cqrlaunc.ogg"

$limit qbaron/sight 0
$limit qbaron/death 0
$limit qbaron/active 0
$limit qbaron/pain 0
$limit qbaron/attack 0
$limit qbaron/shotx 0
$limit flemb/summon 0

$rolloff qbaron/sight 300 2400
$rolloff qbaron/death 200 2400
$rolloff qbaron/active 200 2400
$rolloff qbaron/pain 200 2400
$rolloff qbaron/attack 200 2400
$rolloff qbaron/shotx 250 2400
$rolloff flemb/summon 200 2400