#ifndef DND_SPELLTABLES_IN
#define DND_SPELLTABLES_IN

#include "DnD_SpellDefs.h"

#define SPELL_DEF(ID, TREE, LVL, FLAGS, X, Y) \
	id = ID; \
	SpellDefs[id].scale_mask = 0; \
	SpellDefs[id].drain_mask = 0; \
	SpellDefs[id].tree = TREE; \
	SpellDefs[id].req_level = LVL; \
	SpellDefs[id].flags = FLAGS; \
	SpellDefs[id].tx = X; \
	SpellDefs[id].ty = Y

#define SPELL_VAL(W, B, P) \
	SpellDefs[id].base[W] = B; \
	SpellDefs[id].per_rank[W] = P

// Opt a field into the compounding rank curve. Only real damage dealt to something belongs
// here -- DAMAGE also carries percents, mana regen, armour ratings and minion health
// depending on the spell, and those stay on the linear per_rank step alone.
#define SPELL_SCALE(W) \
	SpellDefs[id].scale_mask |= 1 << (W)

// Mark a field as a SELF cost paid in health. Gentler curve than mana, see DND_SPELL_DRAINGROWSHARE.
#define SPELL_DRAIN(W) \
	SpellDefs[id].drain_mask |= 1 << (W)

#define SPELL_REQ(N, S, R) \
	SpellDefs[id].req_spell[N] = (S) + 1; \
	SpellDefs[id].req_rank[N] = R

#define SPELL_SYN(T, S, F, V, FL) \
	SpellSynergies[syn].target = (T) + 1; \
	SpellSynergies[syn].source = S; \
	SpellSynergies[syn].field = F; \
	SpellSynergies[syn].per_rank = V; \
	SpellSynergies[syn].flags = FL; \
	++syn

// Rank 5 and rank 10 bonuses are NOT in this table. They are one-off behaviour changes rather than
// numbers on a curve, so the cast code asks SpellThresholdMet and branches -- a rank never gets its
// own actor or its own row.
void InitSpellDefs() {
	int id, syn = 0, i;

	// zero every row first: the terminator is a zero target, and this is a global
	for(i = 0; i < MAX_SPELL_SYNERGIES; ++i)
		SpellSynergies[i].target = 0;

	// ============================== FIRE ==============================

	SPELL_DEF(SPL_BLAZE, DND_SKILLTREE_FIRE, 1, 0, 3, 0);
	SPELL_VAL(SPELLVAL_DAMAGE,		8,		4);
	SPELL_VAL(SPELLVAL_COST,		8.0,	0.8);
	SPELL_VAL(SPELLVAL_CASTTIME,	1.0,	0);
	SPELL_VAL(SPELLVAL_DURATION,	3.0,	0);
	SPELL_VAL(SPELLVAL_CDR,			0,		8.0);
	SPELL_VAL(SPELLVAL_RADIUS,		96,		0);
	SPELL_SCALE(SPELLVAL_DAMAGE);

	SPELL_DEF(SPL_FIREBALL, DND_SKILLTREE_FIRE, 1, SPLF_PROJECTILE, 4, 0);
	SPELL_VAL(SPELLVAL_DAMAGE,		100,	25);
	SPELL_VAL(SPELLVAL_COST,		5.0,	1.0);
	SPELL_VAL(SPELLVAL_CASTTIME,	0.65,	0);
	SPELL_VAL(SPELLVAL_AMOUNT,		1,		0);
	SPELL_SCALE(SPELLVAL_DAMAGE);

	SPELL_DEF(SPL_INFERNALSTRIKE, DND_SKILLTREE_FIRE, 8, SPLF_REQ_ANY, 3, 1);
	SPELL_VAL(SPELLVAL_DAMAGE,		50,		25);
	SPELL_VAL(SPELLVAL_COST,		6.0,	1.0);
	SPELL_VAL(SPELLVAL_COOLDOWN,	3.0,	0);
	SPELL_VAL(SPELLVAL_RADIUS,		128,	0);
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_REQ(0, SPL_BLAZE, 2);
	SPELL_REQ(1, SPL_FIREBALL, 2);

	SPELL_DEF(SPL_WARMTH, DND_SKILLTREE_FIRE, 8, SPLF_REQ_ANY | SPLF_SUPPORT, 5, 1);
	SPELL_VAL(SPELLVAL_DAMAGE,		50,		10);	// percent mana regen
	SPELL_VAL(SPELLVAL_DAMAGE2,		0,		0.25);	// flat mana regen per rank
	SPELL_VAL(SPELLVAL_COST,		10.0,	1.0);
	SPELL_VAL(SPELLVAL_COOLDOWN,	30.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	1.0,	0);
	SPELL_VAL(SPELLVAL_DURATION,	8.0,	0);
	SPELL_VAL(SPELLVAL_RADIUS,		192,	0);
	SPELL_REQ(0, SPL_BLAZE, 4);
	SPELL_REQ(1, SPL_FIREBALL, 4);

	SPELL_DEF(SPL_HEATSHIELD, DND_SKILLTREE_FIRE, 16, SPLF_TARGETED | SPLF_ALLYTARGET | SPLF_SUPPORT, 7, 2);
	SPELL_VAL(SPELLVAL_DAMAGE,		100,	25);	// armor rating granted
	SPELL_VAL(SPELLVAL_COST,		10.0,	2.0);
	SPELL_VAL(SPELLVAL_COOLDOWN,	3.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	1.0,	0);
	SPELL_VAL(SPELLVAL_DURATION,	5.0,	1.0);
	SPELL_REQ(0, SPL_WARMTH, 1);

	SPELL_DEF(SPL_INCINERATE, DND_SKILLTREE_FIRE, 16, SPLF_PASSIVE, 5, 2);
	SPELL_VAL(SPELLVAL_DAMAGE,		5.0,	0.25);	// percent of max health
	SPELL_VAL(SPELLVAL_DAMAGE2,		30,		0);		// percent chance
	SPELL_VAL(SPELLVAL_RADIUS,		128,	0);
	SPELL_REQ(0, SPL_WARMTH, 3);

	SPELL_DEF(SPL_BOILINGBLOOD, DND_SKILLTREE_FIRE, 24, SPLF_REQ_ANY | SPLF_SUPPORT, 5, 3);
	SPELL_VAL(SPELLVAL_DAMAGE,		25,		1);		// percent move speed
	SPELL_VAL(SPELLVAL_DAMAGE2,		5,		1);		// health lost per second -- this spell's whole cost
	SPELL_DRAIN(SPELLVAL_DAMAGE2);
	SPELL_VAL(SPELLVAL_COOLDOWN,	8.0,	0);
	SPELL_VAL(SPELLVAL_DURATION,	10.0,	0);
	SPELL_VAL(SPELLVAL_CDR,			15.0,	0);
	SPELL_REQ(0, SPL_INCINERATE, 1);
	SPELL_REQ(1, SPL_FIREJET, 1);
	SPELL_REQ(2, SPL_HEATSHIELD, 1);

	SPELL_DEF(SPL_ANGER, DND_SKILLTREE_FIRE, 24, SPLF_PASSIVE | SPLF_AURA | SPLF_RESERVES | SPLF_REQ_ANY | SPLF_SUPPORT, 6, 3);
	SPELL_VAL(SPELLVAL_DAMAGE,		15.0,	1.0);	// more fire damage
	SPELL_VAL(SPELLVAL_DAMAGE2,		10,		0);		// base ignite chance
	SPELL_VAL(SPELLVAL_COST,		30.0,	0);		// reservation percent
	SPELL_VAL(SPELLVAL_RADIUS,		256,	8);
	SPELL_REQ(0, SPL_INCINERATE, 1);
	SPELL_REQ(1, SPL_FIREJET, 1);
	SPELL_REQ(2, SPL_HEATSHIELD, 1);

	SPELL_DEF(SPL_PYROBLAST, DND_SKILLTREE_FIRE, 16, SPLF_PROJECTILE | SPLF_REQ_ANY, 2, 2);
	SPELL_VAL(SPELLVAL_DAMAGE,		360,	60);
	SPELL_VAL(SPELLVAL_COST,		12.0,	1.8);
	SPELL_VAL(SPELLVAL_CASTTIME,	2.0,	0);
	SPELL_VAL(SPELLVAL_RADIUS,		128,	0);
	SPELL_VAL(SPELLVAL_AMOUNT,		30,		0);		// full damage core, PERCENT of the blast radius
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_REQ(0, SPL_BLAZE, 4);
	SPELL_REQ(1, SPL_FIREBALL, 4);
	SPELL_SYN(SPL_PYROBLAST, SPL_BLAZE, SPELLVAL_DAMAGE, 5.0, SYNF_MORE);
	SPELL_SYN(SPL_PYROBLAST, SPL_FIREBALL, SPELLVAL_RADIUS, 5.0, SYNF_MORE);

	SPELL_DEF(SPL_SEARINGBOND, DND_SKILLTREE_FIRE, 24, 0, 2, 3);
	SPELL_VAL(SPELLVAL_DAMAGE,		75,		25);
	SPELL_VAL(SPELLVAL_COST,		18.0,	1.2);
	SPELL_VAL(SPELLVAL_COOLDOWN,	15.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	2.0,	0);
	SPELL_VAL(SPELLVAL_DURATION,	2.5,	0.25);
	SPELL_VAL(SPELLVAL_RADIUS,		160,	0);
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_REQ(0, SPL_PYROBLAST, 3);

	SPELL_DEF(SPL_SCORCHINGRAY, DND_SKILLTREE_FIRE, 24, SPLF_CHANNELED, 1, 3);
	SPELL_VAL(SPELLVAL_DAMAGE,		80,		20);
	SPELL_VAL(SPELLVAL_COST,		3.0,	0.333);
	SPELL_VAL(SPELLVAL_CASTTIME,	0.35,	0);
	SPELL_VAL(SPELLVAL_DURATION,	5.0,	0);		// exposure duration
	SPELL_VAL(SPELLVAL_RADIUS,		0,		8);		// beam length bonus
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_REQ(0, SPL_PYROBLAST, 2);

	SPELL_DEF(SPL_FLAMMABILITY, DND_SKILLTREE_FIRE, 30, SPLF_CURSE | SPLF_TARGETED, 0, 3);
	SPELL_VAL(SPELLVAL_DAMAGE,		30,		1);		// resistance reduction
	SPELL_VAL(SPELLVAL_DAMAGE2,		25,		0);		// base ignite chance
	SPELL_VAL(SPELLVAL_COST,		30.0,	2.0);
	SPELL_VAL(SPELLVAL_COOLDOWN,	5.0,	0);
	SPELL_VAL(SPELLVAL_DURATION,	8.0,	0);
	SPELL_VAL(SPELLVAL_RADIUS,		256,	0);
	SPELL_REQ(0, SPL_PYROBLAST, 1);

	SPELL_DEF(SPL_IMMOLATION, DND_SKILLTREE_FIRE, 36, 0, 2, 4);
	SPELL_VAL(SPELLVAL_DAMAGE,		72,		24);
	SPELL_VAL(SPELLVAL_COST,		10.0,	1.0);	// per second
	SPELL_VAL(SPELLVAL_COOLDOWN,	8.0,	0);
	SPELL_VAL(SPELLVAL_RADIUS,		96,		12);
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_REQ(0, SPL_INFERNALSTRIKE, 1);
	SPELL_REQ(1, SPL_SEARINGBOND, 1);
	SPELL_SYN(SPL_IMMOLATION, SPL_INFERNALSTRIKE, SPELLVAL_DAMAGE, 6.0, SYNF_MORE);

	SPELL_DEF(SPL_RAINOFFIRE, DND_SKILLTREE_FIRE, 40, SPLF_TARGETED, 1, 5);
	SPELL_VAL(SPELLVAL_DAMAGE,		40,		16);
	SPELL_VAL(SPELLVAL_COST,		25.0,	2.5);
	SPELL_VAL(SPELLVAL_COOLDOWN,	10.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	1.0,	0);
	SPELL_VAL(SPELLVAL_DURATION,	4.5,	0);
	SPELL_VAL(SPELLVAL_RADIUS,		72,		8);
	SPELL_VAL(SPELLVAL_AMOUNT,		320,	0);		// scatter radius
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_REQ(0, SPL_IMMOLATION, 1);
	SPELL_SYN(SPL_RAINOFFIRE, SPL_VOLCANO, SPELLVAL_AMOUNT, 1, SYNF_FLAT);

	SPELL_DEF(SPL_FLAMEPILLAR, DND_SKILLTREE_FIRE, 36, 0, 5, 4);
	SPELL_VAL(SPELLVAL_DAMAGE,		24,		8);
	SPELL_VAL(SPELLVAL_COST,		20.0,	2.0);
	SPELL_VAL(SPELLVAL_COOLDOWN,	12.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	2.0,	0);
	SPELL_VAL(SPELLVAL_DURATION,	2.0,	0);
	SPELL_VAL(SPELLVAL_RADIUS,		96,		0);
	SPELL_VAL(SPELLVAL_AMOUNT,		12,		0);		// tic count
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_SYN(SPL_FLAMEPILLAR, SPL_BLAZE, SPELLVAL_DAMAGE, 2.5, SYNF_MORE);
	SPELL_SYN(SPL_FLAMEPILLAR, SPL_FIREBALL, SPELLVAL_RADIUS, 5.0, SYNF_MORE);
	SPELL_SYN(SPL_FLAMEPILLAR, SPL_PYROBLAST, SPELLVAL_DAMAGE, 2.5, SYNF_MORE);

	SPELL_DEF(SPL_FIREJET, DND_SKILLTREE_FIRE, 16, SPLF_PROJECTILE, 6, 2);
	SPELL_VAL(SPELLVAL_DAMAGE,		180,	60);
	SPELL_VAL(SPELLVAL_DAMAGE2,		36,		12);
	SPELL_VAL(SPELLVAL_COST,		15.0,	1.5);
	SPELL_VAL(SPELLVAL_COOLDOWN,	4.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	1.5,	0);
	SPELL_VAL(SPELLVAL_RADIUS,		128,	0);
	SPELL_VAL(SPELLVAL_DURATION,	0.75,	0);	// flight time, and so how far it reaches
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_SCALE(SPELLVAL_DAMAGE2);
	SPELL_REQ(0, SPL_WARMTH, 3);
	SPELL_SYN(SPL_FIREJET, SPL_BLAZE, SPELLVAL_DAMAGE, 2.5, SYNF_MORE);
	SPELL_SYN(SPL_FIREJET, SPL_FIREBALL, SPELLVAL_DAMAGE, 2.55, SYNF_MORE);
	SPELL_SYN(SPL_FIREJET, SPL_PYROBLAST, SPELLVAL_DAMAGE, 5.0, SYNF_MORE);

	SPELL_DEF(SPL_FIREDEMON, DND_SKILLTREE_FIRE, 45, SPLF_SUMMON, 5, 5);
	SPELL_VAL(SPELLVAL_DAMAGE,		650,	50);	// minion health
	SPELL_VAL(SPELLVAL_DAMAGE2,		0,		10);	// percent more minion damage
	SPELL_VAL(SPELLVAL_COST,		60.0,	5.0);
	SPELL_VAL(SPELLVAL_COOLDOWN,	75.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	1.5,	0);

	// No DURATION: this summon is permanent, so there is nothing for spell duration gear to
	// stretch and nothing for the panel to promise.

	// How many may be out at once. The pet cap on its own would let a roster be nothing but these,
	// which is the thing this stops. Safe on AMOUNT: that field doubles as the full damage core for
	// EXPLOSIVE spells, and the demon's fireball is a plain projectile that never reads it.
	SPELL_VAL(SPELLVAL_AMOUNT,		1,		0);		// max active at once

	SPELL_REQ(0, SPL_FLAMEPILLAR, 3);
	SPELL_SYN(SPL_FIREDEMON, SPL_WARMTH, SPELLVAL_DAMAGE, 2.5, SYNF_MORE);

	SPELL_DEF(SPL_MOLTENBOULDER_S, DND_SKILLTREE_FIRE, 45, SPLF_PROJECTILE, 6, 5);
	SPELL_VAL(SPELLVAL_DAMAGE,		24,		6);		// travel
	SPELL_VAL(SPELLVAL_DAMAGE2,		256,	48);	// impact
	SPELL_VAL(SPELLVAL_RADIUS,		96,		0);		// roll blast; the impact one is 200% of this
	SPELL_VAL(SPELLVAL_COST,		60.0,	4.0);
	SPELL_VAL(SPELLVAL_COOLDOWN,	35.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	2.5,	0);
	SPELL_VAL(SPELLVAL_DURATION,	6.0,	0);
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_SCALE(SPELLVAL_DAMAGE2);
	SPELL_REQ(0, SPL_FLAMEPILLAR, 2);
	SPELL_SYN(SPL_MOLTENBOULDER_S, SPL_BLAZE, SPELLVAL_DAMAGE, 2.5, SYNF_MORE);
	SPELL_SYN(SPL_MOLTENBOULDER_S, SPL_FIREBALL, SPELLVAL_DAMAGE2, 2.5, SYNF_MORE);
	SPELL_SYN(SPL_MOLTENBOULDER_S, SPL_PYROBLAST, SPELLVAL_DAMAGE, 2.5, SYNF_MORE);

	SPELL_DEF(SPL_RIGHTEOUSFIRE, DND_SKILLTREE_FIRE, 40, 0, 3, 5);
	SPELL_VAL(SPELLVAL_DAMAGE,		50,		2);		// percent of health and shield
	SPELL_VAL(SPELLVAL_DAMAGE2,		20,		0);		// percent more spell damage
	SPELL_VAL(SPELLVAL_COOLDOWN,	1.0,	0);
	SPELL_VAL(SPELLVAL_RADIUS,		256,	16);	// Spell_RighteousFireFX Scale tracks the BASE
	SPELL_REQ(0, SPL_FLAMEPILLAR, 2);
	SPELL_SYN(SPL_RIGHTEOUSFIRE, SPL_IMMOLATION, SPELLVAL_RADIUS, 8, SYNF_FLAT);

	SPELL_DEF(SPL_ANNIHILUS, DND_SKILLTREE_FIRE, 52, SPLF_CHANNELED | SPLF_TARGETED, 6, 6);
	SPELL_VAL(SPELLVAL_DAMAGE,		250,	25);	// per 0.5s channelled
	SPELL_VAL(SPELLVAL_COST,		50.0,	5.0);
	SPELL_VAL(SPELLVAL_COOLDOWN,	45.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	0.5,	0);
	SPELL_VAL(SPELLVAL_DURATION,	2.5,	0);		// max channel
	SPELL_VAL(SPELLVAL_RADIUS,		96,		0);
	SPELL_VAL(SPELLVAL_AMOUNT,		512,	0);		// max target range
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_REQ(0, SPL_MOLTENBOULDER_S, 4);
	// this extends maximum channel time by 0.25
	SPELL_SYN(SPL_ANNIHILUS, SPL_MOLTENBOULDER_S, SPELLVAL_DURATION, 0.25, SYNF_FLAT);

	// Area of effect, which for a spell IS the radius field: GetSpellValue applies PSTAT_SPELL_AOE
	// to SPELLVAL_RADIUS linearly, so a percent here means the same thing spell area gear means.
	// It rides the whole ramp, since the blast lerps from this row toward FULLRADIUS.
	SPELL_SYN(SPL_ANNIHILUS, SPL_RIGHTEOUSFIRE, SPELLVAL_RADIUS, 10.0, SYNF_MORE);

	// Centred on the last row between Volcano and Annihilus. RESERVES, so it holds mana for as long
	// as it is switched on, and PASSIVE, so it never reaches the hotbar and can be toggled.
	SPELL_DEF(SPL_HEARTOFFIRE, DND_SKILLTREE_FIRE, 45, SPLF_PASSIVE | SPLF_RESERVES | SPLF_SUPPORT, 4, 6);
	SPELL_VAL(SPELLVAL_DAMAGE,		10.0,	0.75);	// percent of MAX cooldown removed per proc
	SPELL_VAL(SPELLVAL_DAMAGE2,		25,		5);		// percent chance to proc
	SPELL_VAL(SPELLVAL_COST,		20.0,	0);		// reservation percent
	SPELL_VAL(SPELLVAL_DURATION,	4.0,	0);		// rank 5 window
	SPELL_VAL(SPELLVAL_AMOUNT,		20,		0);		// rank 5 percent MORE damage

	SPELL_DEF(SPL_VOLCANO, DND_SKILLTREE_FIRE, 52, SPLF_TARGETED | SPLF_REQ_ANY, 2, 6);
	SPELL_VAL(SPELLVAL_DAMAGE,		60,		0);
	SPELL_VAL(SPELLVAL_COST,		100.0,	15.0);
	SPELL_VAL(SPELLVAL_COOLDOWN,	60.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	2.0,	0);
	SPELL_VAL(SPELLVAL_DURATION,	10.0,	0.5);
	SPELL_VAL(SPELLVAL_RADIUS,		80,		0);

	// Rocks per ERUPTION, not per cast: the cone erupts once per pass of its DECORATE loop, so the
	// total follows from DURATION, which is what this spell ranks up.
	//
	// DAMAGE2 rather than AMOUNT. AMOUNT is not a free slot for an EXPLOSIVE spell -- "DnD Spell
	// Explosion Setup" reads it as the percent of the blast that takes FULL damage, so a 4 there
	// quietly gave every rock a 4% core and put the rest of its radius under falloff.
	SPELL_VAL(SPELLVAL_DAMAGE2,		4,		0);		// rocks per eruption
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_REQ(0, SPL_IMMOLATION, 1);
	SPELL_REQ(1, SPL_RIGHTEOUSFIRE, 1);

	// Percent per rank of the source, accumulated additively and applied once -- "increased", not
	// "more", despite the flag name. Same shape as every other non-FLAT synergy in this table.
	SPELL_SYN(SPL_VOLCANO, SPL_IMMOLATION, SPELLVAL_DAMAGE2, 10.0, SYNF_MORE);

	// ============================== COLD ==============================
	// Reconciled against .claude/SpellDesign/Ice.txt. Values the doc does not state are marked
	// GUESS and are feel numbers, not design.

	SPELL_DEF(SPL_ICEBOLT, DND_SKILLTREE_ICE, 1, SPLF_PROJECTILE, 3, 0);
	SPELL_VAL(SPELLVAL_DAMAGE,		80,		25);
	SPELL_VAL(SPELLVAL_DAMAGE2,		30,		0);		// slow percent; 75 at rank 5
	SPELL_VAL(SPELLVAL_COST,		5.0,	1.0);
	SPELL_VAL(SPELLVAL_CASTTIME,	1.0,	0);
	SPELL_VAL(SPELLVAL_RADIUS,		96,		0);		// rank 10 only: splash on impact
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_SYN(SPL_ICEBOLT, SPL_GLACIALSPIKE, SPELLVAL_DAMAGE, 2.5, SYNF_MORE);
	SPELL_SYN(SPL_ICEBOLT, SPL_FROSTSHARDS, SPELLVAL_DAMAGE, 2.5, SYNF_MORE);
	SPELL_SYN(SPL_ICEBOLT, SPL_WINTERORB, SPELLVAL_DAMAGE, 5.0, SYNF_MORE);

	SPELL_DEF(SPL_FREEZINGPULSE, DND_SKILLTREE_ICE, 1, 0, 0, 0);
	SPELL_VAL(SPELLVAL_DAMAGE,		50,		15);
	SPELL_VAL(SPELLVAL_DAMAGE2,		20,		0);		// freeze chance at the muzzle, 0 at max range
	SPELL_VAL(SPELLVAL_COST,		6.0,	1.0);
	SPELL_VAL(SPELLVAL_CASTTIME,	0.65,	0);
	SPELL_VAL(SPELLVAL_RADIUS,		500,	0);		// travel range. +25% at rank 5
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_SYN(SPL_FREEZINGPULSE, SPL_CREEPINGFROST, SPELLVAL_DAMAGE, 5.0, SYNF_MORE);
	SPELL_SYN(SPL_FREEZINGPULSE, SPL_GUSTOFFROST, SPELLVAL_RADIUS, 5.0, SYNF_MORE);

	SPELL_DEF(SPL_GLACIALSPIKE, DND_SKILLTREE_ICE, 8, SPLF_PROJECTILE, 3, 1);
	SPELL_VAL(SPELLVAL_DAMAGE,		100,	10);
	SPELL_VAL(SPELLVAL_COST,		12.0,	1.8);
	SPELL_VAL(SPELLVAL_COOLDOWN,	2.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	0.75,	0);
	SPELL_VAL(SPELLVAL_DURATION,	1.0,	0);		// shatter freeze; 2.0 at rank 5
	SPELL_VAL(SPELLVAL_AMOUNT,		10,		0);		// rip count
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_REQ(0, SPL_ICEBOLT, 3);
	SPELL_SYN(SPL_GLACIALSPIKE, SPL_ICEBOLT, SPELLVAL_DAMAGE, 5.0, SYNF_MORE);
	SPELL_SYN(SPL_GLACIALSPIKE, SPL_FREEZINGPULSE, SPELLVAL_AMOUNT, 1, SYNF_FLAT);

	SPELL_DEF(SPL_CHILLINGBREATH, DND_SKILLTREE_ICE, 8, SPLF_CHANNELED, 4, 1);
	SPELL_VAL(SPELLVAL_DAMAGE,		40,		10);	// per 0.5s tick
	SPELL_VAL(SPELLVAL_COST,		4.0,	0.5);	// per 0.5s tick
	SPELL_VAL(SPELLVAL_COOLDOWN,	2.0,	0);
	SPELL_VAL(SPELLVAL_RADIUS,		320,	0);		// GUESS: cone reach. 30% wider at rank 10
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_REQ(0, SPL_ICEBOLT, 3);
	SPELL_SYN(SPL_CHILLINGBREATH, SPL_ICEBOLT, SPELLVAL_DAMAGE, 3.0, SYNF_MORE);

	SPELL_DEF(SPL_CREEPINGFROST, DND_SKILLTREE_ICE, 9, SPLF_PROJECTILE, 0, 1);
	SPELL_VAL(SPELLVAL_DAMAGE,		30,		10);	// impact
	SPELL_VAL(SPELLVAL_DAMAGE2,		125,	20);	// per second while crawling
	SPELL_VAL(SPELLVAL_COST,		10.0,	1.0);
	SPELL_VAL(SPELLVAL_COOLDOWN,	2.5,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	0.5,	0);
	SPELL_VAL(SPELLVAL_DURATION,	5.0,	0);		// +2.0 at rank 5
	SPELL_VAL(SPELLVAL_AMOUNT,		6,		0);		// GUESS: crawl speed, units a tic
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_SCALE(SPELLVAL_DAMAGE2);
	SPELL_REQ(0, SPL_FREEZINGPULSE, 2);
	SPELL_SYN(SPL_CREEPINGFROST, SPL_GUSTOFFROST, SPELLVAL_AMOUNT, 3.0, SYNF_MORE);
	SPELL_SYN(SPL_CREEPINGFROST, SPL_FREEZINGPULSE, SPELLVAL_DAMAGE2, 2.5, SYNF_MORE);

	SPELL_DEF(SPL_ICESHIELD_S, DND_SKILLTREE_ICE, 12, SPLF_SUPPORT, 1, 1);
	SPELL_VAL(SPELLVAL_DAMAGE,		200,	25);	// health per barrier
	SPELL_VAL(SPELLVAL_COST,		25.0,	3.0);
	SPELL_VAL(SPELLVAL_COOLDOWN,	20.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	3.0,	0);
	SPELL_VAL(SPELLVAL_DURATION,	5.0,	0.5);	// +2.5 at rank 5
	SPELL_VAL(SPELLVAL_AMOUNT,		8,		0);		// barriers
	SPELL_REQ(0, SPL_ICEBOLT, 2);

	SPELL_DEF(SPL_FROSTSHARDS, DND_SKILLTREE_ICE, 16, SPLF_PROJECTILE, 3, 2);
	SPELL_VAL(SPELLVAL_DAMAGE,		30,		5);		// per shard
	SPELL_VAL(SPELLVAL_COST,		20.0,	1.5);
	SPELL_VAL(SPELLVAL_COOLDOWN,	5.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	1.5,	0);
	SPELL_VAL(SPELLVAL_DURATION,	1.5,	0);		// how long it keeps launching
	SPELL_VAL(SPELLVAL_AMOUNT,		5,		0);		// shards per 0.5s; +2 at rank 5
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_REQ(0, SPL_GLACIALSPIKE, 2);
	SPELL_SYN(SPL_FROSTSHARDS, SPL_GLACIALSPIKE, SPELLVAL_DAMAGE, 2.5, SYNF_MORE);
	SPELL_SYN(SPL_FROSTSHARDS, SPL_ICEBOLT, SPELLVAL_DAMAGE, 2.5, SYNF_MORE);

	SPELL_DEF(SPL_GUSTOFFROST, DND_SKILLTREE_ICE, 16, 0, 4, 2);
	SPELL_VAL(SPELLVAL_DAMAGE2,		30,		0);		// slow percent; 60 at rank 5
	SPELL_VAL(SPELLVAL_COST,		18.0,	1.2);
	SPELL_VAL(SPELLVAL_COOLDOWN,	25.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	2.5,	0);
	SPELL_VAL(SPELLVAL_RADIUS,		512,	0);		// GUESS: how far the gust pushes
	SPELL_VAL(SPELLVAL_CDR,			0,		10.0);
	SPELL_REQ(0, SPL_CHILLINGBREATH, 2);

	SPELL_DEF(SPL_FROSTBOMB, DND_SKILLTREE_ICE, 18, SPLF_TARGETED, 5, 2);
	SPELL_VAL(SPELLVAL_DAMAGE,		60,		5);		// per pulse
	SPELL_VAL(SPELLVAL_COST,		15.0,	1.0);
	SPELL_VAL(SPELLVAL_COOLDOWN,	8.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	0.5,	0);
	SPELL_VAL(SPELLVAL_DURATION,	5.0,	0);
	SPELL_VAL(SPELLVAL_RADIUS,		128,	0);		// 180 at rank 10
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_REQ(0, SPL_CHILLINGBREATH, 2);

	SPELL_DEF(SPL_ICENOVA, DND_SKILLTREE_ICE, 14, 0, 0, 2);
	SPELL_VAL(SPELLVAL_DAMAGE,		250,	50);
	SPELL_VAL(SPELLVAL_COST,		20.0,	2.0);
	SPELL_VAL(SPELLVAL_COOLDOWN,	1.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	1.5,	0);
	SPELL_VAL(SPELLVAL_RADIUS,		320,	18);
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_REQ(0, SPL_ICESHIELD_S, 1);
	// WHOLE number: RADIUS is a plain integer field, so a fractional literal here would be read as
	// fixed point and land as hundreds of thousands of units.
	SPELL_SYN(SPL_ICENOVA, SPL_ICESHIELD_S, SPELLVAL_RADIUS, 12, SYNF_FLAT);

	SPELL_DEF(SPL_ICEGOLEM, DND_SKILLTREE_ICE, 20, SPLF_SUMMON, 1, 2);
	SPELL_VAL(SPELLVAL_DAMAGE,		500,	50);	// minion health
	SPELL_VAL(SPELLVAL_DAMAGE2,		50,		5);		// melee; the dash is a multiple of this
	SPELL_VAL(SPELLVAL_COST,		25.0,	2.5);
	SPELL_VAL(SPELLVAL_COOLDOWN,	30.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	3.0,	0);
	SPELL_VAL(SPELLVAL_AMOUNT,		1,		0);		// max active at once, as the fire demon
	SPELL_REQ(0, SPL_ICESHIELD_S, 3);
	SPELL_SYN(SPL_ICEGOLEM, SPL_ICESHIELD_S, SPELLVAL_DAMAGE, 2.0, SYNF_MORE);
	SPELL_SYN(SPL_ICEGOLEM, SPL_GUSTOFFROST, SPELLVAL_DAMAGE, 2.0, SYNF_MORE);

	SPELL_DEF(SPL_HATRED, DND_SKILLTREE_ICE, 24, SPLF_PASSIVE | SPLF_AURA | SPLF_RESERVES | SPLF_SUPPORT, 4, 4);
	SPELL_VAL(SPELLVAL_DAMAGE,		15.0,	1.5);	// more cold damage
	SPELL_VAL(SPELLVAL_COST,		30.0,	0);		// reservation percent
	SPELL_VAL(SPELLVAL_RADIUS,		256,	0);		// doubled at rank 5
	SPELL_REQ(0, SPL_ICESHIELD_S, 2);

	SPELL_DEF(SPL_FROSTBITE, DND_SKILLTREE_ICE, 30, SPLF_CURSE | SPLF_TARGETED | SPLF_REQ_ANY, 5, 4);
	SPELL_VAL(SPELLVAL_DAMAGE,		30,		1);		// cold resistance reduction
	SPELL_VAL(SPELLVAL_DAMAGE2,		25,		0);		// base chill chance
	SPELL_VAL(SPELLVAL_COST,		30.0,	2.0);
	SPELL_VAL(SPELLVAL_COOLDOWN,	5.0,	0);
	SPELL_VAL(SPELLVAL_DURATION,	8.0,	0);		// +4.0 at rank 10
	SPELL_VAL(SPELLVAL_RADIUS,		256,	0);		// +25% at rank 5
	SPELL_REQ(0, SPL_FROSTSHARDS, 1);
	SPELL_REQ(1, SPL_FROSTBOMB, 1);

	SPELL_DEF(SPL_BLIZZARD, DND_SKILLTREE_ICE, 32, SPLF_TARGETED, 3, 4);
	SPELL_VAL(SPELLVAL_DAMAGE,		90,		18);	// per ice
	SPELL_VAL(SPELLVAL_COST,		60.0,	5.0);
	SPELL_VAL(SPELLVAL_COOLDOWN,	18.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	2.0,	0);
	SPELL_VAL(SPELLVAL_DURATION,	5.0,	0);
	SPELL_VAL(SPELLVAL_RADIUS,		64,		0);		// blast of one ice
	SPELL_VAL(SPELLVAL_AMOUNT,		256,	0);		// storm radius; +128 at rank 5
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_REQ(0, SPL_FROSTSHARDS, 3);
	SPELL_REQ(1, SPL_GUSTOFFROST, 2);
	SPELL_SYN(SPL_BLIZZARD, SPL_FROSTSHARDS, SPELLVAL_DAMAGE, 5.0, SYNF_MORE);
	SPELL_SYN(SPL_BLIZZARD, SPL_GLACIALSPIKE, SPELLVAL_DAMAGE, 2.5, SYNF_MORE);
	SPELL_SYN(SPL_BLIZZARD, SPL_ICEBOLT, SPELLVAL_AMOUNT, 12, SYNF_FLAT);

	SPELL_DEF(SPL_WINTERORB, DND_SKILLTREE_ICE, 36, SPLF_PROJECTILE, 1, 4);
	SPELL_VAL(SPELLVAL_DAMAGE,		100,	50);
	SPELL_VAL(SPELLVAL_DAMAGE2,		30,		0);		// slow percent
	SPELL_VAL(SPELLVAL_COST,		80.0,	4.0);
	SPELL_VAL(SPELLVAL_COOLDOWN,	20.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	3.0,	0);
	SPELL_VAL(SPELLVAL_DURATION,	0.75,	0);		// slow, and the freeze from rank 5
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_REQ(0, SPL_GUSTOFFROST, 1);
	SPELL_REQ(1, SPL_ICEGOLEM, 2);
	SPELL_SYN(SPL_WINTERORB, SPL_ICEBOLT, SPELLVAL_DAMAGE, 5.0, SYNF_MORE);
	SPELL_SYN(SPL_WINTERORB, SPL_FROSTSHARDS, SPELLVAL_DAMAGE, 2.5, SYNF_MORE);
	// DURATION is fixed point, so a fractional literal is correct here where RADIUS would not be.
	SPELL_SYN(SPL_WINTERORB, SPL_GUSTOFFROST, SPELLVAL_DURATION, 0.2, SYNF_FLAT);

	SPELL_DEF(SPL_ICESPEAR, DND_SKILLTREE_ICE, 24, SPLF_PROJECTILE | SPLF_REQ_ANY, 0, 3);
	SPELL_VAL(SPELLVAL_DAMAGE,		50,		5);		// first phase
	SPELL_VAL(SPELLVAL_DAMAGE2,		250,	25);	// evolved
	SPELL_VAL(SPELLVAL_COST,		35.0,	2.5);
	SPELL_VAL(SPELLVAL_COOLDOWN,	5.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	0.5,	0);
	// Travel speed, NOT the rip count: the doc gives the spear a travel speed synergy and a FLAT
	// rip count of 10, so the constant one is a define and the field goes to the thing that moves.
	SPELL_VAL(SPELLVAL_AMOUNT,		20,		0);		// GUESS: first phase speed
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_SCALE(SPELLVAL_DAMAGE2);
	SPELL_REQ(0, SPL_ICENOVA, 2);
	SPELL_REQ(1, SPL_ICEGOLEM, 2);
	SPELL_SYN(SPL_ICESPEAR, SPL_ICEBOLT, SPELLVAL_DAMAGE2, 5.0, SYNF_MORE);
	SPELL_SYN(SPL_ICESPEAR, SPL_ICENOVA, SPELLVAL_AMOUNT, 2.5, SYNF_MORE);

	SPELL_DEF(SPL_GLACIALCASCADE, DND_SKILLTREE_ICE, 44, 0, 0, 4);
	SPELL_VAL(SPELLVAL_DAMAGE,		200,	50);	// first burst; each later one is 20% over the last
	SPELL_VAL(SPELLVAL_COST,		45.0,	3.5);
	SPELL_VAL(SPELLVAL_COOLDOWN,	8.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	1.0,	0);
	SPELL_VAL(SPELLVAL_RADIUS,		512,	0);		// GUESS: how far the wave advances. +25% at rank 5
	SPELL_VAL(SPELLVAL_AMOUNT,		4,		0);		// bursts
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_REQ(0, SPL_ICESPEAR, 2);
	SPELL_SYN(SPL_GLACIALCASCADE, SPL_ICESPEAR, SPELLVAL_DAMAGE, 5.0, SYNF_MORE);
	SPELL_SYN(SPL_GLACIALCASCADE, SPL_GLACIALSPIKE, SPELLVAL_RADIUS, 2.5, SYNF_MORE);

	SPELL_DEF(SPL_SHIVERINGARMOR, DND_SKILLTREE_ICE, 46, SPLF_TARGETED | SPLF_SUPPORT, 4, 5);
	SPELL_VAL(SPELLVAL_DAMAGE,		15.0,	1.5);	// percent damage reduction
	SPELL_VAL(SPELLVAL_DAMAGE2,		20,		0);		// percent freeze on being hit
	SPELL_VAL(SPELLVAL_COST,		30.0,	2.5);
	SPELL_VAL(SPELLVAL_COOLDOWN,	20.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	0.5,	0);
	SPELL_VAL(SPELLVAL_DURATION,	5.0,	0);
	// Armour points, which only the Ice Shield synergy grants -- so a base of 0 is correct, not a
	// missing row. Its own field because DAMAGE2 is the freeze chance.
	SPELL_VAL(SPELLVAL_AMOUNT,		0,		0);
	SPELL_REQ(0, SPL_HATRED, 1);
	SPELL_SYN(SPL_SHIVERINGARMOR, SPL_ICESHIELD_S, SPELLVAL_AMOUNT, 25, SYNF_FLAT);

	SPELL_DEF(SPL_AVALANCHE, DND_SKILLTREE_ICE, 52, 0, 2, 5);
	SPELL_VAL(SPELLVAL_DAMAGE,		16,		4);		// per ice
	SPELL_VAL(SPELLVAL_COST,		120.0,	15.0);
	SPELL_VAL(SPELLVAL_COOLDOWN,	50.0,	0);
	SPELL_VAL(SPELLVAL_CASTTIME,	2.0,	0);
	SPELL_VAL(SPELLVAL_AMOUNT,		75,		2);		// ice thrown
	SPELL_SCALE(SPELLVAL_DAMAGE);
	SPELL_REQ(0, SPL_BLIZZARD, 1);
	SPELL_REQ(1, SPL_WINTERORB, 1);
	// 2.5 truncates to 2 per rank: per_rank is read with >> 16 for a MORE synergy.
	SPELL_SYN(SPL_AVALANCHE, SPL_BLIZZARD, SPELLVAL_DAMAGE, 2.5, SYNF_MORE);
	SPELL_SYN(SPL_AVALANCHE, SPL_CHILLINGBREATH, SPELLVAL_DAMAGE, 2.5, SYNF_MORE);
	SPELL_SYN(SPL_AVALANCHE, SPL_GUSTOFFROST, SPELLVAL_DAMAGE, 2.5, SYNF_MORE);
}

#endif
